//! Authenticated Lightroom Classic integration installer for CreatorHub Desk.
//!
//! The archive is generated by CreatorHub for the signed-in Desk user. This
//! module treats it as untrusted input anyway: it caps size, accepts only the
//! the known plug-in files, rejects traversal/symlinks/duplicates and swaps
//! the installation atomically.

use std::collections::BTreeMap;
use std::fs;
use std::io::{Cursor, Read};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zip::ZipArchive;

use crate::{desk_identity, device_auth::DeviceToken, lightroom_broker};

const PLUGIN_DIR_NAME: &str = "CreatorHubNorge.lrplugin";
const TOOLKIT_IDENTIFIER: &str = "com.creatorhub.norge.lightroom";
const PLUGIN_MANIFEST_JSON: &str = include_str!(
    "../../../../backend/server/lightroom-plugin-template/CreatorHubNorge.lrplugin/CreatorHubManifest.json"
);
const MAX_ARCHIVE_BYTES: usize = 10 * 1024 * 1024;
const MAX_FILE_BYTES: u64 = 2 * 1024 * 1024;
const EXPECTED_FILES: [&str; 9] = [
    "Info.lua",
    "CreatorHubManifest.json",
    "PluginInit.lua",
    "PluginInfoProvider.lua",
    "ExportServiceProvider.lua",
    "CreatorHubDefaults.lua",
    "README.txt",
    "TranslatedStrings_en.txt",
    "TranslatedStrings_nb.txt",
];

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct PluginManifest {
    major: u32,
    minor: u32,
    revision: u32,
    build: u32,
    display_version: String,
}

fn plugin_manifest() -> Result<PluginManifest, String> {
    let manifest: PluginManifest = serde_json::from_str(PLUGIN_MANIFEST_JSON)
        .map_err(|error| format!("Ugyldig CreatorHub pluginmanifest: {error}"))?;
    let computed = format!(
        "{}.{}.{}.{}",
        manifest.major, manifest.minor, manifest.revision, manifest.build
    );
    if manifest.display_version != computed {
        return Err("CreatorHub pluginmanifest har inkonsistent versjon.".to_string());
    }
    Ok(manifest)
}

#[derive(Debug, Clone, Serialize)]
pub struct LightroomIntegrationStatus {
    pub classic_installed: bool,
    pub classic_path: Option<String>,
    pub plugin_installed: bool,
    pub plugin_path: String,
    pub plugin_version: Option<String>,
    pub plugin_account_email: Option<String>,
    pub plugin_update_required: bool,
    pub connected_user_email: Option<String>,
    pub restart_required: bool,
    pub plugin_runtime_active: bool,
    pub plugin_runtime_last_seen_seconds: Option<u64>,
    pub broker_running: bool,
    pub broker_url: String,
    pub broker_error: Option<String>,
}

#[cfg(target_os = "macos")]
fn lightroom_classic_candidates() -> Vec<PathBuf> {
    let mut candidates = vec![
        PathBuf::from("/Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app"),
        PathBuf::from("/Applications/Adobe Lightroom Classic.app"),
    ];
    if let Some(home) = dirs::home_dir() {
        candidates
            .push(home.join("Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app"));
        candidates.push(home.join("Applications/Adobe Lightroom Classic.app"));
    }
    candidates
}

#[cfg(target_os = "windows")]
fn lightroom_classic_candidates() -> Vec<PathBuf> {
    let mut candidates = Vec::new();
    for variable in ["PROGRAMFILES", "PROGRAMFILES(X86)"] {
        if let Ok(root) = std::env::var(variable) {
            let adobe = PathBuf::from(root).join("Adobe");
            candidates.push(adobe.join("Adobe Lightroom Classic").join("Lightroom.exe"));
            candidates.push(
                adobe
                    .join("Adobe Lightroom Classic")
                    .join("Adobe Lightroom Classic.exe"),
            );
        }
    }
    candidates
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn lightroom_classic_candidates() -> Vec<PathBuf> {
    Vec::new()
}

fn modules_dir() -> Result<PathBuf, String> {
    #[cfg(target_os = "macos")]
    {
        return dirs::home_dir()
            .map(|home| home.join("Library/Application Support/Adobe/Lightroom/Modules"))
            .ok_or_else(|| "Fant ikke brukerens hjemmemappe.".to_string());
    }
    #[cfg(target_os = "windows")]
    {
        return dirs::config_dir()
            .map(|root| root.join("Adobe/Lightroom/Modules"))
            .ok_or_else(|| "Fant ikke brukerens AppData-mappe.".to_string());
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    Err("Lightroom-installasjon støttes foreløpig på macOS og Windows.".to_string())
}

fn plugin_dir() -> Result<PathBuf, String> {
    Ok(modules_dir()?.join(PLUGIN_DIR_NAME))
}

fn installed_string_setting(path: &Path, setting: &str) -> Option<String> {
    let defaults = fs::read_to_string(path.join("CreatorHubDefaults.lua")).ok()?;
    let marker = format!("{setting} = \"");
    let start = defaults.find(&marker)? + marker.len();
    let rest = defaults.get(start..)?;
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn installed_plugin_version(path: &Path) -> Option<String> {
    installed_string_setting(path, "pluginVersion")
}

fn is_creatorhub_plugin(path: &Path) -> bool {
    fs::read_to_string(path.join("Info.lua"))
        .map(|contents| contents.contains(TOOLKIT_IDENTIFIER))
        .unwrap_or(false)
}

fn version_tuple(value: &str) -> Option<(u32, u32, u32, u32)> {
    let mut parts = value.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next()?.parse().ok()?;
    let build = parts.next().unwrap_or("0").parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some((major, minor, patch, build))
}

pub fn status(connected_user_email: Option<String>) -> Result<LightroomIntegrationStatus, String> {
    let manifest = plugin_manifest()?;
    let classic_path = lightroom_classic_candidates()
        .into_iter()
        .find(|candidate| candidate.exists());
    let plugin_path = plugin_dir()?;
    let plugin_installed = plugin_path.is_dir() && is_creatorhub_plugin(&plugin_path);
    let plugin_version = plugin_installed
        .then(|| installed_plugin_version(&plugin_path))
        .flatten();
    let plugin_account_email = plugin_installed
        .then(|| installed_string_setting(&plugin_path, "accountEmail"))
        .flatten();
    let version_update_required = plugin_installed
        && match plugin_version.as_deref().and_then(version_tuple) {
            Some(installed) => installed < version_tuple(&manifest.display_version).unwrap(),
            None => true,
        };
    let account_update_required = plugin_installed
        && match (
            plugin_account_email.as_deref(),
            connected_user_email.as_deref(),
        ) {
            (Some(installed), Some(connected)) => !installed.eq_ignore_ascii_case(connected),
            (None, Some(_)) => true,
            _ => false,
        };
    let broker_update_required = if plugin_installed {
        let installed_url = installed_string_setting(&plugin_path, "deskBrokerUrl");
        let installed_secret = installed_string_setting(&plugin_path, "deskBrokerSecret");
        let current_secret = desk_identity::load_or_create_lightroom_broker_secret()?;
        let current_url = lightroom_broker::broker_url();
        installed_url.as_deref() != Some(current_url.as_str())
            || installed_secret.as_deref() != Some(current_secret.as_str())
    } else {
        false
    };
    let plugin_update_required =
        version_update_required || account_update_required || broker_update_required;
    Ok(LightroomIntegrationStatus {
        classic_installed: classic_path.is_some(),
        classic_path: classic_path.map(|path| path.to_string_lossy().into_owned()),
        plugin_installed,
        plugin_version,
        plugin_account_email,
        plugin_update_required,
        plugin_path: plugin_path.to_string_lossy().into_owned(),
        connected_user_email,
        restart_required: false,
        plugin_runtime_active: lightroom_broker::runtime_is_active(),
        plugin_runtime_last_seen_seconds: lightroom_broker::runtime_last_seen_seconds(),
        broker_running: lightroom_broker::is_running(),
        broker_url: lightroom_broker::broker_url(),
        broker_error: lightroom_broker::last_error(),
    })
}

pub async fn download_and_install(
    device: &DeviceToken,
) -> Result<LightroomIntegrationStatus, String> {
    if !status(Some(device.user_email.clone()))?.classic_installed {
        return Err("Lightroom Classic ble ikke funnet på denne maskinen.".to_string());
    }
    let url = format!(
        "{}/api/desktop/me/lightroom-plugin",
        device.api_base.trim_end_matches('/')
    );
    let response = reqwest::Client::new()
        .get(url)
        .header("Authorization", format!("Bearer {}", device.token))
        .header(
            "User-Agent",
            concat!("creatorhub-one-desk/", env!("CARGO_PKG_VERSION")),
        )
        .send()
        .await
        .map_err(|error| format!("Kunne ikke hente Lightroom-plugin: {}", error))?;
    let response_status = response.status();
    if !response_status.is_success() {
        let body = response.text().await.unwrap_or_default();
        return Err(package_download_error(response_status.as_u16(), &body));
    }
    if let Some(length) = response.content_length() {
        if length > MAX_ARCHIVE_BYTES as u64 {
            return Err("Lightroom-pakken er større enn tillatt.".to_string());
        }
    }
    let archive = response
        .bytes()
        .await
        .map_err(|error| format!("Kunne ikke lese Lightroom-pakken: {}", error))?;
    if archive.len() > MAX_ARCHIVE_BYTES {
        return Err("Lightroom-pakken er større enn tillatt.".to_string());
    }

    let broker_secret = desk_identity::load_or_create_lightroom_broker_secret()?;
    install_archive_at_with_broker(
        &archive,
        &modules_dir()?,
        Some((&lightroom_broker::broker_url(), &broker_secret)),
    )?;
    let mut installed = status(Some(device.user_email.clone()))?;
    installed.restart_required = true;
    Ok(installed)
}

fn package_download_error(status: u16, body: &str) -> String {
    match status {
        401 | 403 => {
            "CreatorHub-innloggingen må fornyes før Lightroom-pluginen kan installeres.".to_string()
        }
        404 => "CreatorHub-serveren må oppdateres før Lightroom-pluginen kan installeres. Ingen filer ble endret.".to_string(),
        _ => {
            let server_message = serde_json::from_str::<serde_json::Value>(body)
                .ok()
                .and_then(|value| {
                    value
                        .get("error")
                        .or_else(|| value.get("message"))
                        .and_then(|entry| entry.as_str())
                        .map(str::to_owned)
                })
                .unwrap_or_else(|| body.chars().take(300).collect::<String>());
            format!(
                "CreatorHub avviste Lightroom-installasjonen ({}): {}",
                status, server_message
            )
        }
    }
}

fn validated_archive_files(archive: &[u8]) -> Result<BTreeMap<String, Vec<u8>>, String> {
    let mut zip = ZipArchive::new(Cursor::new(archive))
        .map_err(|error| format!("Ugyldig Lightroom ZIP: {}", error))?;
    let mut files = BTreeMap::new();
    let mut total_size = 0_u64;

    for index in 0..zip.len() {
        let entry = zip
            .by_index(index)
            .map_err(|error| format!("Les ZIP-element: {}", error))?;
        let enclosed = entry
            .enclosed_name()
            .ok_or_else(|| "Lightroom-pakken inneholder en utrygg filsti.".to_string())?;
        let normalized = enclosed.to_string_lossy().replace('\\', "/");
        if entry.is_dir() {
            if normalized.trim_end_matches('/') != PLUGIN_DIR_NAME {
                return Err("Lightroom-pakken inneholder en ukjent mappe.".to_string());
            }
            continue;
        }
        let prefix = format!("{}/", PLUGIN_DIR_NAME);
        let relative = normalized
            .strip_prefix(&prefix)
            .ok_or_else(|| "Lightroom-pakken har feil rotmappe.".to_string())?;
        if relative.contains('/') || !EXPECTED_FILES.contains(&relative) {
            return Err(format!(
                "Lightroom-pakken inneholder ukjent fil: {}",
                relative
            ));
        }
        if entry
            .unix_mode()
            .is_some_and(|mode| mode & 0o170000 == 0o120000)
        {
            return Err("Lightroom-pakken kan ikke inneholde symbolske lenker.".to_string());
        }
        if entry.size() > MAX_FILE_BYTES {
            return Err(format!(
                "Lightroom-filen {} er større enn tillatt.",
                relative
            ));
        }
        let mut bytes = Vec::with_capacity(entry.size() as usize);
        entry
            .take(MAX_FILE_BYTES + 1)
            .read_to_end(&mut bytes)
            .map_err(|error| format!("Les {}: {}", relative, error))?;
        if bytes.len() as u64 > MAX_FILE_BYTES {
            return Err(format!(
                "Lightroom-filen {} er større enn tillatt.",
                relative
            ));
        }
        total_size = total_size.saturating_add(bytes.len() as u64);
        if total_size > MAX_ARCHIVE_BYTES as u64 {
            return Err("Utpakket Lightroom-pakke er større enn tillatt.".to_string());
        }
        if files.insert(relative.to_string(), bytes).is_some() {
            return Err(format!(
                "Lightroom-pakken inneholder duplikat: {}",
                relative
            ));
        }
    }

    for required in EXPECTED_FILES {
        if !files.contains_key(required) {
            return Err(format!("Lightroom-pakken mangler {}.", required));
        }
    }
    let info = String::from_utf8_lossy(files.get("Info.lua").expect("validated required file"));
    if !info.contains(TOOLKIT_IDENTIFIER) {
        return Err("Lightroom-pakken har feil plugin-identitet.".to_string());
    }
    let packaged_manifest: PluginManifest = serde_json::from_slice(
        files
            .get("CreatorHubManifest.json")
            .expect("validated required file"),
    )
    .map_err(|error| format!("Lightroom-pakken har ugyldig pluginmanifest: {error}"))?;
    if packaged_manifest.display_version != plugin_manifest()?.display_version {
        return Err("Lightroom-pakken har en annen versjon enn CreatorHub Desk.".to_string());
    }
    Ok(files)
}

fn configure_files_for_desk(
    files: &mut BTreeMap<String, Vec<u8>>,
    broker_url: &str,
    broker_secret: &str,
) -> Result<(), String> {
    if broker_url != lightroom_broker::broker_url()
        || broker_secret.len() != 64
        || !broker_secret
            .chars()
            .all(|character| character.is_ascii_hexdigit())
    {
        return Err("Ugyldig lokal Lightroom SSO-konfigurasjon.".to_string());
    }
    let defaults = files
        .get_mut("CreatorHubDefaults.lua")
        .ok_or_else(|| "Lightroom-pakken mangler CreatorHubDefaults.lua.".to_string())?;
    let source = String::from_utf8(defaults.clone())
        .map_err(|_| "CreatorHubDefaults.lua er ikke UTF-8.".to_string())?;
    let mut replacements = 0_u8;
    let configured = source
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            let replacement = if trimmed.starts_with("pluginToken = ") {
                Some("  pluginToken = \"\",".to_string())
            } else if trimmed.starts_with("deskBrokerUrl = ") {
                Some(format!("  deskBrokerUrl = \"{broker_url}\","))
            } else if trimmed.starts_with("deskBrokerSecret = ") {
                Some(format!("  deskBrokerSecret = \"{broker_secret}\","))
            } else {
                None
            };
            if replacement.is_some() {
                replacements += 1;
            }
            replacement.unwrap_or_else(|| line.to_string())
        })
        .collect::<Vec<_>>()
        .join("\n");
    if replacements != 3 {
        return Err("Lightroom-pakken mangler forventede Desk SSO-felt.".to_string());
    }
    *defaults = format!("{configured}\n").into_bytes();
    Ok(())
}

fn install_archive_at_with_broker(
    archive: &[u8],
    modules: &Path,
    broker: Option<(&str, &str)>,
) -> Result<(), String> {
    let mut files = validated_archive_files(archive)?;
    if let Some((broker_url, broker_secret)) = broker {
        configure_files_for_desk(&mut files, broker_url, broker_secret)?;
    }
    fs::create_dir_all(modules).map_err(|error| format!("Opprett Lightroom Modules: {}", error))?;
    let target = modules.join(PLUGIN_DIR_NAME);
    if target.exists() && !is_creatorhub_plugin(&target) {
        return Err(
            "En ukjent plugin bruker allerede CreatorHub-mappen. Ingen filer ble overskrevet."
                .to_string(),
        );
    }

    let operation_id = Uuid::new_v4();
    let staging = modules.join(format!(".{}.installing-{}", PLUGIN_DIR_NAME, operation_id));
    let backup = modules.join(format!(".{}.backup-{}", PLUGIN_DIR_NAME, operation_id));
    fs::create_dir(&staging).map_err(|error| format!("Opprett staging-mappe: {}", error))?;

    let write_result = (|| -> Result<(), String> {
        for (name, contents) in &files {
            let path = staging.join(name);
            fs::write(&path, contents).map_err(|error| format!("Skriv {}: {}", name, error))?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                fs::set_permissions(&path, fs::Permissions::from_mode(0o600))
                    .map_err(|error| format!("Sett filrettigheter for {}: {}", name, error))?;
            }
        }

        if target.exists() {
            fs::rename(&target, &backup)
                .map_err(|error| format!("Sikre forrige Lightroom-plugin: {}", error))?;
        }
        if let Err(error) = fs::rename(&staging, &target) {
            if backup.exists() {
                let _ = fs::rename(&backup, &target);
            }
            return Err(format!("Aktiver Lightroom-plugin: {}", error));
        }
        if backup.exists() {
            let _ = fs::remove_dir_all(&backup);
        }
        Ok(())
    })();

    if write_result.is_err() && staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }
    write_result
}

#[cfg(test)]
fn install_archive_at(archive: &[u8], modules: &Path) -> Result<(), String> {
    install_archive_at_with_broker(archive, modules, None)
}

pub fn uninstall() -> Result<LightroomIntegrationStatus, String> {
    let target = plugin_dir()?;
    if target.exists() {
        if !is_creatorhub_plugin(&target) {
            return Err("Mappen tilhører ikke CreatorHub og ble ikke fjernet.".to_string());
        }
        fs::remove_dir_all(&target)
            .map_err(|error| format!("Fjern Lightroom-plugin: {}", error))?;
    }
    status(None)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::tempdir;
    use zip::ZipWriter;
    use zip::write::SimpleFileOptions;

    fn test_archive(extra: Option<(&str, &[u8])>) -> Vec<u8> {
        let cursor = Cursor::new(Vec::new());
        let mut writer = ZipWriter::new(cursor);
        for name in EXPECTED_FILES {
            writer
                .start_file(
                    format!("{}/{}", PLUGIN_DIR_NAME, name),
                    SimpleFileOptions::default(),
                )
                .unwrap();
            let body = if name == "Info.lua" {
                format!("LrToolkitIdentifier = '{}'", TOOLKIT_IDENTIFIER)
            } else if name == "CreatorHubManifest.json" {
                PLUGIN_MANIFEST_JSON.to_string()
            } else if name == "CreatorHubDefaults.lua" {
                concat!(
                    "return {\n",
                    "  pluginToken = \"legacy-token\",\n",
                    "  pluginVersion = \"1.4.0.2\",\n",
                    "  deskBrokerUrl = \"\",\n",
                    "  deskBrokerSecret = \"\",\n",
                    "}\n",
                )
                .to_string()
            } else {
                format!("-- {}", name)
            };
            writer.write_all(body.as_bytes()).unwrap();
        }
        if let Some((name, body)) = extra {
            writer
                .start_file(name, SimpleFileOptions::default())
                .unwrap();
            writer.write_all(body).unwrap();
        }
        writer.finish().unwrap().into_inner()
    }

    #[test]
    fn installs_only_the_expected_creatorhub_plugin_files() {
        let temp = tempdir().unwrap();
        install_archive_at(&test_archive(None), temp.path()).unwrap();
        let installed = temp.path().join(PLUGIN_DIR_NAME);
        assert!(is_creatorhub_plugin(&installed));
        assert_eq!(
            installed_plugin_version(&installed).as_deref(),
            Some("1.4.0.2")
        );
        assert_eq!(
            fs::read_dir(installed).unwrap().count(),
            EXPECTED_FILES.len()
        );
    }

    #[test]
    fn rejects_archive_path_traversal_and_unknown_files() {
        let temp = tempdir().unwrap();
        let archive = test_archive(Some(("CreatorHubNorge.lrplugin/../../escape.lua", b"bad")));
        assert!(install_archive_at(&archive, temp.path()).is_err());
        assert!(!temp.path().join("escape.lua").exists());
    }

    #[test]
    fn refuses_to_overwrite_a_foreign_plugin_directory() {
        let temp = tempdir().unwrap();
        let target = temp.path().join(PLUGIN_DIR_NAME);
        fs::create_dir(&target).unwrap();
        fs::write(target.join("Info.lua"), "foreign").unwrap();
        let error = install_archive_at(&test_archive(None), temp.path()).unwrap_err();
        assert!(error.contains("ukjent plugin"));
        assert_eq!(
            fs::read_to_string(target.join("Info.lua")).unwrap(),
            "foreign"
        );
    }

    #[test]
    fn explains_missing_production_endpoint_without_exposing_raw_response() {
        let message = package_download_error(
            404,
            r#"{"message":"Endpoint not implemented","path":"/api/desktop/me/lightroom-plugin"}"#,
        );
        assert!(message.contains("serveren må oppdateres"));
        assert!(!message.contains("Endpoint not implemented"));
    }

    #[test]
    fn desk_install_removes_cloud_token_and_injects_loopback_capability() {
        let temp = tempdir().unwrap();
        let secret = "a".repeat(64);
        install_archive_at_with_broker(
            &test_archive(None),
            temp.path(),
            Some((&lightroom_broker::broker_url(), &secret)),
        )
        .unwrap();
        let defaults = fs::read_to_string(
            temp.path()
                .join(PLUGIN_DIR_NAME)
                .join("CreatorHubDefaults.lua"),
        )
        .unwrap();
        assert!(defaults.contains("pluginToken = \"\""));
        assert!(defaults.contains("deskBrokerUrl = \"http://127.0.0.1:48653\""));
        assert!(defaults.contains(&format!("deskBrokerSecret = \"{secret}\"")));
        assert!(!defaults.contains("legacy-token"));
    }

    #[test]
    fn compares_plugin_versions_without_downgrading_future_versions() {
        let current = plugin_manifest().unwrap().display_version;
        assert!(version_tuple("1.2.9") < version_tuple(&current));
        assert_eq!(version_tuple("1.4.0.3"), version_tuple(&current));
        assert!(version_tuple("1.5.0") > version_tuple(&current));
        assert!(version_tuple("1.4.0.2") < version_tuple(&current));
        assert!(version_tuple("1.4.0.1") < version_tuple(&current));
        assert!(version_tuple("invalid").is_none());
    }
}
