#!/bin/bash
# Setup script for Multi-Angle Sync Environment
# This script creates a virtual environment and installs all required dependencies

set -e  # Exit on error

echo "🚀 Setting up Multi-Angle Sync Environment..."
echo ""

# Check Python version
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
echo "📦 Python version: $PYTHON_VERSION"

# Check if Python 3.9+
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 9 ]); then
    echo "❌ Error: Python 3.9 or later is required"
    exit 1
fi

# Create virtual environment
VENV_DIR="venv-sync"
if [ -d "$VENV_DIR" ]; then
    echo "⚠️  Virtual environment already exists. Removing old one..."
    rm -rf "$VENV_DIR"
fi

echo "📦 Creating virtual environment: $VENV_DIR"
python3 -m venv "$VENV_DIR"

# Activate virtual environment
echo "🔌 Activating virtual environment..."
source "$VENV_DIR/bin/activate"

# Upgrade pip
echo "⬆️  Upgrading pip..."
pip install --upgrade pip setuptools wheel

# Install PyTorch (CPU version by default, can be changed to CUDA)
echo ""
echo "🔥 Installing PyTorch..."
pip install torch torchvision torchaudio

# Install core dependencies
echo ""
echo "📚 Installing core dependencies..."
pip install numpy opencv-python redis psycopg2-binary

# Install audio processing
echo ""
echo "🎵 Installing audio processing libraries..."
pip install torchaudio

# Install SyncNet
echo ""
echo "🎬 Installing SyncNet (audio-visual sync)..."
pip install syncnet-python

# Install transformers for Synchformer
echo ""
echo "🤖 Installing HuggingFace transformers..."
pip install transformers

# Try to install Synchformer from GitHub
echo ""
echo "📹 Attempting to install Synchformer from GitHub..."
if pip install git+https://github.com/v-iashin/Synchformer.git 2>/dev/null; then
    echo "✅ Synchformer installed from GitHub"
else
    echo "⚠️  Synchformer GitHub install failed, will use HuggingFace model instead"
fi

# Install additional utilities
echo ""
echo "🛠️  Installing additional utilities..."
pip install tqdm    # Progress bars
pip install boto3   # AWS SDK for R2 upload (optional but recommended)
pip install psycopg2-binary  # PostgreSQL adapter (for fine-tuning database access)

# Try to install decord (optional, may fail on some systems)
echo "   Attempting to install decord (optional)..."
pip install decord 2>/dev/null || echo "   ⚠️  decord not available (optional, skipping)"

# Create weights directory
echo ""
echo "📁 Creating weights directory..."
mkdir -p weights
mkdir -p models

# Download SyncNet model weights (if URLs are available)
echo ""
echo "⬇️  Downloading SyncNet model weights..."
cd weights

# Note: These URLs may need to be updated with actual download links
# For now, we'll create a script to download them manually
cat > download_syncnet_weights.sh << 'EOF'
#!/bin/bash
# Download SyncNet model weights
# Update these URLs with actual download links when available

echo "📥 Downloading SyncNet model weights..."
echo ""
echo "⚠️  Please download the following files manually:"
echo "   1. sfd_face.pth - Face detection model"
echo "   2. syncnet_v2.model - SyncNet model weights"
echo ""
echo "Place them in the weights/ directory"
echo ""
echo "You can find these files at:"
echo "  - SyncNet repository: https://github.com/joonson/syncnet_python"
echo "  - Or check the syncnet-python PyPI page for download links"
EOF

chmod +x download_syncnet_weights.sh

cd ..

# Download Synchformer model from HuggingFace
echo ""
echo "⬇️  Downloading Synchformer model from HuggingFace..."
python3 << 'PYTHON_SCRIPT'
import os
from transformers import AutoModel

try:
    print("Downloading Synchformer model from HuggingFace...")
    model = AutoModel.from_pretrained('AmrMKayid/synchformer-hf')
    print("✅ Synchformer model downloaded successfully")
except Exception as e:
    print(f"⚠️  Could not download Synchformer model: {e}")
    print("   You can download it later with:")
    print("   python -c \"from transformers import AutoModel; AutoModel.from_pretrained('AmrMKayid/synchformer-hf')\"")
PYTHON_SCRIPT

# Create requirements.txt
echo ""
echo "📝 Creating requirements.txt..."
cat > requirements-sync.txt << EOF
# Multi-Angle Sync Environment Requirements
# Generated by setup-sync-environment.sh

# PyTorch
torch>=2.0.0
torchvision>=0.15.0
torchaudio>=2.0.0

# Core dependencies
numpy>=1.24.0
opencv-python>=4.8.0
redis>=5.0.0
psycopg2-binary>=2.9.0

# Audio/Video processing
torchaudio>=2.0.0
decord>=0.6.0

# Sync models
syncnet-python>=0.1.0
transformers>=4.30.0

# Utilities
tqdm>=4.65.0
boto3>=1.28.0  # AWS SDK for R2 upload (optional but recommended)
psycopg2-binary>=2.9.0  # PostgreSQL adapter (for fine-tuning)
EOF

# Create activation script
echo ""
echo "📝 Creating activation script..."
cat > activate-sync-env.sh << 'EOF'
#!/bin/bash
# Activate the sync environment

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/venv-sync/bin/activate"

echo "✅ Sync environment activated!"
echo "   Python: $(which python)"
echo "   Pip: $(which pip)"
echo ""
echo "To deactivate, run: deactivate"
EOF

chmod +x activate-sync-env.sh

# Test installation
echo ""
echo "🧪 Testing installation..."
python3 << 'PYTHON_SCRIPT'
import sys

print("Testing installed packages...\n")

packages = {
    'torch': 'PyTorch',
    'torchvision': 'TorchVision',
    'torchaudio': 'TorchAudio',
    'numpy': 'NumPy',
    'cv2': 'OpenCV',
    'redis': 'Redis',
    'transformers': 'Transformers',
}

failed = []

for module, name in packages.items():
    try:
        __import__(module)
        print(f"✅ {name}: Available")
    except ImportError:
        print(f"❌ {name}: Not available")
        failed.append(name)

# Test SyncNet
try:
    from syncnet import SyncNet
    print("✅ SyncNet: Available")
except ImportError:
    print("⚠️  SyncNet: Not available (may need model weights)")

print("\n" + "="*50)
if failed:
    print(f"⚠️  {len(failed)} package(s) failed to import: {', '.join(failed)}")
else:
    print("✅ All core packages installed successfully!")
print("="*50)
PYTHON_SCRIPT

echo ""
echo "✅ Setup complete!"
echo ""
echo "📋 Next steps:"
echo "   1. Activate the environment: source activate-sync-env.sh"
echo "   2. Download SyncNet model weights:"
echo "      cd weights && ./download_syncnet_weights.sh"
echo "   3. Test the sync worker:"
echo "      python server/workers/video-sync-worker.py"
echo ""
echo "💡 To activate the environment in the future:"
echo "   source activate-sync-env.sh"
echo ""
echo "💡 To deactivate:"
echo "   deactivate"

