/**
 * CreatorHub Norge - Resume Builder
 * Advanced CV builder for Norwegian professionals
 * Features: AI assistance, ATS optimization, Norwegian job tracking, project integration
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useAuth } from '@/hooks/useAuth';
import { useAutoSave } from '@/hooks/useAutosave';
import { useEnhancedMasterIntegration } from '../../integration/EnhancedMasterIntegrationProvider';
import CreatorHubMarketplace from './ResumeBuilderMarketplace';
import {
  Box,
  Container,
  Paper,
  Typography,
  Button,
  Stepper,
  Step,
  StepLabel,
  StepContent,
  TextField,
  Grid,
  Card,
  CardContent,
  CardActions,
  IconButton,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  LinearProgress,
  Alert,
  Tabs,
  Tab,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Tooltip,
  Badge,
  Stack,
  Divider,
  Avatar,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemSecondaryAction,
  Fab,
  Menu,
  MenuItem as MenuItemComponent,
  Switch,
  FormControlLabel,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  CircularProgress,
  Autocomplete,
} from '@mui/material';
import {
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Download as DownloadIcon,
  Visibility as PreviewIcon,
  Assessment as AnalyzeIcon,
  AutoAwesome as AIIcon,
  AutoAwesome,
  Spellcheck,
  CheckCircle as CheckIcon,
  Warning as WarningIcon,
  Work as WorkIcon,
  School as EducationIcon,
  Star as SkillIcon,
  EmojiEvents as CertificationIcon,
  Folder as ProjectIcon,
  Public as PublicIcon,
  Lock as PrivateIcon,
  Save as SaveIcon,
  Share as ShareIcon,
  ContentCopy as CopyIcon,
  Refresh as RefreshIcon,
  ArrowBack as BackIcon,
  ArrowForward as ForwardIcon,
  ExpandMore as ExpandMoreIcon,
  TrendingUp as TrendingUpIcon,
  Description as TemplateIcon,
  Settings as SettingsIcon,
  CloudUpload as UploadIcon,
  Link as LinkIcon,
  BusinessCenter as BusinessIcon,
  Email as EmailIcon,
  Phone as PhoneIcon,
  LocationOn as LocationIcon,
  Language as WebsiteIcon,
  LinkedIn as LinkedInIcon,
  GitHub as GitHubIcon,
  Folder as FolderIcon,
  PictureAsPdf as PdfIcon,
  Image as ImageIcon,
  VideoFile as VideoIcon,
  InsertDriveFile as FileIcon,
  Error as ErrorIcon,
  History as HistoryIcon,
  Restore as RestoreIcon,
  Publish as PublishIcon,
} from '@mui/icons-material';

// ============================================================================
// INTERFACES
// ============================================================================

interface Resume {
  id: string;
  userId: string;
  title: string;
  slug: string;
  personalInfo: {
    fullName: string;
    email: string;
    phone?: string;
    location?: string;
    website?: string;
    linkedin?: string;
    github?: string;
    portfolio?: string;
    profilePhoto?: string;
    professionalTitle?: string;
    summary?: string;
  };
  templateId: string;
  colorScheme: string;
  atsScore: number;
  atsOptimized: boolean;
  keywords: string[];
  targetJobTitle?: string;
  targetIndustry?: string;
  status: 'draft' | 'active' | 'archived';
  isPublic: boolean;
  publicUrl?: string;
  language: string;
  createdAt: string;
  updatedAt: string;
  experiences?: ResumeExperience[];
  education?: ResumeEducation[];
  skills?: ResumeSkill[];
  certifications?: ResumeCertification[];
  projects?: ResumeProject[];
}

interface ResumeExperience {
  id: string;
  resumeId: string;
  jobTitle: string;
  company: string;
  location?: string;
  employmentType?: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'self-employed';
  startDate: string;
  endDate?: string;
  isCurrent: boolean;
  description?: string;
  achievements: string[];
  skills: string[];
  projectId?: string;
  autoGenerated: boolean;
  displayOrder: number;
  isVisible: boolean;
}

interface ResumeEducation {
  id: string;
  resumeId: string;
  degree: string;
  fieldOfStudy?: string;
  institution: string;
  location?: string;
  startDate: string;
  endDate?: string;
  isCurrent: boolean;
  grade?: string;
  description?: string;
  achievements: string[];
  displayOrder: number;
  isVisible: boolean;
}

interface ResumeSkill {
  id: string;
  resumeId: string;
  name: string;
  category?: string;
  proficiencyLevel: number;
  yearsOfExperience?: number;
  isEndorsed: boolean;
  displayOrder: number;
  isVisible: boolean;
}

interface ResumeCertification {
  id: string;
  resumeId: string;
  name: string;
  issuer: string;
  issueDate: string;
  expiryDate?: string;
  credentialId?: string;
  credentialUrl?: string;
  description?: string;
  displayOrder: number;
  isVisible: boolean;
}

interface ResumeProject {
  id: string;
  resumeId: string;
  title: string;
  description?: string;
  role?: string;
  startDate?: string;
  endDate?: string;
  technologies: string[];
  achievements: string[];
  projectUrl?: string;
  images: string[];
  projectId?: string;
  autoGenerated: boolean;
  displayOrder: number;
  isVisible: boolean;
}

interface ResumeTemplate {
  id: string;
  name: string;
  description?: string;
  category: string;
  atsScore: number;
  isAtsOptimized: boolean;
  layout: 'single-column' | 'two-column' | 'modern-split';
  previewImage?: string;
  isPremium: boolean;
}

interface JobApplication {
  id: string;
  userId: string;
  resumeId?: string;
  jobTitle: string;
  company: string;
  location?: string;
  jobUrl?: string;
  source?: string;
  status: 'saved' | 'applied' | 'interviewing' | 'offer' | 'rejected' | 'accepted' | 'withdrawn';
  appliedDate?: string;
  notes?: string;
  priority: 'low' | 'medium' | 'high';
  tags: string[];
}

interface GoogleDriveLink {
  id: string;
  name: string;
  url: string;
  type: 'pdf' | 'image' | 'video' | 'document' | 'folder' | 'other';
  size?: string;
  lastModified?: string;
}

interface PortfolioItem {
  id?: string;
  resumeId?: string;
  title: string;
  description: string;
  category: 'project' | 'design' | 'documentation' | 'presentation' | 'other';
  technologies?: string[];
  googleDriveLinks?: GoogleDriveLink[];
  isPublic: boolean;
  createdAt?: string;
  updatedAt?: string;
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export default function ResumeBuilder() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const { auth, features, analytics } = useEnhancedMasterIntegration();

  // Feature access checks
  const resumeBuilderAccess = features.checkFeatureAccess('resume-builder, ');
  const googleDriveAccess = features.checkFeatureAccess('google-drive-integration,');
  const portfolioAccess = features.checkFeatureAccess('portfolio-management,');

  // State Management
  const [activeStep, setActiveStep] = useState(0);
  const [selectedResume, setSelectedResume] = useState<Resume | null>(null);
  const [showTemplateDialog, setShowTemplateDialog] = useState(false);
  const [showExportDialog, setShowExportDialog] = useState(false);
  const [showAIDialog, setShowAIDialog] = useState(false);
  const [showProjectImportDialog, setShowProjectImportDialog] = useState(false);
  const [tabValue, setTabValue] = useState(0);
  const [aiJobDescription, setAiJobDescription] = useState('');
  
  // Portfolio state
  const [portfolioItems, setPortfolioItems] = useState<PortfolioItem[]>([]);
  const [showPortfolioDialog, setShowPortfolioDialog] = useState(false);
  const [editingPortfolioItem, setEditingPortfolioItem] = useState<PortfolioItem | null>(null);
  const [portfolioFormData, setPortfolioFormData] = useState<Partial<PortfolioItem>>({
    title: '',
    description: '',
    category: 'project',
    technologies: [],
    googleDriveLinks: [],
    isPublic: true,
  });

  // Draft and versioning state
  const [isDraft, setIsDraft] = useState(true);
  const [currentVersion, setCurrentVersion] = useState(1);
  const [versionHistory, setVersionHistory] = useState<any[]>([]);
  const [showVersionDialog, setShowVersionDialog] = useState(false);
  const [autoSaveStatus, setAutoSaveStatus] = useState<'saved' | 'saving' | 'error' | 'pending'>('saved');

  // Auto-save integration
  const autoSave = useAutoSave({
    config: {
      enabled: true,
      debounceMs: 2000, // Auto-save after 2 seconds of inactivity
      retryAttempts: 3,
      retryDelayMs: 1000,
    },
    onDataSaved: (data) => {
      setAutoSaveStatus('saved');
      analytics.trackEvent('resume_autosaved', {
        userId: user?.id,
        resumeId: selectedResume?.id,
        dataType: data.type,
      });
      console.log('✅ Resume auto-saved: ', data);
    },
    onDataQueued: () => {
      setAutoSaveStatus('pending');
    },
    onError: (error) => {
      setAutoSaveStatus('error');
      console.error('❌ Auto-save error: ', error);
    },
    onInitialized: () => {
      console.log('🔄 Auto-save initialized for Resume Builder');
    },
  });

  // Google Drive integration functions
  const handleGoogleDriveFilePicker = useCallback(async () => {
    // Check feature access
    if (!googleDriveAccess.hasAccess) {
      console.warn('Google Drive integration not available:', googleDriveAccess.reason);
      alert('Google Drive-integrasjon er ikke tilgjengelig: ' + googleDriveAccess.reason);
      return;
    }

    try {
      // Track feature usage
      features.trackFeatureUsage('google-drive-integration, ','file_picker_opened');
      analytics.trackEvent('google_drive_picker_opened', { userId: user?.id });

      if (!auth.state.isAuthenticated) {
        await auth.login();
        return;
      }

      const authHeader = await auth.getAuthHeader();
      const googleClient = await auth.getAuthenticatedClient(['https://www.googleapis.com/auth/drive.readonly']);
      
      // Initialize Google Drive API picker
      if (window.google && window.google.picker) {
        const picker = new window.google.picker.PickerBuilder()
          .addView(window.google.picker.ViewId.DOCS)
          .addView(window.google.picker.ViewId.SPREADSHEETS)
          .addView(window.google.picker.ViewId.PRESENTATIONS)
          .addView(window.google.picker.ViewId.PDFS)
          .addView(window.google.picker.ViewId.IMAGES)
          .addView(window.google.picker.ViewId.VIDEOS)
          .setOAuthToken(googleClient.getToken().access_token)
          .setDeveloperKey(process.env.NEXT_PUBLIC_GOOGLE_API_KEY)
          .setCallback(handleGoogleDriveFilesSelected)
          .build();
        
        picker.setVisible(true);
      } else {
        console.error('Google Picker API not loaded');
        // Fallback: manual URL input
        const url = prompt('Please enter the Google Drive file URL:');
        if (url) {
          handleManualGoogleDriveLink(url);
        }
      }
    } catch (error) {
      console.error('Google Drive picker error:', error);
      // Fallback to manual URL input
      const url = prompt('Please enter the Google Drive file URL:');
      if (url) {
        handleManualGoogleDriveLink(url);
      }
    }
  }, [auth]);

  const handleGoogleDriveFilesSelected = useCallback((data: any) => {
    if (data.action === window.google.picker.Action.PICKED) {
      const files = data.docs;
      const newLinks: GoogleDriveLink[] = files.map((file: any) => ({
        id: file.id,
        name: file.name,
        url: file.url,
        type: getFileTypeFromMimeType(file.mimeType),
        size: formatFileSize(file.sizeBytes),
        lastModified: new Date(file.lastEditedUtc).toLocaleDateString(),
      }));

      setPortfolioFormData(prev => ({
        ...prev,
        googleDriveLinks: [...(prev.googleDriveLinks || []), ...newLinks]
      }));

      // Track successful file selection
      features.trackFeatureUsage('google-drive-integration','files_selected', { fileCount: files.length });
      analytics.trackEvent('google_drive_files_selected', { 
        userId: user?.id,
        fileCount: files.length,
        fileTypes: files.map((f: any) => getFileTypeFromMimeType(f.mimeType))
      });
    }
  }, [features, analytics, user]);

  const handleManualGoogleDriveLink = useCallback((url: string) => {
    const link: GoogleDriveLink = {
      id: `manual_${Date.now()}`,
      name: 'Manual Link',
      url: url,
      type: 'other',
    };

    setPortfolioFormData(prev => ({
      ...prev,
      googleDriveLinks: [...(prev.googleDriveLinks || []), link]
    }));
  }, []);

  const getFileTypeFromMimeType = (mimeType: string): GoogleDriveLink['type'] => {
    if (mimeType.includes('pdf')) return 'pdf';
    if (mimeType.includes('image')) return 'image';
    if (mimeType.includes('video')) return 'video';
    if (mimeType.includes('document') || mimeType.includes('text')) return 'document';
    if (mimeType.includes('folder')) return 'folder';
    return 'other';
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes','KB','MB','GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ', ' + sizes[i];
  };

  const getFileIcon = (type: GoogleDriveLink['type']) => {
    switch (type) {
      case 'pdf': return <PdfIcon />;
      case 'image': return <ImageIcon />;
      case 'video': return <VideoIcon />;
      case 'document': return <FileIcon />;
      case 'folder': return <FolderIcon />;
      default: return <FileIcon />;
    }
  };

  // Portfolio management functions
  const handleAddPortfolioItem = useCallback(() => {
    // Check feature access
    if (!portfolioAccess.hasAccess) {
      console.warn('Portfolio management not available:', portfolioAccess.reason);
      alert('Portefølje-administrasjon er ikke tilgjengelig: ' + portfolioAccess.reason);
      return;
    }

    // Track feature usage
    features.trackFeatureUsage('portfolio-management','add_portfolio_item_dialog_opened');
    analytics.trackEvent('portfolio_item_add_started', { userId: user?.id });

    setEditingPortfolioItem(null);
    setPortfolioFormData({
      title: '',
      description: '',
      category: 'project',
      technologies: [],
      googleDriveLinks: [],
      isPublic: true,
    });
    setShowPortfolioDialog(true);
  }, [portfolioAccess, features, analytics, user]);

  const handleEditPortfolioItem = useCallback((item: PortfolioItem) => {
    setEditingPortfolioItem(item);
    setPortfolioFormData(item);
    setShowPortfolioDialog(true);
  }, []);

  const handleSavePortfolioItem = useCallback(async () => {
    try {
      // Track portfolio item save
      features.trackFeatureUsage('portfolio-management','portfolio_item_saved', {
        isEdit: !!editingPortfolioItem,
        hasGoogleDriveLinks: (portfolioFormData.googleDriveLinks?.length || 0) > 0,
        category: portfolioFormData.category
      });

      analytics.trackEvent('portfolio_item_saved', {
        userId: user?.id,
        isEdit: !!editingPortfolioItem,
        itemId: editingPortfolioItem?.id || `new_${Date.now()}`,
        category: portfolioFormData.category,
        googleDriveLinksCount: portfolioFormData.googleDriveLinks?.length || 0,
        technologiesCount: portfolioFormData.technologies?.length || 0
      });

      if (editingPortfolioItem) {
        // Update existing item
        const updatedItems = portfolioItems.map(item =>
          item.id === editingPortfolioItem.id
            ? { ...portfolioFormData, id: editingPortfolioItem.id, updatedAt: new Date().toISOString() }
            : item
        );
        setPortfolioItems(updatedItems);
      } else {
        // Add new item
        const newItem: PortfolioItem = {
          ...portfolioFormData,
          id: `portfolio_${Date.now()}`,
          resumeId: selectedResume?.id,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        } as PortfolioItem;
        setPortfolioItems(prev => [...prev, newItem]);
      }
      
      setShowPortfolioDialog(false);
      setEditingPortfolioItem(null);
      setPortfolioFormData({
        title: '',
        description: '',
        category: 'project',
        technologies: [],
        googleDriveLinks: [],
        isPublic: true,
      });
    } catch (error) {
      console.error('Error saving portfolio item:', error);
    }
  }, [editingPortfolioItem, portfolioFormData, portfolioItems, selectedResume, features, analytics, user]);

  const handleDeletePortfolioItem = useCallback((itemId: string) => {
    setPortfolioItems(prev => prev.filter(item => item.id !== itemId));
    
    // Track deletion
    analytics.trackEvent('portfolio_item_deleted', {
      userId: user?.id,
      itemId,
    });
  }, [analytics, user]);

  // ============================================================================
  // DRAFT & VERSIONING FUNCTIONS
  // ============================================================================

  // Auto-save resume data whenever it changes
  useEffect(() => {
    if (selectedResume && user) {
      setAutoSaveStatus('pending');
      
      // Queue auto-save with debouncing
      autoSave.save('resume_draft', {
        resume: selectedResume,
        portfolioItems,
        isDraft,
        version: currentVersion,
        userId: user.id,
      }, {
        resumeId: selectedResume.id,
        timestamp: Date.now(),
      });
    }
  }, [selectedResume, portfolioItems, isDraft, currentVersion, user, autoSave]);

  // Save as draft
  const handleSaveAsDraft = useCallback(async () => {
    if (!selectedResume) return;

    try {
      setAutoSaveStatus('saving');
      
      // Force immediate save
      await autoSave.forceSave();
      
      // Update draft status
      setIsDraft(true);
      
      // Track draft save
      features.trackFeatureUsage('resume-builder','draft_saved');
      analytics.trackEvent('resume_draft_saved', {
        userId: user?.id,
        resumeId: selectedResume.id,
        version: currentVersion,
      });
      
      setAutoSaveStatus('saved');
      console.log('✅ Draft saved successfully');
    } catch (error) {
      setAutoSaveStatus('error');
      console.error('❌ Error saving draft:', error);
    }
  }, [selectedResume, currentVersion, autoSave, features, analytics, user]);

  // Publish resume (exit draft mode)
  const handlePublishResume = useCallback(async () => {
    if (!selectedResume) return;

    try {
      setAutoSaveStatus('saving');
      
      // Force save before publishing
      await autoSave.forceSave();
      
      // Create new version
      const newVersion = {
        id: `version_${Date.now()}`,
        resumeId: selectedResume.id,
        versionNumber: currentVersion,
        data: { ...selectedResume, portfolioItems },
        createdAt: new Date().toISOString(),
        publishedBy: user?.id,
      };
      
      setVersionHistory(prev => [...prev, newVersion]);
      setCurrentVersion(prev => prev + 1);
      setIsDraft(false);
      
      // Track publication
      features.trackFeatureUsage('resume-builder','resume_published');
      analytics.trackEvent('resume_published', {
        userId: user?.id,
        resumeId: selectedResume.id,
        version: currentVersion,
      });
      
      setAutoSaveStatus('saved');
      console.log('✅ Resume published successfully - Version', currentVersion);
    } catch (error) {
      setAutoSaveStatus('error');
      console.error('❌ Error publishing resume:', error);
    }
  }, [selectedResume, currentVersion, portfolioItems, autoSave, features, analytics, user]);

  // Restore from version
  const handleRestoreVersion = useCallback((version: any) => {
    if (!version.data) return;

    // Restore resume data
    setSelectedResume(version.data);
    setPortfolioItems(version.data.portfolioItems || []);
    setCurrentVersion(version.versionNumber + 1);
    setIsDraft(true);
    
    // Track version restoration
    features.trackFeatureUsage('resume-builder','version_restored');
    analytics.trackEvent('resume_version_restored', {
      userId: user?.id,
      resumeId: version.resumeId,
      restoredVersion: version.versionNumber,
      newVersion: version.versionNumber + 1,
    });
    
    setShowVersionDialog(false);
    console.log('✅ Version restored:', version.versionNumber);
  }, [features, analytics, user]);

  // Restore from auto-save backup
  const handleRestoreFromBackup = useCallback(() => {
    const restored = autoSave.restoreFromBackup();
    
    if (restored) {
      // Track backup restoration
      features.trackFeatureUsage('resume-builder','backup_restored');
      analytics.trackEvent('resume_backup_restored', {
        userId: user?.id,
      });
      
      console.log('✅ Backup restored successfully');
      alert('Tidligere lagret versjon er gjenopprettet!');
    } else {
      console.warn('⚠️ No backup available to restore');
      alert('Ingen backup tilgjengelig');
    }
  }, [autoSave, features, analytics, user]);

  const handleRemoveGoogleDriveLink = useCallback((linkId: string) => {
    setPortfolioFormData(prev => ({
      ...prev,
      googleDriveLinks: prev.googleDriveLinks?.filter(link => link.id !== linkId) || []
    }));
  }, []);

  // ============================================================================
  // AI WRITING TOOLS - QuillBot-style Features
  // ============================================================================

  const [aiToolDialog, setAiToolDialog] = useState(false);
  const [aiToolType, setAiToolType] = useState<'paraphrase' | 'grammar' | 'summarize' | 'generate-resume' | 'generate-cover-letter'>('paraphrase');
  const [aiInputText, setAiInputText] = useState('');
  const [aiOutputText, setAiOutputText] = useState('');
  const [aiParaphraseMode, setAiParaphraseMode] = useState('standard');
  const [aiIsProcessing, setAiIsProcessing] = useState(false);
  const [aiTargetField, setAiTargetField] = useState<string>('');

  // LinkedIn Import State
  const [linkedInDialog, setLinkedInDialog] = useState(false);
  const [linkedInImportMode, setLinkedInImportMode] = useState<'preview' | 'select'>('select');
  const [linkedInData, setLinkedInData] = useState<any>(null);
  const [linkedInSelectedData, setLinkedInSelectedData] = useState({
    personalInfo: true,
    workExperience: true,
    education: true,
    skills: true,
    certifications: true,
  });

  // AI Paraphrase modes (same as QuillBot)
  const aiParaphraseModes = [
    { value: 'standard', label: 'Standard', description: 'Balansert omskriving' },
    { value: 'fluency', label: 'Fluency', description: 'Forbedrer flyt og lesbarhet' },
    { value: 'creative', label: 'Creative', description: 'Kreativ og originell omskriving' },
    { value: 'academic', label: 'Academic', description: 'Akademisk og formell stil' },
    { value: 'formal', label: 'Formal', description: 'Profesjonell og formell tone' },
    { value: 'shorten', label: 'Shorten', description: 'Forkorter og kondenserer tekst' },
    { value: 'expand', label: 'Expand', description: 'Utvider og utdyper tekst' },
  ];

  // Open AI tool dialog
  const openAiTool = useCallback((type: typeof aiToolType, initialText: string = '', targetField: string = ',') => {
    setAiToolType(type);
    setAiInputText(initialText);
    setAiOutputText('');
    setAiTargetField(targetField);
    setAiToolDialog(true);

    // Track feature usage
    features.trackFeatureUsage('ai-resume-writing', `${type}_opened`);
    analytics.trackEvent('ai_tool_opened', {
      userId: user?.id,
      toolType: type,
      hasInitialText: !!initialText,
    });
  }, [features, analytics, user]);

  // AI Paraphrase
  const handleAiParaphrase = useCallback(async () => {
    if (!aiInputText.trim()) return;

    setAiIsProcessing(true);
    try {
      const response = await apiRequest('/api/ai/paraphrase', {
        method: 'POST',
        headers: { 'x-user-id': user?.id || ',' },
        body: JSON.stringify({
          text: aiInputText,
          mode: aiParaphraseMode,
        }),
      });

      setAiOutputText(response.paraphrased || '');
      
      features.trackFeatureUsage('ai-resume-writing','paraphrase_success', { mode: aiParaphraseMode });
      analytics.trackEvent('ai_paraphrase_success', {
        userId: user?.id,
        mode: aiParaphraseMode,
        inputLength: aiInputText.length,
      });
    } catch (error) {
      console.error('AI Paraphrase error:', error);
      alert('Kunne ikke omskrive tekst. Prøv igjen.');
    } finally {
      setAiIsProcessing(false);
    }
  }, [aiInputText, aiParaphraseMode, user, features, analytics]);

  // AI Grammar Check
  const handleAiGrammar = useCallback(async () => {
    if (!aiInputText.trim()) return;

    setAiIsProcessing(true);
    try {
      const response = await apiRequest('/api/ai/grammar', {
        method: 'POST',
        headers: { 'x-user-id': user?.id || ',' },
        body: JSON.stringify({ text: aiInputText }),
      });

      setAiOutputText(response.corrected || '');
      
      features.trackFeatureUsage('ai-resume-writing','grammar_check_success');
      analytics.trackEvent('ai_grammar_success', {
        userId: user?.id,
        inputLength: aiInputText.length,
      });
    } catch (error) {
      console.error('AI Grammar error:', error);
      alert('Kunne ikke sjekke grammatikk. Prøv igjen.');
    } finally {
      setAiIsProcessing(false);
    }
  }, [aiInputText, user, features, analytics]);

  // AI Summarize
  const handleAiSummarize = useCallback(async () => {
    if (!aiInputText.trim()) return;

    setAiIsProcessing(true);
    try {
      const response = await apiRequest('/api/ai/summarize', {
        method: 'POST',
        headers: { 'x-user-id': user?.id || ',' },
        body: JSON.stringify({ text: aiInputText }),
      });

      setAiOutputText(response.summary || '');
      
      features.trackFeatureUsage('ai-resume-writing','summarize_success');
      analytics.trackEvent('ai_summarize_success', {
        userId: user?.id,
        inputLength: aiInputText.length,
      });
    } catch (error) {
      console.error('AI Summarize error:', error);
      alert('Kunne ikke oppsummere tekst. Prøv igjen.');
    } finally {
      setAiIsProcessing(false);
    }
  }, [aiInputText, user, features, analytics]);

  // AI Generate Resume Content
  const handleAiGenerateResume = useCallback(async (jobTitle: string, skills: string[], experience: string) => {
    setAiIsProcessing(true);
    try {
      const response = await apiRequest('/api/ai/generate-resume', {
        method: 'POST',
        headers: { 'x-user-id': user?.id || ',' },
        body: JSON.stringify({
          jobTitle,
          skills: skills.join(''),
          experience,
        }),
      });

      setAiOutputText(response.resume || '');
      
      features.trackFeatureUsage('ai-resume-writing','resume_generated');
      analytics.trackEvent('ai_resume_generated', {
        userId: user?.id,
        jobTitle,
        skillsCount: skills.length,
      });
    } catch (error) {
      console.error('AI Generate Resume error:', error);
      alert('Kunne ikke generere CV-innhold. Prøv igjen.');
    } finally {
      setAiIsProcessing(false);
    }
  }, [user, features, analytics]);

  // AI Generate Cover Letter
  const handleAiGenerateCoverLetter = useCallback(async (jobTitle: string, company: string, skills: string[]) => {
    setAiIsProcessing(true);
    try {
      const response = await apiRequest('/api/ai/generate-cover-letter', {
        method: 'POST',
        headers: { 'x-user-id': user?.id || ',' },
        body: JSON.stringify({
          jobTitle,
          company,
          skills: skills.join(''),
        }),
      });

      setAiOutputText(response.coverLetter || '');
      
      features.trackFeatureUsage('ai-resume-writing','cover_letter_generated');
      analytics.trackEvent('ai_cover_letter_generated', {
        userId: user?.id,
        jobTitle,
        company,
      });
    } catch (error) {
      console.error('AI Generate Cover Letter error:', error);
      alert('Kunne ikke generere søknadsbrev. Prøv igjen.');
    } finally {
      setAiIsProcessing(false);
    }
  }, [user, features, analytics]);

  // Apply AI result to target field
  const handleApplyAiResult = useCallback(() => {
    if (!aiOutputText || !selectedResume) return;

    // Apply to specific field based on aiTargetField
    // This will be implemented based on which field the AI tool was opened from
    
    analytics.trackEvent('ai_result_applied', {
      userId: user?.id,
      toolType: aiToolType,
      targetField: aiTargetField,
    });

    setAiToolDialog(false);
  }, [aiOutputText, selectedResume, aiTargetField, aiToolType, analytics, user]);

  // ============================================================================
  // LINKEDIN IMPORT FUNCTIONS
  // ============================================================================

  const handleLinkedInConnect = useCallback(async () => {
    try {
      // Check if LinkedIn is authenticated
      if (!linkedIn.state.isAuthenticated) {
        // Initiate LinkedIn OAuth
        await linkedIn.login();
      } else {
        // Already connected, open import dialog
        setLinkedInDialog(true);
      }
    } catch (error) {
      console.error('LinkedIn connection error:', error);
    }
  }, [linkedIn]);

  const handleLinkedInSync = useCallback(async () => {
    try {
      // Sync LinkedIn profile
      const profile = await linkedIn.syncProfile();
      setLinkedInData(profile);
      setLinkedInImportMode('select');
      setLinkedInDialog(true);
      
      analytics.trackEvent('linkedin_profile_synced', {
        userId: user?.id,
        hasExperience: !!profile.experience?.length,
        hasEducation: !!profile.education?.length,
      });
    } catch (error) {
      console.error('LinkedIn sync error:', error);
    }
  }, [linkedIn, analytics, user]);

  const handleLinkedInImport = useCallback(() => {
    if (!linkedInData || !selectedResume) return;

    // Import LinkedIn data utilities
    const { linkedInToResumeData, mergeLinkedInData } = require('@/utils/linkedin-data-extractor');
    
    // Convert LinkedIn data to resume format
    const linkedInResumeData = linkedInToResumeData(linkedInData);
    
    // Filter selected data
    const filteredData = {
      personalInfo: linkedInSelectedData.personalInfo ? linkedInResumeData.personalInfo : selectedResume.personalInfo,
      workExperience: linkedInSelectedData.workExperience 
        ? [...(selectedResume.workExperience || []), ...linkedInResumeData.workExperience]
        : selectedResume.workExperience,
      education: linkedInSelectedData.education
        ? [...(selectedResume.education || []), ...linkedInResumeData.education]
        : selectedResume.education,
      skills: linkedInSelectedData.skills
        ? [...(selectedResume.skills || []), ...linkedInResumeData.skills]
        : selectedResume.skills,
      certifications: linkedInSelectedData.certifications
        ? [...(selectedResume.certifications || []), ...linkedInResumeData.certifications]
        : selectedResume.certifications,
    };

    // Merge with existing resume
    const mergedResume = {
      ...selectedResume,
      ...filteredData,
    };

    setSelectedResume(mergedResume);
    setLinkedInDialog(false);
    setLinkedInData(null);
    
    analytics.trackEvent('linkedin_data_imported', {
      userId: user?.id,
      importedSections: Object.keys(linkedInSelectedData).filter(k => linkedInSelectedData[k as keyof typeof linkedInSelectedData]),
    });

    // Track feature usage
    features.trackFeatureUsage('linkedin-auto-sync','data_imported');
  }, [linkedInData, selectedResume, linkedInSelectedData, analytics, user, features]);

  const handleLinkedInPreview = useCallback(() => {
    setLinkedInImportMode('preview');
  }, []);

  const handleLinkedInBackToSelect = useCallback(() => {
    setLinkedInImportMode('select');
  }, []);

  // Fetch resumes
  const { data: resumes = [], isLoading: resumesLoading } = useQuery({
    queryKey: ['resumes', user?.id],
    queryFn: async () => {
      const response = await apiRequest('/api/resumes', {
        headers: { 'x-user-id': user?.id || ',' },
      });
      return response as Resume[];
    },
    enabled: !!user?.id,
  });

  // Fetch templates
  const { data: templates = [], isLoading: templatesLoading } = useQuery({
    queryKey: ['resume-templates'],
    queryFn: async () => {
      const response = await apiRequest('/api/resume-templates');
      return response as ResumeTemplate[];
    },
  });

  // Create resume mutation
  const createResumeMutation = useMutation({
    mutationFn: async (data: Partial<Resume>) => {
      const response = await apiRequest('/api/resumes', {
        method: 'POST',
        headers: { 
          'x-user-id': user?.id || ',','Content-Type' : 'application/json',
        },
        body: JSON.stringify(data),
      });
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['resumes'] });
    },
  });

  // Update resume mutation
  const updateResumeMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<Resume> }) => {
      const response = await apiRequest(`/api/resumes/${id}`, {
        method: 'PUT',
        headers: {
          'x-user-id': user?.id || ',','Content-Type' : 'application/json',
        },
        body: JSON.stringify(data),
      });
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['resumes'] });
    },
  });

  // Delete resume mutation
  const deleteResumeMutation = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest(`/api/resumes/${id}`, {
        method: 'DELETE',
        headers: { 'x-user-id': user?.id || ',' },
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['resumes'] });
      setSelectedResume(null);
    },
  });

  // Import projects mutation
  const importProjectsMutation = useMutation({
    mutationFn: async (resumeId: string) => {
      const response = await apiRequest(`/api/resumes/${resumeId}/import-completed-projects`, {
        method: 'POST',
        headers: { 
          'x-user-id': user?.id || ',','Content-Type' : 'application/json',
        },
      });
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['resumes'] });
      setShowProjectImportDialog(false);
    },
  });

  // AI analysis mutation
  const aiAnalyzeMutation = useMutation({
    mutationFn: async ({ resumeId, jobDescription }: { resumeId: string; jobDescription?: string }) => {
      const response = await apiRequest(`/api/resumes/${resumeId}/ai-analyze`, {
        method: 'POST',
        headers: {
          'x-user-id': user?.id || ',','Content-Type' : 'application/json',
        },
        body: JSON.stringify({ jobDescription }),
      });
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['resumes'] });
      setShowAIDialog(false);
    },
  });

  // Export resume mutation
  const exportResumeMutation = useMutation({
    mutationFn: async ({ resumeId, format }: { resumeId: string; format: 'pdf' | 'docx' | 'txt' | 'json' }) => {
      const response = await fetch(`/api/resumes/${resumeId}/export`, {
        method: 'POST',
        headers: {
          'x-user-id': user?.id || ',','Content-Type' : 'application/json',
        },
        body: JSON.stringify({ format }),
      });

      if (!response.ok) {
        throw new Error('Export failed');
      }

      if (format === 'pdf') {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `resume-${resumeId}.pdf`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      } else {
        return await response.json();
      }
    },
  });

  // ============================================================================
  // HANDLERS
  // ============================================================================

  const handleCreateResume = useCallback(() => {
    createResumeMutation.mutate({
      title: 'Ny CV',
      personalInfo: {
        fullName: user?.email || 'Ditt navn',
        email: user?.email || '',
      },
      templateId: 'modern-ats',
      status: 'draft',
      language: 'no',
    });
  }, [user, createResumeMutation]);

  const handleSelectResume = useCallback((resume: Resume) => {
    setSelectedResume(resume);
    setActiveStep(1);
  }, []);

  const handleUpdateResume = useCallback((data: Partial<Resume>) => {
    if (selectedResume) {
      updateResumeMutation.mutate({
        id: selectedResume.id,
        data,
      });
    }
  }, [selectedResume, updateResumeMutation]);

  const handleDeleteResume = useCallback((id: string) => {
    if (window.confirm('Er du sikker på at du vil slette denne CV-en?')) {
      deleteResumeMutation.mutate(id);
    }
  }, [deleteResumeMutation]);

  const handleImportProjects = useCallback(() => {
    if (selectedResume) {
      importProjectsMutation.mutate(selectedResume.id);
    }
  }, [selectedResume, importProjectsMutation]);

  const handleAIAnalyze = useCallback(() => {
    if (selectedResume) {
      aiAnalyzeMutation.mutate({
        resumeId: selectedResume.id,
        jobDescription: aiJobDescription || undefined,
      });
    }
  }, [selectedResume, aiJobDescription, aiAnalyzeMutation]);

  const handleExport = useCallback((format: 'pdf' | 'docx' | 'txt' | 'json') => {
    if (selectedResume) {
      exportResumeMutation.mutate({
        resumeId: selectedResume.id,
        format,
      });
    }
  }, [selectedResume, exportResumeMutation]);

  // ============================================================================
  // RENDER
  // ============================================================================

  if (!user) {
    return (
      <Container maxWidth="md" sx={{ mt: 4 }}>
        <Alert severity="warning">
          Vennligst logg inn for å bruke CV-bygger
        </Alert>
      </Container>
    );
  }

  return (
    <Container maxWidth="xl" sx={{ mt: 4, mb: 4 }}>
      {/* Header with Brand Kit */}
      <Box sx={{ mb: 4 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            {/* CreatorHub ResumeBuilder Logo */}
            <Box
              sx={{
                width: 56,
                height: 56,
                borderRadius: 2,
                background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)'}}
            >
              <Typography
                sx={{
                  fontFamily: 'Poppins, sans-serif',
                  fontSize: '24px',
                  fontWeight: 70,
                  color: '#fff',
                  lineHeight: 1}}
              >
                RB
              </Typography>
            </Box>
            
            <Box>
              <Typography 
                variant="h3" 
                gutterBottom 
                sx={{ 
                  fontWeight: 70,
                  fontFamily: 'Poppins, sans-serif',
                  background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  backgroundClip: 'text'}}
              >
                CreatorHub ResumeBuilder
              </Typography>
              <Typography variant="body1" color="text.secondary">
                Lag profesjonelle CV-er med AI-assistanse, ATS-optimalisering og automatisk prosjekt-import
              </Typography>
            </Box>
          </Box>

          {/* Auto-save status and actions */}
          {selectedResume && (
            <Stack direction="row" spacing={2} alignItems="center">
              {/* Auto-save status indicator */}
              <Chip
                icon={
                  autoSaveStatus === 'saving' ? <SaveIcon /> :
                  autoSaveStatus === 'saved' ? <CheckIcon /> :
                  autoSaveStatus === 'error' ? <ErrorIcon /> :
                  <SaveIcon />
                }
                label={
                  autoSaveStatus === 'saving' ? 'Lagrer...' :
                  autoSaveStatus === 'saved' ? 'Lagret' :
                  autoSaveStatus === 'error' ? 'Lagringsfeil' :
                  'Venter...'
                }
                color={
                  autoSaveStatus === 'saved' ? 'success' :
                  autoSaveStatus === 'error' ? 'error' :
                  'default'
                }
                size="small"
                variant={autoSaveStatus === 'saved' ? 'outlined' : 'filled'}
              />

              {/* Draft indicator */}
              {isDraft && (
                <Chip
                  label={`Utkast - Versjon ${currentVersion}`}
                  color="warning"
                  size="small"
                  variant="outlined"
                />
              )}

              {/* Version history button */}
              <Tooltip title="Se versjonshistorikk">
                <IconButton onClick={() => setShowVersionDialog(true)} size="small">
                  <Badge badgeContent={versionHistory.length} color="primary">
                    <HistoryIcon />
                  </Badge>
                </IconButton>
              </Tooltip>

              {/* Restore backup button */}
              <Tooltip title="Gjenopprett fra backup">
                <IconButton onClick={handleRestoreFromBackup} size="small">
                  <RestoreIcon />
                </IconButton>
              </Tooltip>

              {/* Save as draft button */}
              <Button
                startIcon={<SaveIcon />}
                onClick={handleSaveAsDraft}
                variant="outlined"
                size="small"
                disabled={autoSaveStatus === 'saving'}
              >
                Lagre utkast
              </Button>

              {/* Publish button */}
              {isDraft && (
                <Button
                  startIcon={<PublishIcon />}
                  onClick={handlePublishResume}
                  variant="contained"
                  color="primary"
                  size="small"
                  disabled={autoSaveStatus === 'saving'}
                >
                  Publiser
                </Button>
              )}
            </Stack>
          )}
        </Box>
      </Box>

      {/* Marketplace Card Preview (Optional - can be removed in production) */}
      {!selectedResume && resumes.length === 0 && (
        <Box sx={{ mb: 4 }}>
          <Typography
            variant="h6"
            gutterBottom
            sx={{
              fontFamily: 'Poppins, sans-serif',
              fontWeight: 600,
              mb: 2}}
          >
            🎯 CreatorHub Marketplace
          </Typography>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <CreatorHubMarketplace 
                onSelect={handleCreateResume}
                showPricing={true}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <Box
                sx={{
                  p: 3,
                  borderRadius: 2,
                  border: '2px dashed #2563eb',
                  background: 'linear-gradient(135deg, rgba(255, 140, 0, 0.05) 0%, rgba(37, 99, 235, 0.05) 100%)'}}
              >
                <Typography
                  variant="h6"
                  gutterBottom
                  sx={{
                    fontFamily: 'Poppins, sans-serif',
                    fontWeight: 600,
                    color: '#2563eb'}}
                >
                  Marketplace Feature
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                  Dette kortet viser hvordan CreatorHub apps vil vises i marketplace for andre brukere.
                  Den inneholder:
                </Typography>
                <List dense>
                  <ListItem sx={{ px: 0 }}>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckIcon sx={{ color: '#2563eb', fontSize: 20 }} />
                    </ListItemIcon>
                    <ListItemText primary="CreatorHub ResumeBuilder branding" />
                  </ListItem>
                  <ListItem sx={{ px: 0 }}>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckIcon sx={{ color: '#2563eb', fontSize: 20 }} />
                    </ListItemIcon>
                    <ListItemText primary="App-ikon med gradient" />
                  </ListItem>
                  <ListItem sx={{ px: 0 }}>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckIcon sx={{ color: '#2563eb', fontSize: 20 }} />
                    </ListItemIcon>
                    <ListItemText primary="Funksjonsliste og fordeler" />
                  </ListItem>
                  <ListItem sx={{ px: 0 }}>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckIcon sx={{ color: '#2563eb', fontSize: 20 }} />
                    </ListItemIcon>
                    <ListItemText primary="Prisinformasjon" />
                  </ListItem>
                  <ListItem sx={{ px: 0 }}>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckIcon sx={{ color: '#2563eb', fontSize: 20 }} />
                    </ListItemIcon>
                    <ListItemText primary="CTA-knapp" />
                  </ListItem>
                </List>
              </Box>
            </Grid>
          </Grid>
        </Box>
      )}

      {/* Stepper */}
      <Stepper activeStep={activeStep} orientation="vertical" sx={{ mb: 4 }}>
        <Step>
          <StepLabel>Velg eller lag CV</StepLabel>
          <StepContent>
            <Grid container spacing={3}>
              {/* Create New Button */}
              <Grid item xs={12} md={4}>
                <Card 
                  sx={{ 
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    cursor: 'pointer',
                    border: '2px dashed',
                    borderColor: '#2563eb',
                    bgcolor: 'rgba(37, 99, 235, 0.03)', '&:hover': {
                      bgcolor: 'rgba(37, 99, 235, 0.08)',
                      borderColor: '#ff8c00',
                      transform: 'translateY(-2px)',
                      transition: 'all 0.2s',
                    }}}
                  onClick={handleCreateResume}
                >
                  <CardContent sx={{ textAlign: 'center', py: 6 }}>
                    <AddIcon sx={{ fontSize: 64, color: '#2563eb', mb: 2 }} />
                    <Typography 
                      variant="h6"
                      sx={{
                        fontFamily: 'Poppins, sans-serif',
                        fontWeight: 600,
                        color: '#2563eb'}}
                    >
                      Lag ny CV
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Start fra scratch med AI-assistanse
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>

              {/* LinkedIn Import Button */}
              <Grid item xs={12} md={4}>
                <Card 
                  sx={{ 
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    cursor: 'pointer',
                    border: '2px solid',
                    borderColor: linkedIn.state.isAuthenticated ? '#2563eb' : '#ff8c00',
                    bgcolor: linkedIn.state.isAuthenticated ? 'rgba(37, 99, 235, 0.05)' : 'rgba(255, 140, 0, 0.05)','&:hover': {
                      bgcolor: linkedIn.state.isAuthenticated ? 'rgba(37, 99, 235, 0.1)' : 'rgba(255, 140, 0, 0.1)',
                      transform: 'translateY(-4px)',
                      transition: 'all 0.2s',
                      boxShadow: linkedIn.state.isAuthenticated 
                        ? '0 8px 24px rgba(37, 99, 235, 0.2)' 
                        : '0 8px 24px rgba(255, 140, 0, 0.2)',
                    }}}
                  onClick={handleLinkedInConnect}
                >
                  <CardContent sx={{ textAlign: 'center', py: 6 }}>
                    <LinkedInIcon 
                      sx={{ 
                        fontSize: 64, 
                        color: linkedIn.state.isAuthenticated ? '#2563eb' : '#ff8c00', 
                        mb: 2 
                      }} 
                    />
                    <Typography 
                      variant="h6"
                      sx={{
                        fontFamily: 'Poppins, sans-serif',
                        fontWeight: 600,
                        color: linkedIn.state.isAuthenticated ? '#2563eb' : '#ff8c00'}}
                    >
                      {linkedIn.state.isAuthenticated ? 'Importer fra LinkedIn' : 'Koble til LinkedIn'}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      {linkedIn.state.isAuthenticated 
                        ? 'Synkroniser profil og importer data' 
                        : 'Logg inn og importer CV-data automatisk'}
                    </Typography>
                    {linkedIn.state.isAuthenticated && (
                      <Chip 
                        label="Tilkoblet" 
                        sx={{ 
                          mt: 1,
                          background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                          color: '#fff',
                          fontWeight: 600}}
                        size="small" 
                        icon={<CheckIcon sx={{ color: '#fff !important' }} />}
                      />
                    )}
                  </CardContent>
                </Card>
              </Grid>

              {/* Existing Resumes */}
              {resumes.map((resume) => (
                <Grid item xs={12} md={4} key={resume.id}>
                  <Card 
                    sx={{ 
                      height: '100%',
                      cursor: 'pointer','&:hover': {
                        boxShadow: 6,
                      }}}
                    onClick={() => handleSelectResume(resume)}
                  >
                    <CardContent>
                      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                        <Typography variant="h6" noWrap>
                          {resume.title}
                        </Typography>
                        <Chip 
                          label={resume.status}
                          size="small"
                          color={resume.status === 'active' ? 'success' : 'default'}
                        />
                      </Box>

                      <Typography variant="body2" color="text.secondary" gutterBottom>
                        {resume.personalInfo.professionalTitle || 'Ingen tittel'}
                      </Typography>

                      {/* ATS Score */}
                      <Box sx={{ mt: 2 }}>
                        <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                          <Typography variant="caption">ATS-Score</Typography>
                          <Typography variant="caption" fontWeight={600}>
                            {resume.atsScore}%
                          </Typography>
                        </Box>
                        <LinearProgress 
                          variant="determinate" 
                          value={resume.atsScore} 
                          color={resume.atsScore >= 80 ? 'success' : resume.atsScore >= 60 ? 'warning' : 'error'}
                        />
                      </Box>

                      {/* Stats */}
                      <Stack direction="row" spacing={2} sx={{ mt: 2 }}>
                        <Tooltip title="Arbeidserfaring">
                          <Chip 
                            icon={<WorkIcon />} 
                            label={resume.experiences?.length || 0} 
                            size="small" 
                          />
                        </Tooltip>
                        <Tooltip title="Utdanning">
                          <Chip 
                            icon={<EducationIcon />} 
                            label={resume.education?.length || 0} 
                            size="small" 
                          />
                        </Tooltip>
                        <Tooltip title="Ferdigheter">
                          <Chip 
                            icon={<SkillIcon />} 
                            label={resume.skills?.length || 0} 
                            size="small" 
                          />
                        </Tooltip>
                      </Stack>
                    </CardContent>

                    <CardActions>
                      <Button size="small" startIcon={<EditIcon />}>
                        Rediger
                      </Button>
                      <IconButton 
                        size="small" 
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDeleteResume(resume.id);
                        }}
                      >
                        <DeleteIcon />
                      </IconButton>
                    </CardActions>
                  </Card>
                </Grid>
              ))}
            </Grid>
          </StepContent>
        </Step>

        <Step>
          <StepLabel>Bygg og optimaliser</StepLabel>
          <StepContent>
            {selectedResume && (
              <Box>
                {/* Action Buttons */}
                <Stack direction="row" spacing={2} sx={{ mb: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<UploadIcon />}
                    onClick={() => setShowProjectImportDialog(true)}
                  >
                    Importer prosjekter
                  </Button>
                  <Button
                    variant="contained"
                    startIcon={<AIIcon />}
                    onClick={() => setShowAIDialog(true)}
                    color="secondary"
                  >
                    AI-analyse
                  </Button>
                  <Button
                    variant="outlined"
                    startIcon={<TemplateIcon />}
                    onClick={() => setShowTemplateDialog(true)}
                  >
                    Bytt mal
                  </Button>
                  <Button
                    variant="outlined"
                    startIcon={<DownloadIcon />}
                    onClick={() => setShowExportDialog(true)}
                  >
                    Eksporter
                  </Button>
                </Stack>

                {/* Resume Editor Tabs */}
                <Paper sx={{ mb: 3 }}>
                  <Tabs value={tabValue} onChange={(e, v) => setTabValue(v)}>
                    <Tab label="Personlig info" />
                    <Tab label="Arbeidserfaring" />
                    <Tab label="Utdanning" />
                    <Tab label="Ferdigheter" />
                    <Tab label="Sertifiseringer" />
                    <Tab label="Prosjekter" />
                  </Tabs>

                  <Box sx={{ p: 3 }}>
                    {/* Personal Info Tab */}
                    {tabValue === 0 && (
                      <Grid container spacing={3}>
                        <Grid item xs={12} md={6}>
                          <TextField
                            fullWidth
                            label="Fullt navn"
                            value={selectedResume.personalInfo.fullName}
                            onChange={(e) => handleUpdateResume({
                              personalInfo: {
                                ...selectedResume.personalInfo,
                                fullName: e.target.value,
                              },
                            })}
                          />
                        </Grid>
                        <Grid item xs={12} md={6}>
                          <TextField
                            fullWidth
                            label="Profesjonell tittel"
                            value={selectedResume.personalInfo.professionalTitle || ''}
                            onChange={(e) => handleUpdateResume({
                              personalInfo: {
                                ...selectedResume.personalInfo,
                                professionalTitle: e.target.value,
                              },
                            })}
                          />
                        </Grid>
                        <Grid item xs={12} md={6}>
                          <TextField
                            fullWidth
                            label="E-post"
                            type="email"
                            value={selectedResume.personalInfo.email}
                            onChange={(e) => handleUpdateResume({
                              personalInfo: {
                                ...selectedResume.personalInfo,
                                email: e.target.value,
                              },
                            })}
                          />
                        </Grid>
                        <Grid item xs={12} md={6}>
                          <TextField
                            fullWidth
                            label="Telefon"
                            value={selectedResume.personalInfo.phone || ', '}
                            onChange={(e) => handleUpdateResume({
                              personalInfo: {
                                ...selectedResume.personalInfo,
                                phone: e.target.value,
                              },
                            })}
                          />
                        </Grid>
                        <Grid item xs={12}>
                          <Stack spacing={1}>
                            <Stack direction="row" spacing={1} justifyContent="space-between" alignItems="center">
                              <Typography variant="subtitle2">Profesjonelt sammendrag</Typography>
                              <Stack direction="row" spacing={1}>
                                <Tooltip title="AI Omskriving">
                                  <IconButton
                                    size="small"
                                    onClick={() => openAiTool('paraphrase', selectedResume.personalInfo.summary || ', ','summary')}
                                    color="primary"
                                  >
                                    <AutoAwesome fontSize="small" />
                                  </IconButton>
                                </Tooltip>
                                <Tooltip title="AI Grammatikksjekk">
                                  <IconButton
                                    size="small"
                                    onClick={() => openAiTool('grammar', selectedResume.personalInfo.summary || ', ','summary')}
                                    color="primary"
                                  >
                                    <Spellcheck fontSize="small" />
                                  </IconButton>
                                </Tooltip>
                                <Tooltip title="AI Generer">
                                  <IconButton
                                    size="small"
                                    onClick={() => openAiTool('generate-resume',', ','summary')}
                                    color="secondary"
                                  >
                                    <AIIcon fontSize="small" />
                                  </IconButton>
                                </Tooltip>
                              </Stack>
                            </Stack>
                            <TextField
                              fullWidth
                              multiline
                              rows={4}
                              value={selectedResume.personalInfo.summary || ', '}
                              onChange={(e) => handleUpdateResume({
                                personalInfo: {
                                  ...selectedResume.personalInfo,
                                  summary: e.target.value,
                                },
                              })}
                              placeholder="Skriv et kort sammendrag av din erfaring og kompetanse..."
                            />
                          </Stack>
                        </Grid>
                      </Grid>
                    )}

                    {/* Work Experience Tab */}
                    {tabValue === 1 && (
                      <Box>
                        <Typography variant="h6" gutterBottom>
                          Arbeidserfaring
                        </Typography>
                        {selectedResume.experiences?.length === 0 && (
                          <Alert severity="info" sx={{ mb: 2 }}>
                            Ingen arbeidserfaring lagt til. Importer fullførte prosjekter eller legg til manuelt.
                          </Alert>
                        )}
                        {selectedResume.experiences?.map((exp) => (
                          <Card key={exp.id} sx={{ mb: 2 }}>
                            <CardContent>
                              <Typography variant="h6">{exp.jobTitle}</Typography>
                              <Typography variant="body2" color="text.secondary">
                                {exp.company} | {exp.location}
                              </Typography>
                              <Typography variant="caption" color="text.secondary">
                                {new Date(exp.startDate).toLocaleDateString('no-NO')} - {exp.isCurrent ? 'Nå' : new Date(exp.endDate!).toLocaleDateString('no-NO')}
                              </Typography>
                              {exp.autoGenerated && (
                                <Chip label="Auto-importert" size="small" color="info" sx={{ ml: 1 }} />
                              )}
                            </CardContent>
                          </Card>
                        ))}
                      </Box>
                    )}

                    {/* Skills Tab */}
                    {tabValue === 3 && (
                      <Box>
                        <Typography variant="h6" gutterBottom>
                          Ferdigheter
                        </Typography>
                        <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
                          {selectedResume.skills?.map((skill) => (
                            <Chip 
                              key={skill.id} 
                              label={skill.name}
                              onDelete={() => {/* TODO: Delete skill */}}
                            />
                          ))}
                        </Stack>
                        <Button 
                          startIcon={<AddIcon />} 
                          sx={{ mt: 2 }}
                          onClick={() => {/* TODO: Add skill dialog */}}
                        >
                          Legg til ferdighet
                        </Button>
                      </Box>
                    )}

                    {/* Projects & Portfolio Tab */}
                    {tabValue === 5 && (
                      <Box>
                        <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}>
                          <Typography variant="h6">
                            Prosjekter & Portefølje
                          </Typography>
                          <Button
                            variant="contained"
                            startIcon={<AddIcon />}
                            onClick={handleAddPortfolioItem}
                            sx={{ bgcolor: 'primary.main', color: 'white' }}
                          >
                            Legg til portefølje-oppføring
                          </Button>
                        </Stack>

                        {/* Auto-imported Projects */}
                        {selectedResume.projects && selectedResume.projects.length > 0 && (
                          <Box sx={{ mb: 4 }}>
                            <Typography variant="h6" gutterBottom>
                              Auto-importerte prosjekter
                            </Typography>
                            {selectedResume.projects.map((project) => (
                              <Card key={project.id} sx={{ mb: 2 }}>
                                <CardContent>
                                  <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
                                    <Box sx={{ flex: 1 }}>
                                      <Typography variant="h6">{project.title}</Typography>
                                      <Typography variant="body2" color="text.secondary">
                                        {project.role}
                                      </Typography>
                                      <Typography variant="body2" sx={{ mt: 1 }}>
                                        {project.description}
                                      </Typography>
                                    </Box>
                                    <Chip label="Auto-importert" size="small" color="info" />
                                  </Stack>
                                </CardContent>
                              </Card>
                            ))}
                          </Box>
                        )}

                        {/* Manual Portfolio Items */}
                        <Box>
                          <Typography variant="h6" gutterBottom>
                            Portefølje-oppføringer
                          </Typography>
                          {portfolioItems.length === 0 ? (
                            <Alert severity="info" sx={{ mb: 2 }}>
                              Ingen portefølje-oppføringer lagt til ennå. Klikk på "Legg til portefølje-oppføring" for å komme i gang.
                            </Alert>
                          ) : (
                            <Grid container spacing={2}>
                              {portfolioItems.map((item) => (
                                <Grid item xs={12} sm={6} md={4} key={item.id}>
                                  <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                                    <CardContent sx={{ flex: 1 }}>
                                      <Stack direction="row" justifyContent="space-between" alignItems="flex-start" mb={2}>
                                        <Typography variant="h6" sx={{ fontSize: '16px', fontWeight: 600}}>
                                          {item.title}
                                        </Typography>
                                        <Chip 
                                          label={item.category} 
                                          size="small" 
                                          color="primary" 
                                          variant="outlined"
                                        />
                                      </Stack>
                                      
                                      <Typography variant="body2" color="textSecondary" sx={{ mb: 2, fontSize: '13px' }}>
                                        {item.description}
                                      </Typography>

                                      {/* Google Drive Links */}
                                      {item.googleDriveLinks && item.googleDriveLinks.length > 0 && (
                                        <Box sx={{ mb: 2 }}>
                                          <Typography variant="caption" color="textSecondary" sx={{ mb: 1, display: 'block' }}>
                                            Google Drive-filer:
                                          </Typography>
                                          <Stack spacing={1}>
                                            {item.googleDriveLinks.map((link, index) => (
                                              <Button
                                                key={index}
                                                size="small"
                                                variant="outlined"
                                                startIcon={getFileIcon(link.type)}
                                                href={link.url}
                                                target="_blank"
                                                sx={{ 
                                                  fontSize: '12px',
                                                  textTransform: 'none',
                                                  justifyContent: 'flex-start',
                                                  textAlign: 'left'
                                                }}
                                              >
                                                {link.name}
                                              </Button>
                                            ))}
                                          </Stack>
                                        </Box>
                                      )}

                                      {/* Technologies */}
                                      {item.technologies && item.technologies.length > 0 && (
                                        <Box>
                                          <Typography variant="caption" color="textSecondary" sx={{ mb: 1, display: 'block' }}>
                                            Teknologier:
                                          </Typography>
                                          <Stack direction="row" spacing={0.5} flexWrap="wrap">
                                            {item.technologies.map((tech, index) => (
                                              <Chip 
                                                key={index} 
                                                label={tech} 
                                                size="small" 
                                                sx={{ fontSize: '11px', mb: 0.5 }} 
                                              />
                                            ))}
                                          </Stack>
                                        </Box>
                                      )}
                                    </CardContent>
                                    
                                    <CardActions>
                                      <Button size="small" onClick={() => handleEditPortfolioItem(item)}>
                                        Rediger
                                      </Button>
                                      <Button 
                                        size="small" 
                                        color="error" 
                                        onClick={() => handleDeletePortfolioItem(item.id!)}
                                      >
                                        Slett
                                      </Button>
                                    </CardActions>
                                  </Card>
                                </Grid>
                              ))}
                            </Grid>
                          )}
                        </Box>
                      </Box>
                    )}
                  </Box>
                </Paper>

                {/* ATS Score Card */}
                <Card>
                  <CardContent>
                    <Typography variant="h6" gutterBottom>
                      ATS-Optimalisering
                    </Typography>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                      <Box sx={{ flex: 1 }}>
                        <LinearProgress 
                          variant="determinate" 
                          value={selectedResume.atsScore} 
                          sx={{ height: 10, borderRadius: 5 }}
                          color={selectedResume.atsScore >= 80 ? 'success' : selectedResume.atsScore >= 60 ? 'warning' : 'error'}
                        />
                      </Box>
                      <Typography variant="h4" color="primary">
                        {selectedResume.atsScore}%
                      </Typography>
                    </Box>
                    <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                      {selectedResume.atsScore >= 80 ? '✅ Utmerket ATS-score!' : selectedResume.atsScore >= 60 ? '⚠️ God score, men kan forbedres' : '❌ Trenger forbedring'}
                    </Typography>
                  </CardContent>
                </Card>
              </Box>
            )}
          </StepContent>
        </Step>

        <Step>
          <StepLabel>Publiser og søk jobber</StepLabel>
          <StepContent>
            <Typography>Publiser CV-en din og start jobbsøking</Typography>
            {/* TODO: Job application tracking */}
          </StepContent>
        </Step>
      </Stepper>

      {/* Project Import Dialog */}
      <Dialog 
        open={showProjectImportDialog} 
        onClose={() => setShowProjectImportDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>Importer fullførte prosjekter</DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mb: 2 }}>
            Alle fullførte prosjekter vil bli importert som arbeidserfaring og porteføljeprosjekter.
          </Alert>
          <Typography variant="body2">
            Dette vil automatisk legge til dine fullførte prosjekter som arbeidserfaring i CV-en din.
            Du kan redigere og tilpasse informasjonen etterpå.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowProjectImportDialog(false)}>Avbryt</Button>
          <Button 
            variant="contained" 
            onClick={handleImportProjects}
            disabled={importProjectsMutation.isPending}
            startIcon={importProjectsMutation.isPending ? <CircularProgress size={20} /> : <UploadIcon />}
          >
            Importer prosjekter
          </Button>
        </DialogActions>
      </Dialog>

      {/* AI Analysis Dialog */}
      <Dialog 
        open={showAIDialog} 
        onClose={() => setShowAIDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>AI-analyse av CV</DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mb: 2 }}>
            AI vil analysere CV-en din og gi forslag til forbedringer basert på ATS-optimalisering og beste praksis.
          </Alert>
          <TextField
            fullWidth
            multiline
            rows={6}
            label="Stillingsannonse (valgfritt)"
            placeholder="Lim inn stillingsannonsen du søker på for å få skreddersydde forslag..."
            value={aiJobDescription}
            onChange={(e) => setAiJobDescription(e.target.value)}
            sx={{ mt: 2 }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowAIDialog(false)}>Avbryt</Button>
          <Button 
            variant="contained" 
            onClick={handleAIAnalyze}
            disabled={aiAnalyzeMutation.isPending}
            startIcon={aiAnalyzeMutation.isPending ? <CircularProgress size={20} /> : <AIIcon />}
          >
            Analyser med AI
          </Button>
        </DialogActions>
      </Dialog>

      {/* LinkedIn Import Dialog */}
      <Dialog 
        open={linkedInDialog} 
        onClose={() => {
          setLinkedInDialog(false);
          setLinkedInImportMode('select');
          setLinkedInData(null);
        }}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <LinkedInIcon sx={{ color: '#2563eb' }} />
            <Typography 
              sx={{ 
                fontFamily: 'Poppins, sans-serif',
                fontWeight: 600,
                background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text'}}
            >
              {linkedInImportMode === 'select' ? 'Importer fra LinkedIn' : 'Forhåndsvis import'}
            </Typography>
          </Box>
        </DialogTitle>
        <DialogContent>
          {linkedInImportMode === 'select' ? (
            <>
              <Alert severity="info" sx={{ mb: 2 }}>
                Velg hvilke deler av LinkedIn-profilen din du vil importere til CV-en.
              </Alert>
              
              {linkedIn.state.isAuthenticated && linkedIn.state.profile && (
                <Box sx={{ mb: 3, p: 2, bgcolor: 'background.paper', borderRadius: 1, border: '1px solid', borderColor: 'divider' }}>
                  <Typography variant="subtitle2" gutterBottom>LinkedIn-profil</Typography>
                  <Typography variant="body2" color="text.secondary">
                    {linkedIn.state.profile.firstName} {linkedIn.state.profile.lastName}
                  </Typography>
                  {linkedIn.state.profile.headline && (
                    <Typography variant="body2" color="text.secondary">
                      {linkedIn.state.profile.headline}
                    </Typography>
                  )}
                </Box>
              )}

              <FormControlLabel
                control={
                  <Switch
                    checked={linkedInSelectedData.personalInfo}
                    onChange={(e) => setLinkedInSelectedData(prev => ({ ...prev, personalInfo: e.target.checked }))}
                  />
                }
                label={
                  <Box>
                    <Typography variant="body1">Personlig informasjon</Typography>
                    <Typography variant="caption" color="text.secondary">
                      Navn, e-post, lokasjon, profilbilde
                    </Typography>
                  </Box>
                }
              />
              <Divider sx={{ my: 1 }} />

              <FormControlLabel
                control={
                  <Switch
                    checked={linkedInSelectedData.workExperience}
                    onChange={(e) => setLinkedInSelectedData(prev => ({ ...prev, workExperience: e.target.checked }))}
                  />
                }
                label={
                  <Box>
                    <Typography variant="body1">Arbeidserfaring</Typography>
                    <Typography variant="caption" color="text.secondary">
                      {linkedInData?.experience?.length || 0} stillinger
                    </Typography>
                  </Box>
                }
              />
              <Divider sx={{ my: 1 }} />

              <FormControlLabel
                control={
                  <Switch
                    checked={linkedInSelectedData.education}
                    onChange={(e) => setLinkedInSelectedData(prev => ({ ...prev, education: e.target.checked }))}
                  />
                }
                label={
                  <Box>
                    <Typography variant="body1">Utdanning</Typography>
                    <Typography variant="caption" color="text.secondary">
                      {linkedInData?.education?.length || 0} utdanninger
                    </Typography>
                  </Box>
                }
              />
              <Divider sx={{ my: 1 }} />

              <FormControlLabel
                control={
                  <Switch
                    checked={linkedInSelectedData.skills}
                    onChange={(e) => setLinkedInSelectedData(prev => ({ ...prev, skills: e.target.checked }))}
                  />
                }
                label={
                  <Box>
                    <Typography variant="body1">Ferdigheter</Typography>
                    <Typography variant="caption" color="text.secondary">
                      {linkedInData?.skills?.length || 0} ferdigheter
                    </Typography>
                  </Box>
                }
              />
              <Divider sx={{ my: 1 }} />

              <FormControlLabel
                control={
                  <Switch
                    checked={linkedInSelectedData.certifications}
                    onChange={(e) => setLinkedInSelectedData(prev => ({ ...prev, certifications: e.target.checked }))}
                  />
                }
                label={
                  <Box>
                    <Typography variant="body1">Sertifiseringer</Typography>
                    <Typography variant="caption" color="text.secondary">
                      {linkedInData?.certifications?.length || 0} sertifiseringer
                    </Typography>
                  </Box>
                }
              />
            </>
          ) : (
            <Box>
              <Alert severity="success" sx={{ mb: 2 }}>
                Data importert! Her er en oversikt over hva som ble lagt til:
              </Alert>
              
              {linkedInSelectedData.personalInfo && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="subtitle2" gutterBottom>Personlig informasjon</Typography>
                  <Typography variant="body2" color="text.secondary">
                    ✓ Importert
                  </Typography>
                </Box>
              )}

              {linkedInSelectedData.workExperience && linkedInData?.experience && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="subtitle2" gutterBottom>Arbeidserfaring</Typography>
                  {linkedInData.experience.slice(0, 3).map((exp: any, idx: number) => (
                    <Typography key={idx} variant="body2" color="text.secondary">
                      ✓ {exp.title} at {exp.company}
                    </Typography>
                  ))}
                  {linkedInData.experience.length > 3 && (
                    <Typography variant="caption" color="text.secondary">
                      + {linkedInData.experience.length - 3} flere stillinger
                    </Typography>
                  )}
                </Box>
              )}

              {linkedInSelectedData.education && linkedInData?.education && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="subtitle2" gutterBottom>Utdanning</Typography>
                  {linkedInData.education.map((edu: any, idx: number) => (
                    <Typography key={idx} variant="body2" color="text.secondary">
                      ✓ {edu.school} - {edu.degree || edu.fieldOfStudy}
                    </Typography>
                  ))}
                </Box>
              )}

              {linkedInSelectedData.skills && linkedInData?.skills && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="subtitle2" gutterBottom>Ferdigheter</Typography>
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                    {linkedInData.skills.slice(0, 10).map((skill: string, idx: number) => (
                      <Chip key={idx} label={skill} size="small" />
                    ))}
                    {linkedInData.skills.length > 10 && (
                      <Typography variant="caption" color="text.secondary" sx={{ alignSelf: 'center', ml: 1 }}>
                        + {linkedInData.skills.length - 10} flere
                      </Typography>
                    )}
                  </Box>
                </Box>
              )}
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          {linkedInImportMode === 'select' ? (
            <>
              <Button onClick={() => {
                setLinkedInDialog(false);
                setLinkedInData(null);
              }}>
                Avbryt
              </Button>
              <Button 
                variant="contained" 
                onClick={handleLinkedInImport}
                startIcon={<LinkedInIcon />}
                disabled={!Object.values(linkedInSelectedData).some(v => v)}
                sx={{
                  background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                  color: '#fff',
                  fontFamily: 'Poppins, sans-serif',
                  fontWeight: 600, '&:hover': {
                    background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                    opacity: 0.9,
                    transform: 'translateY(-1px)',
                    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
                  }, '&:disabled': {
                    background: '#ccc',
                    color: '#666',
                  }}}
              >
                Importer valgte deler
              </Button>
            </>
          ) : (
            <>
              <Button onClick={handleLinkedInBackToSelect}>
                Tilbake
              </Button>
              <Button 
                variant="contained" 
                onClick={() => {
                  setLinkedInDialog(false);
                  setLinkedInImportMode('select');
                  setLinkedInData(null);
                }}
                startIcon={<CheckIcon />}
                sx={{
                  background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                  color: '#fff',
                  fontFamily: 'Poppins, sans-serif',
                  fontWeight: 600, '&:hover': {
                    background: 'linear-gradient(135deg, #ff8c00 0%, #2563eb 100%)',
                    opacity: 0.9,
                    transform: 'translateY(-1px)',
                    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
                  }}}
              >
                Lukk
              </Button>
            </>
          )}
        </DialogActions>
      </Dialog>

      {/* Export Dialog */}
      <Dialog 
        open={showExportDialog} 
        onClose={() => setShowExportDialog(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Eksporter CV</DialogTitle>
        <DialogContent>
          <Typography variant="body2" gutterBottom>
            Velg format for eksport:
          </Typography>
          <Stack spacing={2} sx={{ mt: 2 }}>
            <Button 
              variant="outlined" 
              fullWidth 
              onClick={() => handleExport('pdf')}
              startIcon={<DownloadIcon />}
            >
              PDF (Anbefalt)
            </Button>
            <Button 
              variant="outlined" 
              fullWidth 
              onClick={() => handleExport('json')}
              startIcon={<DownloadIcon />}
            >
              JSON (Backup)
            </Button>
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowExportDialog(false)}>Lukk</Button>
        </DialogActions>
      </Dialog>

      {/* Portfolio Dialog */}
      <Dialog 
        open={showPortfolioDialog} 
        onClose={() => setShowPortfolioDialog(false)} 
        maxWidth="md" 
        fullWidth
      >
        <DialogTitle>
          {editingPortfolioItem ? 'Rediger portefølje-oppføring' : 'Legg til portefølje-oppføring'}
        </DialogTitle>
        <DialogContent>
          <Stack spacing={3} sx={{ mt: 2 }}>
            {/* Title */}
            <TextField
              label="Tittel"
              fullWidth
              value={portfolioFormData.title || ', '}
              onChange={(e) => setPortfolioFormData(prev => ({ ...prev, title: e.target.value }))}
              required
            />

            {/* Description */}
            <TextField
              label="Beskrivelse"
              fullWidth
              multiline
              rows={3}
              value={portfolioFormData.description || ', '}
              onChange={(e) => setPortfolioFormData(prev => ({ ...prev, description: e.target.value }))}
              required
            />

            {/* Category */}
            <FormControl fullWidth>
              <InputLabel>Kategori</InputLabel>
              <Select
                value={portfolioFormData.category || 'project'}
                onChange={(e) => setPortfolioFormData(prev => ({ ...prev, category: e.target.value as PortfolioItem['category'] }))}
              >
                <MenuItem value="project">Prosjekt</MenuItem>
                <MenuItem value="design">Design</MenuItem>
                <MenuItem value="documentation">Dokumentasjon</MenuItem>
                <MenuItem value="presentation">Presentasjon</MenuItem>
                <MenuItem value="other">Annet</MenuItem>
              </Select>
            </FormControl>

            {/* Technologies */}
            <Autocomplete
              multiple
              freeSolo
              options={[]}
              value={portfolioFormData.technologies || []}
              onChange={(event, newValue) => {
                setPortfolioFormData(prev => ({ ...prev, technologies: newValue }));
              }}
              renderTags={(value, getTagProps) =>
                value.map((option, index) => (
                  <Chip variant="outlined" label={option} {...getTagProps({ index })} />
                ))
              }
              renderInput={(params) => (
                <TextField
                  {...params}
                  label="Teknologier"
                  placeholder="Skriv og trykk Enter for å legge til"
                />
              )}
            />

            {/* Google Drive Links */}
            <Box>
              <Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}>
                <Typography variant="h6">Google Drive-filer</Typography>
                <Button
                  variant="outlined"
                  startIcon={<CloudUploadIcon />}
                  onClick={handleGoogleDriveFilePicker}
                  disabled={!auth.state.isAuthenticated}
                >
                  Velg fra Google Drive
                </Button>
              </Stack>

              {!auth.state.isAuthenticated && (
                <Alert severity="warning" sx={{ mb: 2 }}>
                  Du må være logget inn med Google for å kunne velge filer fra Google Drive.
                </Alert>
              )}

              {portfolioFormData.googleDriveLinks && portfolioFormData.googleDriveLinks.length > 0 && (
                <Stack spacing={1}>
                  {portfolioFormData.googleDriveLinks.map((link) => (
                    <Card key={link.id} variant="outlined">
                      <CardContent sx={{ py: 1 }}>
                        <Stack direction="row" alignItems="center" spacing={2}>
                          {getFileIcon(link.type)}
                          <Box sx={{ flex: 1 }}>
                            <Typography variant="body2" fontWeight={500}>
                              {link.name}
                            </Typography>
                            <Typography variant="caption" color="textSecondary">
                              {link.type.toUpperCase()} {link.size && `• ${link.size}`}
                            </Typography>
                          </Box>
                          <Button
                            size="small"
                            color="error"
                            onClick={() => handleRemoveGoogleDriveLink(link.id)}
                          >
                            <DeleteIcon />
                          </Button>
                        </Stack>
                      </CardContent>
                    </Card>
                  ))}
                </Stack>
              )}

              {(!portfolioFormData.googleDriveLinks || portfolioFormData.googleDriveLinks.length === 0) && (
                <Alert severity="info">
                  Ingen Google Drive-filer valgt. Klikk på "Velg fra Google Drive" for å legge til filer.
                </Alert>
              )}
            </Box>

            {/* Public/Private */}
            <FormControlLabel
              control={
                <Switch
                  checked={portfolioFormData.isPublic || false}
                  onChange={(e) => setPortfolioFormData(prev => ({ ...prev, isPublic: e.target.checked }))}
                />
              }
              label="Offentlig (synlig for andre)"
            />
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowPortfolioDialog(false)}>
            Avbryt
          </Button>
          <Button
            onClick={handleSavePortfolioItem}
            variant="contained"
            disabled={!portfolioFormData.title || !portfolioFormData.description}
          >
            {editingPortfolioItem ? 'Oppdater' : 'Legg til'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* AI Writing Assistant Dialog - QuillBot-style */}
      <Dialog
        open={aiToolDialog}
        onClose={() => setAiToolDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          <Stack direction="row" alignItems="center" spacing={1}>
            <AIIcon color="primary" />
            <Typography variant="h6">
              {aiToolType === 'paraphrase' && 'AI Omskriving'}
              {aiToolType === 'grammar' && 'AI Grammatikksjekk'}
              {aiToolType === 'summarize' && 'AI Oppsummering'}
              {aiToolType === 'generate-resume' && 'AI CV-Generator'}
              {aiToolType === 'generate-cover-letter' && 'AI Søknadsbrev-Generator'}
            </Typography>
          </Stack>
        </DialogTitle>
        <DialogContent>
          <Stack spacing={3} sx={{ mt: 2 }}>
            {/* Paraphrase Mode Selector */}
            {aiToolType === 'paraphrase' && (
              <FormControl fullWidth>
                <InputLabel>Omskrivings-modus</InputLabel>
                <Select
                  value={aiParaphraseMode}
                  onChange={(e) => setAiParaphraseMode(e.target.value)}
                  label="Omskrivings-modus"
                >
                  {aiParaphraseModes.map((mode) => (
                    <MenuItem key={mode.value} value={mode.value}>
                      <Box>
                        <Typography variant="body1">{mode.label}</Typography>
                        <Typography variant="caption" color="text.secondary">
                          {mode.description}
                        </Typography>
                      </Box>
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            )}

            {/* Input Text */}
            <TextField
              label="Input-tekst"
              multiline
              rows={6}
              value={aiInputText}
              onChange={(e) => setAiInputText(e.target.value)}
              placeholder="Skriv inn eller lim inn tekst her..."
              fullWidth
            />

            {/* Process Button */}
            <Button
              variant="contained"
              startIcon={aiIsProcessing ? <CircularProgress size={20} /> : <AIIcon />}
              onClick={() => {
                if (aiToolType === 'paraphrase') handleAiParaphrase();
                else if (aiToolType === 'grammar') handleAiGrammar();
                else if (aiToolType === 'summarize') handleAiSummarize();
              }}
              disabled={!aiInputText.trim() || aiIsProcessing}
              fullWidth
            >
              {aiIsProcessing ? 'Behandler...' : 'Generer med AI'}
            </Button>

            {/* Output Text */}
            {aiOutputText && (
              <>
                <Divider />
                <TextField
                  label="AI-resultat"
                  multiline
                  rows={6}
                  value={aiOutputText}
                  onChange={(e) => setAiOutputText(e.target.value)}
                  fullWidth
                  InputProps={{
                    endAdornment: (
                      <Tooltip title="Kopier til utklippstavle">
                        <IconButton onClick={() => {
                          navigator.clipboard.writeText(aiOutputText);
                          alert('Kopiert til utklippstavle!');
                        }}>
                          <CopyIcon />
                        </IconButton>
                      </Tooltip>
                    )}}
                />
              </>
            )}
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setAiToolDialog(false)}>
            Avbryt
          </Button>
          {aiOutputText && (
            <Button
              onClick={handleApplyAiResult}
              variant="contained"
              startIcon={<CheckIcon />}
            >
              Bruk resultat
            </Button>
          )}
        </DialogActions>
      </Dialog>
    </Container>
  );
}

