/**
 * Post-session insights card — the immediate-value surface for the
 * ergonomics telemetry opt-in. Shown right after session_end so the
 * photographer sees why they turned it on in the first place.
 *
 * What it displays:
 *   - One-line headline pulled straight from the backend's
 *     ``session.headline`` (generated by ``buildHeadline`` in
 *     ergonomics-telemetry-service).
 *   - Up to 3 delta lines from ``comparison.deltas`` or
 *     ``comparison.praise`` — whichever is more relevant.
 *   - Subtle colour cue based on ``comparison.signal`` (rested /
 *     normal / drained) so the card reads at a glance.
 *
 * Deliberately lightweight — no charts, no numbers the photographer
 * has to decode. The whole point is "5 seconds of value so turning
 * telemetry on is worth it." A fuller dashboard comes later.
 */
import React, { useEffect, useState } from 'react';
import {
  Card,
  CardContent,
  Typography,
  Stack,
  Chip,
  IconButton,
  CircularProgress,
  Box,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import { apiRequest } from '@/lib/queryClient';

interface SessionSummary {
  headline: string;
  hover: {
    assetsViewed: number;
    medianDecisionMs: number;
    p90DecisionMs: number;
    revisitedAssets: number;
  };
  reversal: { decisionsMade: number; reversals: number; rate: number };
}

interface Comparison {
  deltas: string[];
  praise: string[];
  signal: 'rested' | 'normal' | 'drained';
}

interface ApiResponse {
  success: boolean;
  sessionId: string;
  session: SessionSummary;
  comparison: Comparison;
}

export interface PostSessionInsightsCardProps {
  /// The session id the telemetry hook was emitting for the just-
  /// ended review flow. The card fetches GET /telemetry/ergonomics/
  /// session/:sessionId to produce the summary + comparison.
  sessionId: string;
  /// Called when the photographer dismisses the card. Parent owns
  /// visibility so the card can be re-rendered or suppressed on
  /// subsequent sessions (we only show every ~5th to avoid fatigue —
  /// see ReflectPromptModal for the parallel consideration).
  onClose: () => void;
}

const SIGNAL_COLOUR: Record<Comparison['signal'], string> = {
  rested: 'rgba(92, 184, 92, 0.12)',
  normal: 'rgba(255, 255, 255, 0.04)',
  drained: 'rgba(237, 165, 0, 0.12)',
};

const SIGNAL_LABEL: Record<Comparison['signal'], string> = {
  rested: 'Du virker opplagt',
  normal: 'Normal økt',
  drained: 'Virker som du er sliten',
};

export function PostSessionInsightsCard({
  sessionId,
  onClose,
}: PostSessionInsightsCardProps) {
  const [data, setData] = useState<ApiResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let alive = true;
    const load = async () => {
      try {
        const payload = (await apiRequest(
          `/api/telemetry/ergonomics/session/${encodeURIComponent(sessionId)}`,
        )) as ApiResponse;
        if (!alive) return;
        setData(payload);
      } catch (err) {
        if (!alive) return;
        // We never surface a loud error — telemetry is a nice-to-have
        // bonus; if the fetch fails we quietly don't render the card.
        setError(
          err instanceof Error ? err.message : 'Kunne ikke hente innsikt',
        );
      }
    };
    void load();
    return () => {
      alive = false;
    };
  }, [sessionId]);

  if (error) return null;

  if (!data) {
    return (
      <Card variant="outlined" sx={{ p: 1 }}>
        <Stack direction="row" spacing={1} alignItems="center">
          <CircularProgress size={16} />
          <Typography variant="caption" color="text.secondary">
            Henter økt-innsikt…
          </Typography>
        </Stack>
      </Card>
    );
  }

  const { session, comparison } = data;
  // Don't show the card at all on short sessions — the backend's
  // ``buildHeadline`` returns "not enough data yet" in this case, and
  // a card saying that adds noise instead of value.
  if (session.reversal.decisionsMade < 20) return null;

  const lines = comparison.deltas.length > 0
    ? comparison.deltas.slice(0, 3)
    : comparison.praise.slice(0, 3);

  return (
    <Card
      variant="outlined"
      sx={{
        mt: 2,
        mb: 2,
        bgcolor: SIGNAL_COLOUR[comparison.signal],
        borderColor:
          comparison.signal === 'drained'
            ? 'warning.main'
            : comparison.signal === 'rested'
              ? 'success.main'
              : 'divider',
      }}
    >
      <CardContent>
        <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
          <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}>
            <Chip
              size="small"
              label={SIGNAL_LABEL[comparison.signal]}
              color={
                comparison.signal === 'drained'
                  ? 'warning'
                  : comparison.signal === 'rested'
                    ? 'success'
                    : 'default'
              }
            />
            <Chip
              size="small"
              variant="outlined"
              label={`${session.reversal.decisionsMade} beslutninger`}
            />
          </Stack>
          <IconButton size="small" onClick={onClose} aria-label="Lukk">
            <CloseIcon fontSize="small" />
          </IconButton>
        </Stack>

        <Typography variant="body2" sx={{ mb: 1 }}>
          {session.headline}
        </Typography>

        {lines.length > 0 && (
          <Box component="ul" sx={{ pl: 2, m: 0 }}>
            {lines.map((line, idx) => (
              <Typography
                key={idx}
                component="li"
                variant="caption"
                color="text.secondary"
                sx={{ display: 'list-item' }}
              >
                {line}
              </Typography>
            ))}
          </Box>
        )}
      </CardContent>
    </Card>
  );
}

export default PostSessionInsightsCard;
