-- 0000b_missing_columns.sql
-- 962 kolonner som fantes i prod (drizzle-kit push direkte, aldri fanget
-- som SQL-migrasjon) men manglet i migrations-mappen. Oppdaget 2026-08-16
-- ved migrering av ny gentle-grass-DB — genererte "column X does not exist"
-- i flere bakgrunnsjobber (bl.a. prototype_tester_invites.max_team_size).
-- Generert fra pg_catalog på gammel DB (types/defaults nøyaktige).
-- NOT NULL er bevisst utelatt — trygt å legge til når verdier for
-- eksisterende rader er ukjent. Idempotent (IF EXISTS / IF NOT EXISTS).

ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS cost_type character varying(100);
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS amount numeric(10,2);
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS currency character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS cost_date date;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS is_billable boolean DEFAULT true;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS is_reimbursable boolean DEFAULT false;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS receipt_url character varying;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE IF EXISTS public.additional_costs ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS severity character varying DEFAULT 'info'::character varying;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS category character varying;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS is_read boolean DEFAULT false;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS action_required boolean DEFAULT false;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS read_at timestamp without time zone;
ALTER TABLE IF EXISTS public.admin_notifications ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.advanced_email_templates ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.advanced_email_templates ADD COLUMN IF NOT EXISTS subject_template text;
ALTER TABLE IF EXISTS public.advanced_email_templates ADD COLUMN IF NOT EXISTS body_template text;
ALTER TABLE IF EXISTS public.advanced_email_templates ADD COLUMN IF NOT EXISTS category character varying DEFAULT 'general'::character varying;
ALTER TABLE IF EXISTS public.advanced_email_templates ADD COLUMN IF NOT EXISTS profession character varying DEFAULT 'photographer'::character varying;
ALTER TABLE IF EXISTS public.analytics_events ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS hashed_key text;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS prefix text;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS rate_limit integer DEFAULT 100;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS last_used_at timestamp without time zone;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS vendor_id integer;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS key_prefix text;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS key_hash text;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.api_keys ADD COLUMN IF NOT EXISTS revoked_at timestamp without time zone;
ALTER TABLE IF EXISTS public.audit_entries ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.audit_entries ADD COLUMN IF NOT EXISTS resource character varying(100);
ALTER TABLE IF EXISTS public.audit_entries ADD COLUMN IF NOT EXISTS details jsonb;
ALTER TABLE IF EXISTS public.audit_entries ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.auto_monitor_configs ADD COLUMN IF NOT EXISTS monitor_name character varying;
ALTER TABLE IF EXISTS public.auto_monitor_configs ADD COLUMN IF NOT EXISTS monitor_type character varying;
ALTER TABLE IF EXISTS public.auto_monitor_configs ADD COLUMN IF NOT EXISTS config jsonb;
ALTER TABLE IF EXISTS public.auto_monitor_configs ADD COLUMN IF NOT EXISTS last_checked timestamp without time zone;
ALTER TABLE IF EXISTS public.automated_test_suites ADD COLUMN IF NOT EXISTS suite_name character varying;
ALTER TABLE IF EXISTS public.automated_test_suites ADD COLUMN IF NOT EXISTS test_type character varying;
ALTER TABLE IF EXISTS public.automated_test_suites ADD COLUMN IF NOT EXISTS test_config jsonb;
ALTER TABLE IF EXISTS public.automated_test_suites ADD COLUMN IF NOT EXISTS last_run timestamp without time zone;
ALTER TABLE IF EXISTS public.automated_test_suites ADD COLUMN IF NOT EXISTS status character varying DEFAULT 'not-run'::character varying;
ALTER TABLE IF EXISTS public.automation_rules ADD COLUMN IF NOT EXISTS trigger_config jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.automation_rules ADD COLUMN IF NOT EXISTS action_type character varying;
ALTER TABLE IF EXISTS public.automation_rules ADD COLUMN IF NOT EXISTS action_config jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.automation_rules ADD COLUMN IF NOT EXISTS created_by character varying;
ALTER TABLE IF EXISTS public.backup_logs ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.brand_image_discoveries ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.brand_image_discoveries ADD COLUMN IF NOT EXISTS query text;
ALTER TABLE IF EXISTS public.brand_image_discoveries ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE IF EXISTS public.brand_image_discoveries ADD COLUMN IF NOT EXISTS thumbnail_url text;
ALTER TABLE IF EXISTS public.brand_image_discoveries ADD COLUMN IF NOT EXISTS is_saved boolean DEFAULT false;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS business_type character varying(100);
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS vat_number character varying(20);
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS city character varying(100);
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS postal_code character varying(10);
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS country character varying(100) DEFAULT 'Norway'::character varying;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS logo character varying;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS brand_colors jsonb;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS brand_fonts jsonb;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS social_handles jsonb;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS tagline text;
ALTER TABLE IF EXISTS public.business_profiles ADD COLUMN IF NOT EXISTS voice_description text;
ALTER TABLE IF EXISTS public.capture_assets ADD COLUMN IF NOT EXISTS folder_id uuid;
ALTER TABLE IF EXISTS public.casting_production_days ADD COLUMN IF NOT EXISTS data jsonb;
ALTER TABLE IF EXISTS public.casting_props ADD COLUMN IF NOT EXISTS data jsonb;
ALTER TABLE IF EXISTS public.casting_user_roles ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE IF EXISTS public.casting_user_roles ADD COLUMN IF NOT EXISTS deactivated_at timestamp with time zone;
ALTER TABLE IF EXISTS public.casting_user_roles ADD COLUMN IF NOT EXISTS deactivated_by_user_id character varying(255);
ALTER TABLE IF EXISTS public.casting_user_roles ADD COLUMN IF NOT EXISTS deactivation_reason text;
ALTER TABLE IF EXISTS public.client_galleries ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE IF EXISTS public.client_galleries ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE IF EXISTS public.client_galleries ADD COLUMN IF NOT EXISTS client_name text;
ALTER TABLE IF EXISTS public.client_galleries ADD COLUMN IF NOT EXISTS client_email text;
ALTER TABLE IF EXISTS public.client_galleries ADD COLUMN IF NOT EXISTS download_enabled boolean DEFAULT true;
ALTER TABLE IF EXISTS public.client_galleries ADD COLUMN IF NOT EXISTS view_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS client_id character varying;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS submission_type character varying(100) DEFAULT 'inquiry'::character varying;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS data jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS client_email character varying(255);
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS client_name character varying(255);
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS form_data jsonb;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS vendor_id character varying;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS vendor_email character varying;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS is_read boolean DEFAULT false;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS is_starred boolean DEFAULT false;
ALTER TABLE IF EXISTS public.client_submissions ADD COLUMN IF NOT EXISTS category character varying DEFAULT 'inquiry'::character varying;
ALTER TABLE IF EXISTS public.cms_assets ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.cms_assets ADD COLUMN IF NOT EXISTS file_name character varying(255);
ALTER TABLE IF EXISTS public.cms_assets ADD COLUMN IF NOT EXISTS file_type character varying(100);
ALTER TABLE IF EXISTS public.cms_assets ADD COLUMN IF NOT EXISTS file_size bigint;
ALTER TABLE IF EXISTS public.cms_assets ADD COLUMN IF NOT EXISTS file_url text;
ALTER TABLE IF EXISTS public.cms_assets ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.cms_content_types ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE IF EXISTS public.cms_content_types ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE IF EXISTS public.cms_content_types ADD COLUMN IF NOT EXISTS icon text DEFAULT 'FileText'::text;
ALTER TABLE IF EXISTS public.cms_content_types ADD COLUMN IF NOT EXISTS display_field text;
ALTER TABLE IF EXISTS public.cms_content_types ADD COLUMN IF NOT EXISTS is_system boolean DEFAULT false;
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS pageid character varying(255);
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS components jsonb;
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS editedby character varying(255);
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS editnote text;
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS createdat timestamp without time zone;
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS publish_at timestamp with time zone;
ALTER TABLE IF EXISTS public.cms_page_revisions ADD COLUMN IF NOT EXISTS unpublish_at timestamp with time zone;
ALTER TABLE IF EXISTS public.cms_themes ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.cms_themes ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.cms_themes ADD COLUMN IF NOT EXISTS theme_data jsonb;
ALTER TABLE IF EXISTS public.cms_themes ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.code_analysis_results ADD COLUMN IF NOT EXISTS target_file character varying;
ALTER TABLE IF EXISTS public.code_analysis_results ADD COLUMN IF NOT EXISTS results jsonb;
ALTER TABLE IF EXISTS public.code_analysis_results ADD COLUMN IF NOT EXISTS analyzed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.code_generations ADD COLUMN IF NOT EXISTS prompt text;
ALTER TABLE IF EXISTS public.code_generations ADD COLUMN IF NOT EXISTS language character varying(50);
ALTER TABLE IF EXISTS public.code_generations ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.code_templates ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE IF EXISTS public.code_templates ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.code_templates ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS group_id uuid;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS requires_feature character varying(100);
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS requires_subscription_tier character varying(50);
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS is_read_only boolean DEFAULT false;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS "position" integer DEFAULT 0;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS message_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.community_channels ADD COLUMN IF NOT EXISTS member_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.competitor_analysis ADD COLUMN IF NOT EXISTS website character varying(255);
ALTER TABLE IF EXISTS public.competitor_analysis ADD COLUMN IF NOT EXISTS services jsonb;
ALTER TABLE IF EXISTS public.competitor_analysis ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.component_definitions ADD COLUMN IF NOT EXISTS component_schema jsonb;
ALTER TABLE IF EXISTS public.content_analysis_cache ADD COLUMN IF NOT EXISTS content_hash character varying;
ALTER TABLE IF EXISTS public.content_analysis_cache ADD COLUMN IF NOT EXISTS analysis_type character varying;
ALTER TABLE IF EXISTS public.content_analysis_cache ADD COLUMN IF NOT EXISTS analysis_results jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS client_id character varying;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS title character varying(255);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS signed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS source_quote_id character varying;
ALTER TABLE IF EXISTS public.custom_packages ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.custom_packages ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.custom_packages ADD COLUMN IF NOT EXISTS services jsonb;
ALTER TABLE IF EXISTS public.custom_packages ADD COLUMN IF NOT EXISTS base_price numeric(10,2);
ALTER TABLE IF EXISTS public.custom_packages ADD COLUMN IF NOT EXISTS additional_services jsonb;
ALTER TABLE IF EXISTS public.custom_packages ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.custom_roles ADD COLUMN IF NOT EXISTS permissions jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS stages jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS touchpoints jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS personas jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS steps jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS visualization_type character varying(50) DEFAULT 'timeline'::character varying;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS template_type character varying(50);
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS active_persona_id character varying(255);
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS dynamic_links jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS ai_insights jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS conversion_rate numeric(5,2);
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.customer_journey_templates ADD COLUMN IF NOT EXISTS estimated_completion_time integer;
ALTER TABLE IF EXISTS public.customer_pricing ADD COLUMN IF NOT EXISTS customer_id character varying;
ALTER TABLE IF EXISTS public.customer_pricing ADD COLUMN IF NOT EXISTS service_item_id integer;
ALTER TABLE IF EXISTS public.customer_pricing ADD COLUMN IF NOT EXISTS custom_price numeric(10,2);
ALTER TABLE IF EXISTS public.customer_pricing ADD COLUMN IF NOT EXISTS discount_type character varying(50) DEFAULT 'fixed'::character varying;
ALTER TABLE IF EXISTS public.customer_pricing ADD COLUMN IF NOT EXISTS discount_value numeric(10,2) DEFAULT '0'::numeric;
ALTER TABLE IF EXISTS public.customer_signatures ADD COLUMN IF NOT EXISTS sign_request_id integer;
ALTER TABLE IF EXISTS public.dancer_profile_extras ADD COLUMN IF NOT EXISTS availability_confirmed_at timestamp with time zone;
ALTER TABLE IF EXISTS public.data_retention_policies ADD COLUMN IF NOT EXISTS data_type character varying;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS primary_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS primary_color_light text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS primary_color_dark text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS secondary_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS background_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS background_color_dark text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS surface_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS surface_color_dark text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS text_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS text_color_dark text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS muted_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_color text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_family text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_family_heading text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_size_base text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_size_scale text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS line_height_base text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS line_height_heading text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_weight_normal text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_weight_medium text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS font_weight_bold text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS letter_spacing text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS letter_spacing_heading text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_unit text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_xs text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_sm text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_md text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_lg text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_xl text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_2xl text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS spacing_3xl text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_radius_none text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_radius_sm text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_radius_md text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_radius_lg text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_radius_xl text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_radius_full text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS border_width text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS shadow_none text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS shadow_sm text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS shadow_md text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS shadow_lg text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS shadow_xl text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS animation_duration text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS animation_duration_slow text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS animation_duration_fast text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS animation_easing text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS enable_animations boolean;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS enable_hover_effects boolean;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS container_max_width text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS container_padding text;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE IF EXISTS public.design_tokens ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS code character varying(50);
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS discount_type character varying(50);
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS min_order_amount numeric(10,2);
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS max_discount_amount numeric(10,2);
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS valid_from timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS valid_until timestamp without time zone;
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS usage_limit integer;
ALTER TABLE IF EXISTS public.discounts ADD COLUMN IF NOT EXISTS created_by character varying;
ALTER TABLE IF EXISTS public.email_project_associations ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.email_project_associations ADD COLUMN IF NOT EXISTS association_type character varying(100);
ALTER TABLE IF EXISTS public.email_project_associations ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.email_templates ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.email_templates ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE IF EXISTS public.email_templates ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE IF EXISTS public.email_templates ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.email_templates ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE IF EXISTS public.equipment_images ADD COLUMN IF NOT EXISTS equipment_id integer;
ALTER TABLE IF EXISTS public.equipment_images ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.equipment_images ADD COLUMN IF NOT EXISTS image_type character varying DEFAULT 'equipment'::character varying;
ALTER TABLE IF EXISTS public.equipment_images ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.equipment_images ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS service_provider character varying;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS next_scheduled_date timestamp without time zone;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS parts_replaced jsonb;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS labor_hours numeric(5,2);
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS warranty_extended boolean DEFAULT false;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS receipt_url character varying;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS before_photos jsonb;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS after_photos jsonb;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS service_notes text;
ALTER TABLE IF EXISTS public.equipment_maintenance ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS equipment_id integer;
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS rental_cost numeric(10,2);
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS client_name character varying;
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS return_condition character varying;
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS late_fees numeric(10,2) DEFAULT '0'::numeric;
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS pickup_photos jsonb;
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS return_photos jsonb;
ALTER TABLE IF EXISTS public.equipment_rentals ADD COLUMN IF NOT EXISTS damage_notes text;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS category character varying DEFAULT 'lighting'::character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS update_type character varying DEFAULT 'firmware'::character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS is_critical boolean DEFAULT false;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS download_size character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS installation_time character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS photographer_benefits jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS videographer_benefits jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS music_producer_benefits jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS general_improvements jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS bug_fixes jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS new_features jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS requirements jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS compatibility jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS known_issues jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS installation_steps jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS rollback_instructions jsonb;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS photographer_recommendation character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS videographer_recommendation character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS music_producer_recommendation character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS risk_level character varying DEFAULT 'low'::character varying;
ALTER TABLE IF EXISTS public.firmware_updates ADD COLUMN IF NOT EXISTS last_verified timestamp without time zone;
ALTER TABLE IF EXISTS public.gdpr_audit_trails ADD COLUMN IF NOT EXISTS details jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS announcement_type character varying(50);
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS release_date date;
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS price numeric(10,2);
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS currency character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS specifications jsonb;
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE IF EXISTS public.gear_announcements ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE IF EXISTS public.generated_code_history ADD COLUMN IF NOT EXISTS parameters jsonb;
ALTER TABLE IF EXISTS public.generated_code_history ADD COLUMN IF NOT EXISTS generated_by character varying;
ALTER TABLE IF EXISTS public.generated_code_history ADD COLUMN IF NOT EXISTS generated_at timestamp without time zone;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS file_id character varying(255);
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS folder_id character varying(255);
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS file_path text;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS scene_id uuid;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS asset_id uuid;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS render_id uuid;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS export_id uuid;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS web_content_link text;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS thumbnail_link text;
ALTER TABLE IF EXISTS public.google_drive_files ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.google_integration_settings ADD COLUMN IF NOT EXISTS drive_folder_id character varying(255);
ALTER TABLE IF EXISTS public.google_integration_settings ADD COLUMN IF NOT EXISTS sheets_id character varying(255);
ALTER TABLE IF EXISTS public.google_integration_settings ADD COLUMN IF NOT EXISTS pricing_sheets_id character varying(255);
ALTER TABLE IF EXISTS public.google_pay_billing_issues ADD COLUMN IF NOT EXISTS subscription_id uuid;
ALTER TABLE IF EXISTS public.google_pay_products ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.google_pay_products ADD COLUMN IF NOT EXISTS monthly_price numeric(10,2);
ALTER TABLE IF EXISTS public.google_pay_products ADD COLUMN IF NOT EXISTS annual_price numeric(10,2);
ALTER TABLE IF EXISTS public.google_pay_products ADD COLUMN IF NOT EXISTS currency character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.google_pay_products ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS subscription_id uuid;
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS transaction_type character varying(100);
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS amount_micros bigint;
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS currency_code character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS transaction_id character varying(255);
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS external_transaction_id character varying(255);
ALTER TABLE IF EXISTS public.google_pay_transactions ADD COLUMN IF NOT EXISTS processed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS month integer;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS included_hours integer;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS used_hours integer;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS total_overage_cost numeric(10,2);
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS billed boolean DEFAULT false;
ALTER TABLE IF EXISTS public.hour_overages ADD COLUMN IF NOT EXISTS billed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.improvement_tasks ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE IF EXISTS public.improvement_tasks ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.invite_requests ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.invite_requests ADD COLUMN IF NOT EXISTS invited_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.invite_requests ADD COLUMN IF NOT EXISTS accepted_at timestamp without time zone;
ALTER TABLE IF EXISTS public.job_applications ADD COLUMN IF NOT EXISTS userid character varying(255);
ALTER TABLE IF EXISTS public.job_applications ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.lead_import_templates ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.lead_import_templates ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.lead_import_templates ADD COLUMN IF NOT EXISTS template_data jsonb;
ALTER TABLE IF EXISTS public.lead_import_templates ADD COLUMN IF NOT EXISTS field_mappings jsonb;
ALTER TABLE IF EXISTS public.lead_import_templates ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.lead_import_templates ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.lighting_equipment ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE IF EXISTS public.lighting_equipment ADD COLUMN IF NOT EXISTS specifications jsonb;
ALTER TABLE IF EXISTS public.lighting_models ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.lighting_models ADD COLUMN IF NOT EXISTS model_data jsonb;
ALTER TABLE IF EXISTS public.lighting_setups ADD COLUMN IF NOT EXISTS equipment jsonb;
ALTER TABLE IF EXISTS public.lighting_setups ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.live_test_results ADD COLUMN IF NOT EXISTS test_suite_id uuid;
ALTER TABLE IF EXISTS public.live_test_results ADD COLUMN IF NOT EXISTS test_name character varying;
ALTER TABLE IF EXISTS public.live_test_results ADD COLUMN IF NOT EXISTS result character varying;
ALTER TABLE IF EXISTS public.live_test_results ADD COLUMN IF NOT EXISTS duration integer;
ALTER TABLE IF EXISTS public.live_test_results ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE IF EXISTS public.live_test_results ADD COLUMN IF NOT EXISTS executed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.magic_creator_features ADD COLUMN IF NOT EXISTS feature_key character varying(100);
ALTER TABLE IF EXISTS public.magic_creator_features ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.magic_creator_features ADD COLUMN IF NOT EXISTS is_enabled boolean DEFAULT true;
ALTER TABLE IF EXISTS public.magic_creator_features ADD COLUMN IF NOT EXISTS configuration jsonb;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS spent numeric(10,2) DEFAULT 0.00;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS impressions integer DEFAULT 0;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS clicks integer DEFAULT 0;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS conversions integer DEFAULT 0;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS conversion_value numeric(10,2) DEFAULT 0.00;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS campaign_data jsonb;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS norwegian_market_performance jsonb;
ALTER TABLE IF EXISTS public.marketing_campaigns ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.meeting_activities ADD COLUMN IF NOT EXISTS meeting_id character varying;
ALTER TABLE IF EXISTS public.meeting_activities ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS meeting_note_id uuid;
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS file_size bigint;
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS thumbnail_url text;
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS google_drive_id character varying(255);
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.meeting_attachments ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS title character varying;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS note_type character varying DEFAULT 'text'::character varying;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS "position" jsonb DEFAULT '{"x": 0, "y": 0, "z": 0}'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS size jsonb DEFAULT '{"width": 200, "height": 150}'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS style jsonb DEFAULT '{"fontSize": "14px", "textColor": "#333333", "fontFamily": "Inter", "backgroundColor": "#fff3cd"}'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS follow_up_tasks jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS participants jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS agenda jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS position_x integer DEFAULT 0;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS position_y integer DEFAULT 0;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS width integer DEFAULT 200;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS height integer DEFAULT 150;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS color character varying DEFAULT '#ffeb3b'::character varying;
ALTER TABLE IF EXISTS public.meeting_notes ADD COLUMN IF NOT EXISTS created_by character varying;
ALTER TABLE IF EXISTS public.meeting_participants ADD COLUMN IF NOT EXISTS meeting_id character varying;
ALTER TABLE IF EXISTS public.meeting_participants ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.meeting_participants ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.meeting_participants ADD COLUMN IF NOT EXISTS email character varying(255);
ALTER TABLE IF EXISTS public.meeting_workspaces ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.meeting_workspaces ADD COLUMN IF NOT EXISTS workspace_type character varying(100) DEFAULT 'meeting'::character varying;
ALTER TABLE IF EXISTS public.meeting_workspaces ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE IF EXISTS public.meeting_workspaces ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.notes ADD COLUMN IF NOT EXISTS status character varying(50) DEFAULT 'draft'::character varying;
ALTER TABLE IF EXISTS public.notes ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false;
ALTER TABLE IF EXISTS public.notes ADD COLUMN IF NOT EXISTS google_drive_url text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS recipient_type text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS recipient_id character varying;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS payload text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS related_entity_type text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS related_entity_id character varying;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS actor_type text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS actor_id character varying;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS actor_name text;
ALTER TABLE IF EXISTS public.notifications ADD COLUMN IF NOT EXISTS sent_via text DEFAULT 'in_app'::text;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS client_secret text;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS total_authorizations integer DEFAULT 0;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS last_authorization timestamp without time zone;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.oauth_clients ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.ocr_receipts ADD COLUMN IF NOT EXISTS vendor character varying(255);
ALTER TABLE IF EXISTS public.ocr_receipts ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.ocr_receipts ADD COLUMN IF NOT EXISTS extracted_text text;
ALTER TABLE IF EXISTS public.ocr_receipts ADD COLUMN IF NOT EXISTS receipt_number character varying(100);
ALTER TABLE IF EXISTS public.ocr_receipts ADD COLUMN IF NOT EXISTS tax_amount numeric(10,2);
ALTER TABLE IF EXISTS public.ocr_receipts ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE IF EXISTS public.onboarding_profiles ADD COLUMN IF NOT EXISTS step character varying(100);
ALTER TABLE IF EXISTS public.onboarding_profiles ADD COLUMN IF NOT EXISTS completed boolean DEFAULT false;
ALTER TABLE IF EXISTS public.onboarding_profiles ADD COLUMN IF NOT EXISTS data jsonb;
ALTER TABLE IF EXISTS public.onboarding_profiles ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.openapi_documentation_protocols ADD COLUMN IF NOT EXISTS service_name character varying;
ALTER TABLE IF EXISTS public.openapi_documentation_protocols ADD COLUMN IF NOT EXISTS api_version character varying;
ALTER TABLE IF EXISTS public.openapi_documentation_protocols ADD COLUMN IF NOT EXISTS documentation_spec jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.openapi_documentation_protocols ADD COLUMN IF NOT EXISTS endpoint_mapping jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.openapi_documentation_protocols ADD COLUMN IF NOT EXISTS authentication_schemes jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.openapi_documentation_protocols ADD COLUMN IF NOT EXISTS is_published boolean DEFAULT false;
ALTER TABLE IF EXISTS public.packages ADD COLUMN IF NOT EXISTS price numeric(10,2);
ALTER TABLE IF EXISTS public.packages ADD COLUMN IF NOT EXISTS hours_included integer;
ALTER TABLE IF EXISTS public.packages ADD COLUMN IF NOT EXISTS deliverables jsonb;
ALTER TABLE IF EXISTS public.packages ADD COLUMN IF NOT EXISTS additional_options jsonb;
ALTER TABLE IF EXISTS public.packages ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.page_drafts ADD COLUMN IF NOT EXISTS auto_save boolean DEFAULT true;
ALTER TABLE IF EXISTS public.page_templates ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.page_templates ADD COLUMN IF NOT EXISTS template_data jsonb;
ALTER TABLE IF EXISTS public.page_templates ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.page_templates ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS version_number integer;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS content jsonb;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS version_note text;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS sections jsonb;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS theme_key text;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS custom_css text;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS changed_by text;
ALTER TABLE IF EXISTS public.page_versions ADD COLUMN IF NOT EXISTS change_note text;
ALTER TABLE IF EXISTS public.preset_suggestions ADD COLUMN IF NOT EXISTS preset_id integer;
ALTER TABLE IF EXISTS public.preset_suggestions ADD COLUMN IF NOT EXISTS suggestion_type character varying(100);
ALTER TABLE IF EXISTS public.preset_suggestions ADD COLUMN IF NOT EXISTS relevance_score numeric(5,2);
ALTER TABLE IF EXISTS public.preset_suggestions ADD COLUMN IF NOT EXISTS context jsonb;
ALTER TABLE IF EXISTS public.preset_suggestions ADD COLUMN IF NOT EXISTS is_accepted boolean DEFAULT false;
ALTER TABLE IF EXISTS public.preset_usage_history ADD COLUMN IF NOT EXISTS used_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.pricing_categories ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.pricing_categories ADD COLUMN IF NOT EXISTS color character varying(7) DEFAULT '#3B82F6'::character varying;
ALTER TABLE IF EXISTS public.pricing_categories ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;
ALTER TABLE IF EXISTS public.pricing_structures ADD COLUMN IF NOT EXISTS travel_included boolean;
ALTER TABLE IF EXISTS public.pricing_structures ADD COLUMN IF NOT EXISTS travel_radius_km integer;
ALTER TABLE IF EXISTS public.pricing_structures ADD COLUMN IF NOT EXISTS travel_rate_per_km numeric(8,2);
ALTER TABLE IF EXISTS public.privacy_requests ADD COLUMN IF NOT EXISTS details jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.privacy_requests ADD COLUMN IF NOT EXISTS processed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS original_filename character varying;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS processed_filename character varying;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS file_path character varying;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS processing_type character varying;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS status character varying DEFAULT 'processing'::character varying;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.processed_files ADD COLUMN IF NOT EXISTS processed_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS price numeric(10,2);
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS currency character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS sku character varying(100);
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS stock_quantity integer DEFAULT 0;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.profession_configurations ADD COLUMN IF NOT EXISTS profession character varying(100);
ALTER TABLE IF EXISTS public.profession_configurations ADD COLUMN IF NOT EXISTS display_name character varying(255);
ALTER TABLE IF EXISTS public.profession_configurations ADD COLUMN IF NOT EXISTS configuration jsonb;
ALTER TABLE IF EXISTS public.profession_configurations ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.profession_types ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE IF EXISTS public.project_draft_autosave ADD COLUMN IF NOT EXISTS version integer DEFAULT 1;
ALTER TABLE IF EXISTS public.project_draft_autosave ADD COLUMN IF NOT EXISTS last_saved_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.project_draft_autosave ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.project_draft_versions ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.project_draft_versions ADD COLUMN IF NOT EXISTS draft_data jsonb;
ALTER TABLE IF EXISTS public.project_draft_versions ADD COLUMN IF NOT EXISTS version_note text;
ALTER TABLE IF EXISTS public.project_emails ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE IF EXISTS public.project_presets ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE IF EXISTS public.project_presets ADD COLUMN IF NOT EXISTS preset_data jsonb;
ALTER TABLE IF EXISTS public.project_presets ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.project_presets ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.project_presets ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.project_showcases ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.project_showcases ADD COLUMN IF NOT EXISTS status character varying(50) DEFAULT 'draft'::character varying;
ALTER TABLE IF EXISTS public.project_showcases ADD COLUMN IF NOT EXISTS visibility character varying(50) DEFAULT 'private'::character varying;
ALTER TABLE IF EXISTS public.project_showcases ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE IF EXISTS public.project_similarity_analysis ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.project_similarity_analysis ADD COLUMN IF NOT EXISTS similar_project_id character varying;
ALTER TABLE IF EXISTS public.project_timelines ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.project_timelines ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.project_timelines ADD COLUMN IF NOT EXISTS timeline_data jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.project_timelines ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.prototype_feedback ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.prototype_feedback ADD COLUMN IF NOT EXISTS client_id character varying;
ALTER TABLE IF EXISTS public.prototype_feedback ADD COLUMN IF NOT EXISTS feedback text;
ALTER TABLE IF EXISTS public.prototype_feedback ADD COLUMN IF NOT EXISTS submitted_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS granted_plan character varying(50) DEFAULT 'tester_all_access'::character varying;
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS granted_features jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS team_role character varying(20) DEFAULT 'individual'::character varying;
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS master_invite_id uuid;
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS max_team_size integer DEFAULT 1;
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS member_profession character varying(40);
ALTER TABLE IF EXISTS public.prototype_tester_invites ADD COLUMN IF NOT EXISTS member_company character varying(160);
ALTER TABLE IF EXISTS public.push_subscriptions ADD COLUMN IF NOT EXISTS subscription_data jsonb;
ALTER TABLE IF EXISTS public.push_subscriptions ADD COLUMN IF NOT EXISTS timeline_id character varying(255);
ALTER TABLE IF EXISTS public.push_subscriptions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS client_name character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS client_email character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS title character varying(255);
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS base_price numeric(10,2);
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS additional_services jsonb;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS client_info jsonb;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS approvers jsonb;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS project_creation_data jsonb;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS business_info jsonb;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS profession character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS project_type character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS quote_type character varying(50) DEFAULT 'standard'::character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS contract_amendment_for character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS accepted_at timestamp without time zone;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_invoice_id character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_invoice_number character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_customer_id character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_issue_date date;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_due_date date;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_invoice_url text;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_invoice_status character varying(50) DEFAULT 'draft'::character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_sync_status character varying(50) DEFAULT 'pending'::character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_synced_at timestamp without time zone;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS fiken_last_error text;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS accounting_provider character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS accounting_status character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_customer_id character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_invoice_id character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_invoice_number character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_invoice_status character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_invoice_url text;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_voucher_id character varying;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_voucher_url text;
ALTER TABLE IF EXISTS public.quotes ADD COLUMN IF NOT EXISTS tripletex_synced_at timestamp without time zone;
ALTER TABLE IF EXISTS public.rbac_audit_log ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.rbac_audit_log ADD COLUMN IF NOT EXISTS resource character varying(255);
ALTER TABLE IF EXISTS public.rbac_audit_log ADD COLUMN IF NOT EXISTS resource_id character varying;
ALTER TABLE IF EXISTS public.rbac_audit_log ADD COLUMN IF NOT EXISTS old_value jsonb;
ALTER TABLE IF EXISTS public.rbac_audit_log ADD COLUMN IF NOT EXISTS new_value jsonb;
ALTER TABLE IF EXISTS public.rbac_audit_log ADD COLUMN IF NOT EXISTS "timestamp" timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.referral_program ADD COLUMN IF NOT EXISTS referrer_id character varying;
ALTER TABLE IF EXISTS public.referral_program ADD COLUMN IF NOT EXISTS referred_id character varying;
ALTER TABLE IF EXISTS public.referral_program ADD COLUMN IF NOT EXISTS reward_amount numeric(10,2);
ALTER TABLE IF EXISTS public.referral_program ADD COLUMN IF NOT EXISTS reward_type character varying(50);
ALTER TABLE IF EXISTS public.referral_program ADD COLUMN IF NOT EXISTS earned_at timestamp without time zone;
ALTER TABLE IF EXISTS public.referral_program ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.resume_ai_analyses ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resume_ai_analyses ADD COLUMN IF NOT EXISTS userid character varying(255);
ALTER TABLE IF EXISTS public.resume_certifications ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resume_education ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resume_experiences ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resume_exports ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resume_exports ADD COLUMN IF NOT EXISTS userid character varying(255);
ALTER TABLE IF EXISTS public.resume_projects ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resume_skills ADD COLUMN IF NOT EXISTS resumeid character varying(255);
ALTER TABLE IF EXISTS public.resumes ADD COLUMN IF NOT EXISTS userid character varying(255);
ALTER TABLE IF EXISTS public.role_features ADD COLUMN IF NOT EXISTS can_create boolean DEFAULT false;
ALTER TABLE IF EXISTS public.role_features ADD COLUMN IF NOT EXISTS can_read boolean DEFAULT true;
ALTER TABLE IF EXISTS public.role_features ADD COLUMN IF NOT EXISTS can_update boolean DEFAULT false;
ALTER TABLE IF EXISTS public.role_features ADD COLUMN IF NOT EXISTS can_delete boolean DEFAULT false;
ALTER TABLE IF EXISTS public.role_features ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.role_hierarchy ADD COLUMN IF NOT EXISTS inheritance_level integer DEFAULT 1;
ALTER TABLE IF EXISTS public.role_room_google_connections ADD COLUMN IF NOT EXISTS oauth_app character varying(32) DEFAULT 'role_room'::character varying;
ALTER TABLE IF EXISTS public.role_room_member_profiles ADD COLUMN IF NOT EXISTS profile_image_b2_key character varying(500);
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS activity_type character varying(100);
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS subject character varying(255);
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS outcome character varying(100);
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS scheduled_date timestamp without time zone;
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS completed_date timestamp without time zone;
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS duration integer;
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS next_action text;
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS next_action_date timestamp without time zone;
ALTER TABLE IF EXISTS public.sales_activities ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.sales_analytics ADD COLUMN IF NOT EXISTS period_date date;
ALTER TABLE IF EXISTS public.sales_analytics ADD COLUMN IF NOT EXISTS leads_generated integer DEFAULT 0;
ALTER TABLE IF EXISTS public.sales_analytics ADD COLUMN IF NOT EXISTS quotes_sent integer DEFAULT 0;
ALTER TABLE IF EXISTS public.sales_analytics ADD COLUMN IF NOT EXISTS quotes_accepted integer DEFAULT 0;
ALTER TABLE IF EXISTS public.sales_analytics ADD COLUMN IF NOT EXISTS revenue numeric(15,2) DEFAULT '0'::numeric;
ALTER TABLE IF EXISTS public.sales_analytics ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS conversation_type character varying(50);
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS channel character varying(50);
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS subject character varying(255);
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS participants jsonb;
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS started_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS ended_at timestamp without time zone;
ALTER TABLE IF EXISTS public.sales_conversations ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS priority character varying(20) DEFAULT 'medium'::character varying;
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS contact_name character varying(255);
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS contact_email character varying(255);
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS contact_phone character varying(50);
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS estimated_value numeric(10,2);
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS expected_close_date date;
ALTER TABLE IF EXISTS public.sales_leads ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE IF EXISTS public.security_incidents ADD COLUMN IF NOT EXISTS incident_type character varying;
ALTER TABLE IF EXISTS public.security_incidents ADD COLUMN IF NOT EXISTS affected_systems jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.security_incidents ADD COLUMN IF NOT EXISTS detected_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.security_incidents ADD COLUMN IF NOT EXISTS resolved_at timestamp without time zone;
ALTER TABLE IF EXISTS public.seo_backlinks ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.seo_backlinks ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.seo_backlinks ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS campaign_id uuid;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS "position" integer;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS impressions integer DEFAULT 0;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS clicks integer DEFAULT 0;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS ctr numeric(5,2);
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS change_7d integer DEFAULT 0;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS change_30d integer DEFAULT 0;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS change_life integer DEFAULT 0;
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.seo_keywords ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS keywords jsonb;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS page_path text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS meta_keywords text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS canonical_url text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS og_title text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS og_description text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS og_image text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS og_type text DEFAULT 'website'::text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS twitter_card text DEFAULT 'summary_large_image'::text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS twitter_title text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS twitter_description text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS twitter_image text;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS robots_index boolean DEFAULT true;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS robots_follow boolean DEFAULT true;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS structured_data jsonb;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS priority real DEFAULT 0.5;
ALTER TABLE IF EXISTS public.seo_pages ADD COLUMN IF NOT EXISTS change_frequency text DEFAULT 'weekly'::text;
ALTER TABLE IF EXISTS public.service_activations ADD COLUMN IF NOT EXISTS service_id character varying;
ALTER TABLE IF EXISTS public.service_activations ADD COLUMN IF NOT EXISTS status character varying(50) DEFAULT 'active'::character varying;
ALTER TABLE IF EXISTS public.service_activations ADD COLUMN IF NOT EXISTS deactivated_at timestamp without time zone;
ALTER TABLE IF EXISTS public.service_activations ADD COLUMN IF NOT EXISTS configuration jsonb;
ALTER TABLE IF EXISTS public.service_activations ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.session_activity_log ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.session_activity_log ADD COLUMN IF NOT EXISTS resource character varying(255);
ALTER TABLE IF EXISTS public.session_activity_log ADD COLUMN IF NOT EXISTS details jsonb;
ALTER TABLE IF EXISTS public.session_activity_log ADD COLUMN IF NOT EXISTS ip_address character varying;
ALTER TABLE IF EXISTS public.session_activity_log ADD COLUMN IF NOT EXISTS user_agent text;
ALTER TABLE IF EXISTS public.session_activity_log ADD COLUMN IF NOT EXISTS "timestamp" timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS wedding_timeline_id character varying;
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS template_type character varying(100) DEFAULT 'wedding'::character varying;
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS culture character varying(100) DEFAULT 'norsk'::character varying;
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS shots_data jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS critical_shots integer DEFAULT 0;
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS completed_critical_shots integer DEFAULT 0;
ALTER TABLE IF EXISTS public.shot_lists ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.showcase_categories ADD COLUMN IF NOT EXISTS profession character varying(100);
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS cover_image_url character varying(500);
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS slug character varying(255);
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS profession character varying(50);
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS visibility character varying(20) DEFAULT 'private'::character varying;
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS parent_folder_id character varying(255);
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false;
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS "order" integer DEFAULT 0;
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE IF EXISTS public.showcase_collections ADD COLUMN IF NOT EXISTS collection_config jsonb;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS showcase_id character varying;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS comment text;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS comment_type character varying(50) DEFAULT 'general'::character varying;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS rating integer;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS is_approved boolean DEFAULT false;
ALTER TABLE IF EXISTS public.showcase_comments ADD COLUMN IF NOT EXISTS is_private boolean DEFAULT false;
ALTER TABLE IF EXISTS public.showcase_content_items ADD COLUMN IF NOT EXISTS showcase_id character varying;
ALTER TABLE IF EXISTS public.showcase_content_items ADD COLUMN IF NOT EXISTS content_type character varying(100);
ALTER TABLE IF EXISTS public.showcase_content_items ADD COLUMN IF NOT EXISTS media_url text;
ALTER TABLE IF EXISTS public.showcase_content_items ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;
ALTER TABLE IF EXISTS public.showcase_content_items ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.showcase_content_items ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.showcase_drive_sync ADD COLUMN IF NOT EXISTS showcase_id character varying;
ALTER TABLE IF EXISTS public.showcase_drive_sync ADD COLUMN IF NOT EXISTS last_synced_at timestamp without time zone;
ALTER TABLE IF EXISTS public.showcase_drive_sync ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.showcase_interactions ADD COLUMN IF NOT EXISTS showcase_id character varying;
ALTER TABLE IF EXISTS public.showcase_interactions ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.showcase_interactions ADD COLUMN IF NOT EXISTS session_id character varying(255);
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS profession character varying(100);
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS crop_data jsonb;
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS thumbnail_data jsonb;
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS delivery_id character varying;
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS source_type character varying DEFAULT 'manual'::character varying;
ALTER TABLE IF EXISTS public.showcase_items ADD COLUMN IF NOT EXISTS access_code character varying;
ALTER TABLE IF EXISTS public.showcase_settings ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE IF EXISTS public.showcase_templates ADD COLUMN IF NOT EXISTS template_data jsonb;
ALTER TABLE IF EXISTS public.sign_requests ADD COLUMN IF NOT EXISTS requested_by character varying;
ALTER TABLE IF EXISTS public.sign_requests ADD COLUMN IF NOT EXISTS signer_email character varying(255);
ALTER TABLE IF EXISTS public.sign_requests ADD COLUMN IF NOT EXISTS signer_name character varying(255);
ALTER TABLE IF EXISTS public.sign_requests ADD COLUMN IF NOT EXISTS requested_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.sign_requests ADD COLUMN IF NOT EXISTS signed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.smart_albums ADD COLUMN IF NOT EXISTS criteria jsonb;
ALTER TABLE IF EXISTS public.smart_albums ADD COLUMN IF NOT EXISTS auto_update boolean DEFAULT true;
ALTER TABLE IF EXISTS public.smart_albums ADD COLUMN IF NOT EXISTS cover_image_url text;
ALTER TABLE IF EXISTS public.smart_notes ADD COLUMN IF NOT EXISTS note_type character varying(50) DEFAULT 'general'::character varying;
ALTER TABLE IF EXISTS public.smart_notes ADD COLUMN IF NOT EXISTS ai_enhanced boolean DEFAULT false;
ALTER TABLE IF EXISTS public.smart_notes ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false;
ALTER TABLE IF EXISTS public.smart_templates ADD COLUMN IF NOT EXISTS user_id character varying;
ALTER TABLE IF EXISTS public.smart_templates ADD COLUMN IF NOT EXISTS template_type character varying(100);
ALTER TABLE IF EXISTS public.smart_templates ADD COLUMN IF NOT EXISTS template_data jsonb;
ALTER TABLE IF EXISTS public.smart_templates ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.smart_templates ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.standard_packages ADD COLUMN IF NOT EXISTS profession character varying(100);
ALTER TABLE IF EXISTS public.standard_packages ADD COLUMN IF NOT EXISTS services jsonb;
ALTER TABLE IF EXISTS public.standard_packages ADD COLUMN IF NOT EXISTS duration integer;
ALTER TABLE IF EXISTS public.standard_packages ADD COLUMN IF NOT EXISTS is_popular boolean DEFAULT false;
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS project_name character varying;
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS project_type character varying;
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS story_structure jsonb;
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS characters jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS timeline jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS title character varying(255);
ALTER TABLE IF EXISTS public.story_arc_projects ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.story_arc_templates ADD COLUMN IF NOT EXISTS template_name character varying;
ALTER TABLE IF EXISTS public.story_arc_templates ADD COLUMN IF NOT EXISTS template_type character varying;
ALTER TABLE IF EXISTS public.story_arc_templates ADD COLUMN IF NOT EXISTS template_structure jsonb;
ALTER TABLE IF EXISTS public.story_arc_templates ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.story_arc_templates ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.subscription_change_history ADD COLUMN IF NOT EXISTS from_tier_id character varying;
ALTER TABLE IF EXISTS public.subscription_change_history ADD COLUMN IF NOT EXISTS to_tier_id character varying;
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS tier_id character varying;
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS payment_method character varying(100);
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS last_billed timestamp without time zone;
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS next_billing timestamp without time zone;
ALTER TABLE IF EXISTS public.system_features ADD COLUMN IF NOT EXISTS feature_key character varying(100);
ALTER TABLE IF EXISTS public.system_features ADD COLUMN IF NOT EXISTS is_premium boolean DEFAULT false;
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS project_id character varying;
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS quarter integer;
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS gross_income numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS business_expenses numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS net_income numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS vat_collected numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS vat_paid numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS vat_owed numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS income_tax numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS total_tax numeric(15,2);
ALTER TABLE IF EXISTS public.tax_calculations ADD COLUMN IF NOT EXISTS filed_at timestamp without time zone;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS template_name character varying;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS view_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS rating numeric;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS last_used timestamp without time zone;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS performance jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.template_analytics ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.text_enhancement_history ADD COLUMN IF NOT EXISTS context jsonb;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS break_hours numeric(4,2) DEFAULT '0'::numeric;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS activity character varying(50) DEFAULT 'work'::character varying;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS title character varying(255);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS client_id character varying(255);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS project_name character varying(255);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS place character varying(255);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS calculated_hours numeric(6,2);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS calculated_amount numeric(10,2);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS is_invoiced boolean DEFAULT false;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS invoice_id character varying(255);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS invoiced_at timestamp without time zone;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS location jsonb;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS recurrence_key character varying(255);
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS is_template boolean DEFAULT false;
ALTER TABLE IF EXISTS public.time_entries ADD COLUMN IF NOT EXISTS google_drive_file_id character varying(255);
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS travel_type character varying(50);
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS destination character varying(255);
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS departure_date date;
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS return_date date;
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS cost numeric(10,2);
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS currency character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE IF EXISTS public.travel_expenses ADD COLUMN IF NOT EXISTS is_reimbursable boolean DEFAULT true;
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS start_location character varying(255);
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS end_location character varying(255);
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS duration integer;
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS travel_date date;
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS cost numeric(10,2);
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS fiken_travel_log_id character varying;
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS fiken_sync_status character varying(50) DEFAULT 'pending'::character varying;
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS fiken_synced_at timestamp without time zone;
ALTER TABLE IF EXISTS public.travel_log ADD COLUMN IF NOT EXISTS fiken_last_error text;
ALTER TABLE IF EXISTS public.trial_notifications ADD COLUMN IF NOT EXISTS status character varying(50) DEFAULT 'pending'::character varying;
ALTER TABLE IF EXISTS public.trial_usage_tracking ADD COLUMN IF NOT EXISTS feature_key character varying(100);
ALTER TABLE IF EXISTS public.trial_usage_tracking ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.trial_usage_tracking ADD COLUMN IF NOT EXISTS last_used_at timestamp without time zone;
ALTER TABLE IF EXISTS public.user_activity_logs ADD COLUMN IF NOT EXISTS resource character varying(255);
ALTER TABLE IF EXISTS public.user_activity_logs ADD COLUMN IF NOT EXISTS resource_id character varying;
ALTER TABLE IF EXISTS public.user_activity_logs ADD COLUMN IF NOT EXISTS details jsonb;
ALTER TABLE IF EXISTS public.user_activity_logs ADD COLUMN IF NOT EXISTS "timestamp" timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.user_cameras ADD COLUMN IF NOT EXISTS userid character varying(255);
ALTER TABLE IF EXISTS public.user_cameras ADD COLUMN IF NOT EXISTS cameraid character varying(255);
ALTER TABLE IF EXISTS public.user_cameras ADD COLUMN IF NOT EXISTS isprimary boolean DEFAULT false;
ALTER TABLE IF EXISTS public.user_consents ADD COLUMN IF NOT EXISTS granted boolean DEFAULT false;
ALTER TABLE IF EXISTS public.user_consents ADD COLUMN IF NOT EXISTS revoked_at timestamp without time zone;
ALTER TABLE IF EXISTS public.user_consents ADD COLUMN IF NOT EXISTS version character varying(50);
ALTER TABLE IF EXISTS public.user_consents ADD COLUMN IF NOT EXISTS legal_basis character varying(100);
ALTER TABLE IF EXISTS public.user_equipment ADD COLUMN IF NOT EXISTS firmware_current character varying(50);
ALTER TABLE IF EXISTS public.user_equipment ADD COLUMN IF NOT EXISTS firmware_track_key character varying(200);
ALTER TABLE IF EXISTS public.user_equipment ADD COLUMN IF NOT EXISTS firmware_auto_check_enabled boolean DEFAULT true;
ALTER TABLE IF EXISTS public.user_files ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE IF EXISTS public.user_files ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE IF EXISTS public.user_files ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.user_files ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.user_permission_overrides ADD COLUMN IF NOT EXISTS can_create boolean DEFAULT false;
ALTER TABLE IF EXISTS public.user_permission_overrides ADD COLUMN IF NOT EXISTS can_read boolean DEFAULT true;
ALTER TABLE IF EXISTS public.user_permission_overrides ADD COLUMN IF NOT EXISTS can_update boolean DEFAULT false;
ALTER TABLE IF EXISTS public.user_permission_overrides ADD COLUMN IF NOT EXISTS can_delete boolean DEFAULT false;
ALTER TABLE IF EXISTS public.user_permission_overrides ADD COLUMN IF NOT EXISTS granted_by character varying;
ALTER TABLE IF EXISTS public.user_preferences ADD COLUMN IF NOT EXISTS preferences jsonb;
ALTER TABLE IF EXISTS public.user_preferences ADD COLUMN IF NOT EXISTS notifications jsonb;
ALTER TABLE IF EXISTS public.user_preferences ADD COLUMN IF NOT EXISTS dashboard jsonb;
ALTER TABLE IF EXISTS public.user_roles ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.user_roles ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.user_shortcut_preferences ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS plan_id character varying;
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS started_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone;
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS auto_renew boolean DEFAULT true;
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS payment_method character varying(100);
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS amount numeric(10,2);
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS currency character varying(3) DEFAULT 'NOK'::character varying;
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS payment_method_id character varying(255);
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS cancelled_at timestamp without time zone;
ALTER TABLE IF EXISTS public.user_subscriptions ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS business_name text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS organization_number text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS category_id character varying;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS price_range text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS google_review_url text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS cultural_expertise text[];
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS rejection_reason text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS why_statement text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS how_statement text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS what_statement text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS is_test boolean DEFAULT false;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS settings jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS max_users integer DEFAULT 50;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS subscription_plan text DEFAULT 'standard'::text;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS api_access_enabled boolean DEFAULT false;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS api_subscription_start timestamp without time zone;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS api_subscription_end timestamp without time zone;
ALTER TABLE IF EXISTS public.vendors ADD COLUMN IF NOT EXISTS api_monthly_price numeric(10,2) DEFAULT 99.00;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS resolution character varying(50) DEFAULT '4K (3840x2160)'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS aspect_ratio character varying(20) DEFAULT '16:9'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS frame_rate integer DEFAULT 25;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS color_space character varying(50) DEFAULT 'Rec.709'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS google_drive_folder_path text;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS auto_sync_enabled boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS last_synced_at timestamp without time zone;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS render_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.virtual_studio_projects ADD COLUMN IF NOT EXISTS export_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS objects jsonb;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS lighting jsonb;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS environment jsonb;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS cameras jsonb;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS render_quality character varying(20) DEFAULT 'preview'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS render_resolution character varying(50) DEFAULT '1920x1080'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS samples_count integer DEFAULT 128;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS parent_scene_id uuid;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS is_template boolean DEFAULT false;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS view_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS render_time integer;
ALTER TABLE IF EXISTS public.virtual_studio_scenes ADD COLUMN IF NOT EXISTS last_rendered_at timestamp without time zone;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS enable_ai_recommendations boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS ai_suggestion_frequency character varying(20) DEFAULT 'moderate'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS auto_apply_suggestions boolean DEFAULT false;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS default_view character varying(20) DEFAULT '3d'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS show_light_cones boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS show_pattern_visualization boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS show_quality_metrics boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS default_render_quality character varying(20) DEFAULT 'preview'::character varying;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS enable_global_illumination boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS enable_aces boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS enable_asc_cdl boolean DEFAULT false;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS auto_save_enabled boolean DEFAULT true;
ALTER TABLE IF EXISTS public.virtual_studio_user_preferences ADD COLUMN IF NOT EXISTS auto_save_interval_seconds integer DEFAULT 60;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS service text;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS secret text;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS success_rate numeric(5,2) DEFAULT 0.00;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS total_events integer DEFAULT 0;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS last_triggered timestamp without time zone;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS last_error text;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS retry_count integer DEFAULT 0;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.webhooks ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.wedding_timeline_client_settings ADD COLUMN IF NOT EXISTS timeline_id character varying;
ALTER TABLE IF EXISTS public.wedding_timeline_client_settings ADD COLUMN IF NOT EXISTS client_id character varying;
ALTER TABLE IF EXISTS public.wedding_timeline_client_settings ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE IF EXISTS public.wedding_timeline_client_settings ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE IF EXISTS public.wedding_timeline_events ADD COLUMN IF NOT EXISTS timeline_id character varying;
ALTER TABLE IF EXISTS public.wedding_timeline_events ADD COLUMN IF NOT EXISTS event_time timestamp without time zone;
ALTER TABLE IF EXISTS public.wedding_timeline_events ADD COLUMN IF NOT EXISTS location character varying(500);
ALTER TABLE IF EXISTS public.wedding_timeline_events ADD COLUMN IF NOT EXISTS can_client_edit boolean DEFAULT false;
ALTER TABLE IF EXISTS public.workflow_states ADD COLUMN IF NOT EXISTS state character varying(100);
ALTER TABLE IF EXISTS public.workflow_states ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE IF EXISTS public.workflow_states ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now();
ALTER TABLE IF EXISTS public.worklog_entries ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE IF EXISTS public.worklog_entries ADD COLUMN IF NOT EXISTS audio_notes text;
ALTER TABLE IF EXISTS public.worklog_entries ADD COLUMN IF NOT EXISTS collaborators jsonb;
