import React from 'react';
import { Alert, Box, Button, Card, Chip, CircularProgress, Container, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, Stack, Switch, TextField, ThemeProvider, Typography } from '@mui/material';
import ArrowBack from '@mui/icons-material/ArrowBack';
import Add from '@mui/icons-material/Add';
import ContentCopy from '@mui/icons-material/ContentCopy';
import OpenInNew from '@mui/icons-material/OpenInNew';
import { useLocation } from 'wouter';
import { apiRequest } from '@/lib/queryClient';
import { ws, workspaceDarkTheme } from '@/components/workspace/workspaceTheme';
import type { CreatorHubBookingProfile, CreatorHubBookingService } from '@shared/creatorhub-enterprise-operations';

type Booking = { id: string; bookingReference: string; serviceName: string | null; customerName: string; customerEmail: string; startsAt: string; status: string };
type Window = { weekday: number; startTime: string; endTime: string; isActive: boolean };
const weekdays = ['Søn', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør'];
const panel = { bgcolor: ws.panel, border: `1px solid ${ws.border}`, borderRadius: `${ws.radius}px`, p: 2.5 };

export default function BookingAdminPage() {
  const [, navigate] = useLocation();
  const [loading, setLoading] = React.useState(true); const [saving, setSaving] = React.useState(false); const [message, setMessage] = React.useState(''); const [error, setError] = React.useState('');
  const [profile, setProfile] = React.useState<CreatorHubBookingProfile | null>(null); const [services, setServices] = React.useState<CreatorHubBookingService[]>([]); const [bookings, setBookings] = React.useState<Booking[]>([]); const [windows, setWindows] = React.useState<Window[]>([]); const [serviceOpen, setServiceOpen] = React.useState(false);
  const [form, setForm] = React.useState({ slug: '', businessName: '', headline: '', description: '', profession: '', timezone: 'Europe/Oslo', currency: 'NOK', locationLabel: '', contactEmail: '', minimumNoticeHours: 24, maximumAdvanceDays: 180, slotIntervalMinutes: 30, isPublished: false });
  const load = React.useCallback(async () => { setLoading(true); setError(''); try { const data = await apiRequest('/api/creatorhub/booking'); setProfile(data.profile || null); setServices(data.services || []); setBookings(data.bookings || []); const next = data.availability || []; setWindows(next.length ? next : [1,2,3,4,5].map((weekday) => ({ weekday, startTime: '09:00', endTime: '17:00', isActive: true }))); if (data.profile) setForm({ ...data.profile, headline: data.profile.headline || '', description: data.profile.description || '', profession: data.profile.profession || '', locationLabel: data.profile.locationLabel || '', contactEmail: data.profile.contactEmail || '' }); } catch (cause: any) { setError(cause?.message || 'Kunne ikke åpne bookingadministrasjonen.'); } finally { setLoading(false); } }, []);
  React.useEffect(() => { void load(); }, [load]);
  const saveProfile = async () => { setSaving(true); setError(''); try { const result = await apiRequest('/api/creatorhub/booking/profile', { method: 'PUT', body: { ...form, headline: form.headline || null, description: form.description || null, profession: form.profession || null, locationLabel: form.locationLabel || null, contactEmail: form.contactEmail || null, logoUrl: profile?.logoUrl || null, coverUrl: profile?.coverUrl || null } }); setProfile(result.profile); setMessage('Bookingsiden er lagret.'); } catch (cause: any) { setError(cause?.message || 'Kunne ikke lagre bookingsiden.'); } finally { setSaving(false); } };
  const saveAvailability = async () => { setSaving(true); try { await apiRequest('/api/creatorhub/booking/availability', { method: 'PUT', body: { windows } }); setMessage('Tilgjengeligheten er lagret.'); } catch (cause: any) { setError(cause?.message || 'Kunne ikke lagre tilgjengeligheten.'); } finally { setSaving(false); } };
  const publicUrl = profile ? `${window.location.origin}/book/${profile.slug}` : '';
  if (loading) return <ThemeProvider theme={workspaceDarkTheme}><Box sx={{ minHeight: '100vh', bgcolor: ws.bg, display: 'grid', placeItems: 'center' }}><CircularProgress sx={{ color: ws.accent }} /></Box></ThemeProvider>;
  return <ThemeProvider theme={workspaceDarkTheme}><Box sx={{ minHeight: '100vh', bgcolor: ws.bg, color: ws.text, py: 4 }}><Container maxWidth="lg">
    <Stack direction="row" alignItems="center" justifyContent="space-between" sx={{ mb: 3 }}><Stack direction="row" alignItems="center" spacing={1}><IconButton onClick={() => navigate('/profil')} sx={{ color: ws.textDim }}><ArrowBack /></IconButton><Box><Typography variant="h4" sx={{ fontWeight: 850 }}>Booking</Typography><Typography sx={{ color: ws.textDim }}>Enterprise-side, tjenester, tilgjengelighet og innkommende reservasjoner.</Typography></Box></Stack>{publicUrl && <Button href={publicUrl} target="_blank" startIcon={<OpenInNew />} variant="outlined">Åpne offentlig side</Button>}</Stack>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{message && <Alert severity="success" onClose={() => setMessage('')} sx={{ mb: 2 }}>{message}</Alert>}
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1.25fr .75fr' }, gap: 2 }}>
      <Card sx={panel}><Typography variant="h6" sx={{ fontWeight: 800, mb: 2 }}>Profil og offentlig side</Typography><Stack spacing={2}>
        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField fullWidth label="Firmanavn" value={form.businessName} onChange={(e) => setForm((f) => ({ ...f, businessName: e.target.value }))} /><TextField fullWidth label="Adressekode" value={form.slug} onChange={(e) => setForm((f) => ({ ...f, slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '-') }))} helperText={form.slug ? `/book/${form.slug}` : 'Minst 3 tegn'} /></Stack>
        <TextField label="Overskrift" value={form.headline} onChange={(e) => setForm((f) => ({ ...f, headline: e.target.value }))} /><TextField multiline minRows={3} label="Beskrivelse" value={form.description} onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField fullWidth label="Profesjon" value={form.profession} onChange={(e) => setForm((f) => ({ ...f, profession: e.target.value }))} /><TextField fullWidth label="Sted" value={form.locationLabel} onChange={(e) => setForm((f) => ({ ...f, locationLabel: e.target.value }))} /><TextField fullWidth label="Kontakt-e-post" value={form.contactEmail} onChange={(e) => setForm((f) => ({ ...f, contactEmail: e.target.value }))} /></Stack>
        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField fullWidth type="number" label="Minste varsel (timer)" value={form.minimumNoticeHours} onChange={(e) => setForm((f) => ({ ...f, minimumNoticeHours: Number(e.target.value) }))} /><TextField fullWidth type="number" label="Book fremover (dager)" value={form.maximumAdvanceDays} onChange={(e) => setForm((f) => ({ ...f, maximumAdvanceDays: Number(e.target.value) }))} /><TextField fullWidth label="Tidssone" value={form.timezone} onChange={(e) => setForm((f) => ({ ...f, timezone: e.target.value }))} /></Stack>
        <FormControlLabel control={<Switch checked={form.isPublished} onChange={(e) => setForm((f) => ({ ...f, isPublished: e.target.checked }))} />} label="Publiser bookingsiden" /><Button variant="contained" onClick={saveProfile} disabled={saving || form.slug.length < 3 || !form.businessName} sx={{ bgcolor: ws.accent, color: ws.accentContrast }}>{saving ? 'Lagrer…' : 'Lagre profil'}</Button>
        {publicUrl && <Button startIcon={<ContentCopy />} onClick={() => { void navigator.clipboard.writeText(publicUrl); setMessage('Lenken er kopiert.'); }}>{publicUrl}</Button>}
      </Stack></Card>
      <Stack spacing={2}><Card sx={panel}><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 1.5 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>Tjenester</Typography><Button startIcon={<Add />} onClick={() => setServiceOpen(true)}>Ny</Button></Stack><Stack spacing={1}>{services.map((service) => <Box key={service.id} sx={{ p: 1.25, borderRadius: 2, bgcolor: ws.panelAlt }}><Stack direction="row" justifyContent="space-between"><Typography sx={{ fontWeight: 750 }}>{service.name}</Typography><Chip size="small" label={`${service.priceAmount.toLocaleString('nb-NO')} ${profile?.currency || form.currency}`} /></Stack><Typography sx={{ color: ws.textDim, fontSize: 12 }}>{service.durationMinutes} min · {service.locationMode}</Typography></Box>)}{!services.length && <Typography sx={{ color: ws.textDim, fontSize: 13 }}>Legg til tjenesten kunden skal kunne bestille.</Typography>}</Stack></Card>
      <Card sx={panel}><Typography variant="h6" sx={{ fontWeight: 800, mb: 1.5 }}>Ukentlig tilgjengelighet</Typography><Stack spacing={1}>{windows.map((window, index) => <Stack key={`${window.weekday}-${index}`} direction="row" alignItems="center" spacing={1}><Chip label={weekdays[window.weekday]} sx={{ width: 56 }} /><TextField type="time" size="small" value={window.startTime} onChange={(e) => setWindows((all) => all.map((item, i) => i === index ? { ...item, startTime: e.target.value } : item))} /><TextField type="time" size="small" value={window.endTime} onChange={(e) => setWindows((all) => all.map((item, i) => i === index ? { ...item, endTime: e.target.value } : item))} /></Stack>)}</Stack><Button fullWidth sx={{ mt: 2 }} variant="outlined" onClick={saveAvailability}>Lagre tilgjengelighet</Button></Card></Stack>
    </Box>
    <Card sx={{ ...panel, mt: 2 }}><Typography variant="h6" sx={{ fontWeight: 800, mb: 1.5 }}>Bookinger</Typography><Stack spacing={1}>{bookings.map((booking) => <Stack key={booking.id} direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" sx={{ p: 1.25, bgcolor: ws.panelAlt, borderRadius: 2 }}><Box><Typography sx={{ fontWeight: 750 }}>{booking.customerName} · {booking.serviceName}</Typography><Typography sx={{ color: ws.textDim, fontSize: 12 }}>{new Date(booking.startsAt).toLocaleString('nb-NO')} · {booking.customerEmail}</Typography></Box><Chip label={booking.status} /></Stack>)}{!bookings.length && <Typography sx={{ color: ws.textDim }}>Ingen bookinger ennå.</Typography>}</Stack></Card>
    <ServiceDialog open={serviceOpen} onClose={() => setServiceOpen(false)} onCreated={async () => { setServiceOpen(false); await load(); }} />
  </Container></Box></ThemeProvider>;
}

function ServiceDialog({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: () => void }) {
  const [form, setForm] = React.useState({ name: '', description: '', durationMinutes: 60, priceAmount: 0, depositAmount: 0, bufferBeforeMinutes: 0, bufferAfterMinutes: 0, locationMode: 'provider', isActive: true, sortOrder: 0 }); const [error, setError] = React.useState(''); const [busy, setBusy] = React.useState(false);
  const submit = async () => { setBusy(true); setError(''); try { await apiRequest('/api/creatorhub/booking/services', { method: 'POST', body: { ...form, description: form.description || null } }); onCreated(); } catch (cause: any) { setError(cause?.message || 'Kunne ikke opprette tjenesten.'); } finally { setBusy(false); } };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Ny tjeneste</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Navn" value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} /><TextField label="Beskrivelse" multiline minRows={2} value={form.description} onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))} /><Stack direction="row" spacing={1}><TextField fullWidth type="number" label="Varighet (min)" value={form.durationMinutes} onChange={(e) => setForm((f) => ({ ...f, durationMinutes: Number(e.target.value) }))} /><TextField fullWidth type="number" label="Pris" value={form.priceAmount} onChange={(e) => setForm((f) => ({ ...f, priceAmount: Number(e.target.value) }))} /><TextField fullWidth type="number" label="Depositum" value={form.depositAmount} onChange={(e) => setForm((f) => ({ ...f, depositAmount: Number(e.target.value) }))} /></Stack>{error && <Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Avbryt</Button><Button variant="contained" onClick={submit} disabled={busy || !form.name}>{busy ? 'Oppretter…' : 'Opprett'}</Button></DialogActions></Dialog>;
}
