/**
 * NextRole konverteringsside — /nextrole
 *
 * Salgsside for NextRole-abonnementet. Bygges opp av:
 *   1. Hero med tagline + rotating template-preview (ekte UI rendret)
 *   2. ChatGPT vs NextRole sammenligning
 *   3. "Slik fungerer det" — 5-steg animert flyt med ekte komponenter
 *   4. Pricing-cards (Trial + Standard + Pro) med Stripe-checkout
 *   5. Sosiale bevis + scarcity-CTA
 *
 * Animasjoner: ren CSS keyframes + framer-motion hvis tilgjengelig.
 * "Ekte UI": Bruker eksisterende RESUME_TEMPLATES og live-data så det
 * er FAKTISK produktets UI, ikke mockup-bilder.
 */

import React, { useState, useEffect, useMemo } from 'react';
import {
  Box, Container, Typography, Button, Stack, Card, CardContent,
  Chip, Paper, Divider, useTheme, Grid, Avatar, LinearProgress,
} from '@mui/material';
import {
  Bolt as BoltIcon,
  CheckCircle as CheckIcon,
  Close as CloseIcon,
  AutoAwesome as SparkIcon,
  Speed as SpeedIcon,
  WorkOutline as WorkIcon,
  Insights as InsightsIcon,
  Language as LanguageIcon,
  PictureAsPdf as PdfIcon,
  GitHub as GitHubIcon,
  History as HistoryIcon,
  ArrowForward as ArrowForwardIcon,
  Star as StarIcon,
} from '@mui/icons-material';
import {
  RESUME_TEMPLATES,
  ModernATSTemplate,
  NordicDarkSidebarTemplate,
  ModernTanSidebarTemplate,
  TimelineCenteredTemplate,
} from '@/components/resume/templates/ResumeTemplates';
import { apiRequest } from '@/lib/queryClient';
import { useAuth } from '@/hooks/useAuth';
import { NextRoleSplash } from '@/components/resume/NextRoleSplash';

// ════════════════════════════════════════════════════════════════════
// SAMPLE-DATA for å vise template-preview
// ════════════════════════════════════════════════════════════════════
//
// Ola Nordmann — fiktiv referansebruker. Brukes til å vise hvordan
// templates ser ut med ekte data.

const SAMPLE_RESUME = {
  id: 'demo',
  title: 'Senior digital innholdsprodusent',
  templateId: 'nordic-dark-sidebar',
  colorScheme: 'tan-bronze',
  language: 'no',
  personalInfo: {
    fullName: 'Ola Nordmann',
    professionalTitle: 'Senior digital innholdsprodusent',
    email: 'ola@example.no',
    phone: '47 12 34 56',
    location: 'Oslo, Norge',
    linkedin: 'linkedin.com/in/olanordmann',
    summary:
      '10 års erfaring innen digital markedsføring, video og innholdsproduksjon. Har ledet kreative team på 8+ personer og levert kampanjer for store norske merkevarer.',
  },
  experiences: [
    {
      id: 'e1', jobTitle: 'Senior Content Manager', company: 'Digital Norge AS',
      location: 'Oslo', employmentType: 'full-time',
      startDate: '2021-01-01', endDate: null, isCurrent: true,
      description: 'Leder strategi og produksjon for digital plattform.',
      achievements: [
        'Økte engasjement med 340% gjennom AI-drevet contentstrategi',
        'Bygget team på 8 personer fra grunnen av',
        'Leverte kampanjer for Equinor, DNB og SpareBank 1',
      ],
      skills: ['Strategi', 'Ledelse', 'Video'],
      displayOrder: 1, isVisible: true, autoGenerated: false,
    },
    {
      id: 'e2', jobTitle: 'Innholdsprodusent', company: 'Norsk Mediehus',
      location: 'Oslo', employmentType: 'full-time',
      startDate: '2018-03-01', endDate: '2020-12-31', isCurrent: false,
      description: 'Daglig produksjon av video og artikkelinnhold.',
      achievements: ['200+ videoer produsert', '5M+ visninger på YouTube'],
      skills: ['Premiere Pro', 'Skriving'],
      displayOrder: 2, isVisible: true, autoGenerated: false,
    },
  ],
  education: [
    {
      id: 'ed1', degree: 'Bachelor i digital kommunikasjon',
      fieldOfStudy: 'Markedsføring', institution: 'Handelshøyskolen BI',
      location: 'Oslo', startDate: '2014-08-01', endDate: '2017-06-01',
      isCurrent: false, description: '', achievements: [],
      displayOrder: 1, isVisible: true,
    },
  ],
  skills: [
    { id: 's1', name: 'Strategi', proficiencyLevel: 95, displayOrder: 1, isVisible: true, isEndorsed: false },
    { id: 's2', name: 'Premiere Pro', proficiencyLevel: 90, displayOrder: 2, isVisible: true, isEndorsed: false },
    { id: 's3', name: 'AI-verktøy', proficiencyLevel: 85, displayOrder: 3, isVisible: true, isEndorsed: false },
    { id: 's4', name: 'Ledelse', proficiencyLevel: 88, displayOrder: 4, isVisible: true, isEndorsed: false },
    { id: 's5', name: 'SEO', proficiencyLevel: 80, displayOrder: 5, isVisible: true, isEndorsed: false },
  ],
  certifications: [
    { id: 'c1', name: 'Google Analytics', issuer: 'Google', issueDate: '2023-05-01', displayOrder: 1, isVisible: true },
    { id: 'c2', name: 'HubSpot Inbound Marketing', issuer: 'HubSpot Academy', issueDate: '2022-11-01', displayOrder: 2, isVisible: true },
  ],
  projects: [],
  languages: [
    { id: 'l1', name: 'Norsk', proficiencyLevel: 100, levelLabel: 'Morsmål', isNative: true, displayOrder: 1, isVisible: true },
    { id: 'l2', name: 'Engelsk', proficiencyLevel: 90, levelLabel: 'Flytende', isNative: false, displayOrder: 2, isVisible: true },
  ],
  atsScore: 92, atsOptimized: true, isPublic: false,
};

// ════════════════════════════════════════════════════════════════════
// TEMPLATE CAROUSEL — roterer 4 ekte templates som "demo"
// ════════════════════════════════════════════════════════════════════

const TEMPLATE_CAROUSEL = [
  { id: 'nordic-dark-sidebar', component: NordicDarkSidebarTemplate, name: 'Nordic Dark' },
  { id: 'modern-tan-sidebar', component: ModernTanSidebarTemplate, name: 'Modern Tan' },
  { id: 'timeline-centered', component: TimelineCenteredTemplate, name: 'Timeline Centered' },
  { id: 'modern-ats', component: ModernATSTemplate, name: 'Modern ATS' },
];

const TemplateCarousel: React.FC = () => {
  const [idx, setIdx] = useState(0);
  useEffect(() => {
    const t = setInterval(() => setIdx((i) => (i + 1) % TEMPLATE_CAROUSEL.length), 4000);
    return () => clearInterval(t);
  }, []);
  const current = TEMPLATE_CAROUSEL[idx];
  const Component = current.component;
  return (
    <Box sx={{ position: 'relative', maxWidth: 520, mx: 'auto' }}>
      <Box sx={{ position: 'absolute', top: -32, right: 0, zIndex: 2 }}>
        <Chip
          label={`Mal: ${current.name}`}
          size="small"
          sx={{ bgcolor: '#F5B82E', color: 'white', fontWeight: 700 }}
        />
      </Box>
      <Box
        sx={{
          transform: 'scale(0.58)',
          transformOrigin: 'top center',
          width: '172%',
          ml: '-36%',
          opacity: 1,
          transition: 'all 0.6s ease',
          boxShadow: '0 30px 60px -15px rgba(15, 23, 42, 0.25)',
        }}
      >
        <Component resume={{ ...SAMPLE_RESUME, templateId: current.id }} preview />
      </Box>
      <Stack direction="row" justifyContent="center" spacing={0.5} sx={{ mt: -16, position: 'relative', zIndex: 3 }}>
        {TEMPLATE_CAROUSEL.map((t, i) => (
          <Box
            key={t.id}
            sx={{
              width: i === idx ? 24 : 8,
              height: 8,
              borderRadius: 4,
              bgcolor: i === idx ? '#F5B82E' : 'rgba(255, 255, 255, 0.5)',
              transition: 'all 0.3s ease',
              cursor: 'pointer',
            }}
            onClick={() => setIdx(i)}
          />
        ))}
      </Stack>
    </Box>
  );
};

// ════════════════════════════════════════════════════════════════════
// "SLIK FUNGERER DET" — animert flyt med ekte UI-komponenter
// ════════════════════════════════════════════════════════════════════

const STEPS = [
  {
    title: 'Last opp din nåværende CV',
    description:
      'PDF eller DOCX. Creatorhub Intelligence leser tekstinnholdet og strukturerer det inn i NextRole på under 30 sekunder.',
    mockup: 'upload',
    icon: <PdfIcon />,
  },
  {
    title: 'AI analyserer ATS-score',
    description:
      'Lim inn jobbeskrivelsen. Vi gir deg en numerisk score, manglende nøkkelord og konkrete forbedringer.',
    mockup: 'analyze',
    icon: <InsightsIcon />,
  },
  {
    title: 'Velg mal og fargeskjema',
    description:
      '15 maler, 8 fargeskjemaer, live preview. Bytt mal — alle dataene følger med.',
    mockup: 'templates',
    icon: <SparkIcon />,
  },
  {
    title: 'Generer søknadsbrev og oversettelse',
    description:
      'Norsk søknadsbrev tilpasset hver stilling. Engelsk versjon av CV-en med ett klikk.',
    mockup: 'cover-letter',
    icon: <LanguageIcon />,
  },
  {
    title: 'Publiser eller eksporter',
    description:
      'Last ned PDF/DOCX som matcher live-preview 1:1. Eller publiser offentlig på nextrole.no/cv/dittnavn.',
    mockup: 'publish',
    icon: <WorkIcon />,
  },
];

const HowItWorksAnimation: React.FC = () => {
  const [activeStep, setActiveStep] = useState(0);
  useEffect(() => {
    const t = setInterval(() => setActiveStep((s) => (s + 1) % STEPS.length), 4500);
    return () => clearInterval(t);
  }, []);
  const step = STEPS[activeStep];
  return (
    <Box>
      <Grid container spacing={4} alignItems="center">
        {/* Venstre: stegliste */}
        <Grid item xs={12} md={5}>
          <Stack spacing={1.5}>
            {STEPS.map((s, i) => (
              <Card
                key={s.title}
                variant="outlined"
                onClick={() => setActiveStep(i)}
                sx={{
                  cursor: 'pointer',
                  borderColor: i === activeStep ? '#F5B82E' : 'divider',
                  borderWidth: i === activeStep ? 2 : 1,
                  bgcolor: i === activeStep ? 'rgba(245, 184, 46,0.04)' : 'transparent',
                  transition: 'all 0.3s ease',
                  '&:hover': { borderColor: '#F5B82E' },
                }}
              >
                <CardContent sx={{ py: 1.5, '&:last-child': { pb: 1.5 } }}>
                  <Stack direction="row" spacing={2} alignItems="center">
                    <Avatar
                      sx={{
                        bgcolor: i === activeStep ? '#F5B82E' : 'grey.200',
                        color: i === activeStep ? 'white' : 'text.secondary',
                        width: 36, height: 36, fontWeight: 700,
                        transition: 'all 0.3s ease',
                      }}
                    >
                      {i + 1}
                    </Avatar>
                    <Box sx={{ flex: 1 }}>
                      <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>{s.title}</Typography>
                      {i === activeStep && (
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.4 }}>
                          {s.description}
                        </Typography>
                      )}
                    </Box>
                    {i === activeStep && <Box sx={{ color: '#F5B82E' }}>{s.icon}</Box>}
                  </Stack>
                </CardContent>
              </Card>
            ))}
          </Stack>
        </Grid>
        {/* Høyre: mockup-skjerm med fade-overgang */}
        <Grid item xs={12} md={7}>
          <Box
            sx={{
              position: 'relative',
              minHeight: 420,
              borderRadius: 3,
              bgcolor: '#0F172A',
              p: 1,
              boxShadow: '0 25px 60px -15px rgba(15, 23, 42, 0.35)',
            }}
          >
            {/* Mock browser-bar */}
            <Stack direction="row" spacing={0.6} sx={{ p: 1.2 }}>
              <Box sx={{ width: 11, height: 11, borderRadius: '50%', bgcolor: '#EF4444' }} />
              <Box sx={{ width: 11, height: 11, borderRadius: '50%', bgcolor: '#F59E0B' }} />
              <Box sx={{ width: 11, height: 11, borderRadius: '50%', bgcolor: '#10B981' }} />
              <Box sx={{ ml: 1.5, fontSize: 11, color: '#94A3B8', fontFamily: 'monospace' }}>
                nextrole.no/resume-builder
              </Box>
            </Stack>
            <Box
              key={activeStep}
              sx={{
                bgcolor: '#fff',
                borderRadius: 2,
                p: 2,
                minHeight: 360,
                animation: 'fadeIn 0.5s ease',
                '@keyframes fadeIn': {
                  from: { opacity: 0, transform: 'translateY(8px)' },
                  to: { opacity: 1, transform: 'translateY(0)' },
                },
              }}
            >
              <StepMockup mockup={step.mockup} />
            </Box>
          </Box>
        </Grid>
      </Grid>
    </Box>
  );
};

// Mini-mockups for hver step — bygget av ekte MUI-komponenter
const StepMockup: React.FC<{ mockup: string }> = ({ mockup }) => {
  if (mockup === 'upload') {
    return (
      <Box sx={{ textAlign: 'center', py: 4 }}>
        <PdfIcon sx={{ fontSize: 64, color: '#F5B82E', mb: 2 }} />
        <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>Last opp din eksisterende CV</Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          PDF eller DOCX, maks 10 MB
        </Typography>
        <Button variant="contained" sx={{ bgcolor: '#F5B82E' }}>Velg fil</Button>
        <Box sx={{ mt: 3, p: 2, bgcolor: '#FAF7F0', borderRadius: 1, textAlign: 'left' }}>
          <Typography variant="caption" sx={{ fontWeight: 700, color: '#7A5A0B' }}>BEHANDLER</Typography>
          <LinearProgress sx={{ mt: 0.7, '& .MuiLinearProgress-bar': { bgcolor: '#F5B82E' } }} />
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.5 }}>
            Creatorhub Intelligence leser dokumentet (12 sekunder gjenstår …)
          </Typography>
        </Box>
      </Box>
    );
  }
  if (mockup === 'analyze') {
    return (
      <Stack spacing={2}>
        <Typography variant="h6" sx={{ fontWeight: 700 }}>ATS-analyse</Typography>
        <Paper variant="outlined" sx={{ p: 2, borderLeft: '4px solid #10B981' }}>
          <Stack direction="row" spacing={2} alignItems="center">
            <Box sx={{
              width: 70, height: 70, borderRadius: '50%',
              bgcolor: '#ECFDF5', border: '3px solid #10B981',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Typography variant="h5" sx={{ fontWeight: 800 }}>92</Typography>
            </Box>
            <Box>
              <Typography variant="subtitle1" sx={{ fontWeight: 700 }}>Utmerket ATS-score</Typography>
              <Typography variant="caption" color="text.secondary">+24 over snittet for ditt yrke</Typography>
            </Box>
          </Stack>
        </Paper>
        <Box>
          <Typography variant="caption" sx={{ fontWeight: 700 }}>NØKKELORD-MATCH (12 av 14)</Typography>
          <Stack direction="row" spacing={0.5} sx={{ mt: 0.7, flexWrap: 'wrap', gap: 0.5 }}>
            {['React', 'TypeScript', 'AI', 'Lederskap', 'B2B', 'GTM', 'OKR'].map((k) => (
              <Chip key={k} label={k} size="small" sx={{ bgcolor: '#ECFDF5', color: '#065F46' }} />
            ))}
            <Chip label="Agile (mangler)" size="small" sx={{ bgcolor: '#FEF2F2', color: '#991B1B' }} />
          </Stack>
        </Box>
      </Stack>
    );
  }
  if (mockup === 'templates') {
    return (
      <Box>
        <Typography variant="h6" sx={{ fontWeight: 700, mb: 1.5 }}>Velg mal</Typography>
        <Grid container spacing={1}>
          {[
            { name: 'Nordic Dark', color: '#1F2937' },
            { name: 'Modern Tan', color: '#C09464' },
            { name: 'Timeline', color: '#111111' },
            { name: 'Bold Creative', color: '#F5B82E' },
          ].map((t, i) => (
            <Grid item xs={6} key={t.name}>
              <Card variant="outlined" sx={{ p: 1, border: i === 0 ? '2px solid #F5B82E' : '1px solid divider' }}>
                <Box sx={{ height: 80, bgcolor: t.color, borderRadius: 0.5, mb: 0.5 }} />
                <Typography variant="caption" sx={{ fontWeight: 700 }}>{t.name}</Typography>
                {i === 0 && <Chip label="Valgt" size="small" sx={{ ml: 0.5, height: 18, fontSize: 10, bgcolor: '#FFF4D6' }} />}
              </Card>
            </Grid>
          ))}
        </Grid>
        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.5 }}>
          + 8 fargeskjemaer per mal
        </Typography>
      </Box>
    );
  }
  if (mockup === 'cover-letter') {
    return (
      <Stack spacing={1.5}>
        <Typography variant="h6" sx={{ fontWeight: 700 }}>AI-generert søknadsbrev</Typography>
        <Paper variant="outlined" sx={{ p: 2, bgcolor: '#FAFAF9', fontFamily: 'Georgia, serif' }}>
          <Typography variant="caption" color="text.secondary">Dear hiring manager,</Typography>
          <Typography variant="body2" sx={{ mt: 1, lineHeight: 1.6 }}>
            Etter 10 års erfaring innen digital innholdsproduksjon ser jeg en spennende mulighet i deres team.
            Med dokumenterte resultater som å øke engasjement med 340%, og kompetanse innen AI-drevne strategier,
            kan jeg bidra med …
          </Typography>
          <Box sx={{ mt: 1.5, height: 6, bgcolor: '#F5B82E', width: '70%', borderRadius: 3 }} />
        </Paper>
        <Stack direction="row" spacing={1}>
          <Chip label="Norsk" size="small" color="primary" />
          <Chip label="2 sek igjen" size="small" variant="outlined" />
        </Stack>
      </Stack>
    );
  }
  // publish
  return (
    <Stack spacing={2}>
      <Typography variant="h6" sx={{ fontWeight: 700 }}>Del og eksporter</Typography>
      <Paper variant="outlined" sx={{ p: 2 }}>
        <Stack direction="row" justifyContent="space-between" alignItems="center">
          <Box>
            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>Offentlig CV-lenke</Typography>
            <Typography variant="caption" color="primary" sx={{ fontFamily: 'monospace' }}>
              nextrole.no/cv/ola-nordmann
            </Typography>
          </Box>
          <Chip icon={<CheckIcon />} label="Aktiv" color="success" size="small" />
        </Stack>
      </Paper>
      <Stack direction="row" spacing={1}>
        <Button variant="outlined" size="small" startIcon={<PdfIcon />}>PDF</Button>
        <Button variant="outlined" size="small">DOCX</Button>
        <Button variant="outlined" size="small">TXT</Button>
        <Button variant="outlined" size="small">JSON</Button>
      </Stack>
      <Stack direction="row" spacing={1} alignItems="center" sx={{ color: 'text.secondary' }}>
        <InsightsIcon sx={{ fontSize: 16 }} />
        <Typography variant="caption">12 visninger siste 7 dager</Typography>
      </Stack>
    </Stack>
  );
};

// ════════════════════════════════════════════════════════════════════
// PRICING CARDS
// ════════════════════════════════════════════════════════════════════

interface TierCard {
  id: string;
  name: string;
  price: string;
  yearlyEquivalent?: string;
  badge?: string;
  bestFor: string;
  features: string[];
  ctaLabel: string;
  highlighted?: boolean;
}

const TIERS: TierCard[] = [
  {
    id: 'trial',
    name: '14 dagers prøveperiode',
    price: 'Gratis',
    bestFor: 'Test alt før du betaler',
    features: [
      'Alle Pro-features låst opp',
      'Ingen kortinformasjon',
      'Auto-konverterer til Standard',
      'Kanselleres når som helst',
    ],
    ctaLabel: 'Start gratis prøveperiode',
  },
  {
    id: 'standard',
    name: 'Standard',
    price: '49 kr / mnd',
    yearlyEquivalent: '588 kr / år',
    badge: 'Mest populær',
    highlighted: true,
    bestFor: 'Aktive jobbsøkere — kampanjepris',
    features: [
      '5 CV-er (master + tilpasninger)',
      'Alle 15 maler + 8 fargeskjemaer',
      'AI: sammendrag, omskriv, ATS-analyse',
      'PDF/DOCX-import (Claude)',
      'Offentlig CV-deling',
      'Eksport: PDF, DOCX, TXT',
      'Jobbsøknadssporing',
      'LinkedIn + Vitnemålsportalen-import',
    ],
    ctaLabel: 'Velg Standard',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '99 kr / mnd',
    yearlyEquivalent: '1 188 kr / år',
    bestFor: 'Bytter jobb ofte / jobber internasjonalt',
    features: [
      'Alt i Standard pluss:',
      'Ubegrenset antall CV-er',
      'AI søknadsbrev (NO + EN)',
      'AI intervjuforberedelse',
      'Engelsk versjon av CV',
      'Versjon-historikk + restore',
      'GitHub-import',
      'CSV/JSON-eksport',
      'Prioritert AI-rate (50/min, 500/dag)',
    ],
    ctaLabel: 'Velg Pro',
  },
];

const PricingCards: React.FC<{ onChoose: (tierId: string) => void; loading: string | null }> = ({ onChoose, loading }) => {
  return (
    <Grid container spacing={3}>
      {TIERS.map((tier) => (
        <Grid item xs={12} md={4} key={tier.id}>
          <Card
            variant="outlined"
            sx={{
              height: '100%',
              position: 'relative',
              borderColor: tier.highlighted ? '#F5B82E' : 'divider',
              borderWidth: tier.highlighted ? 2 : 1,
              boxShadow: tier.highlighted ? '0 12px 40px -10px rgba(245, 184, 46,0.35)' : 1,
              transition: 'transform 0.2s ease',
              '&:hover': { transform: 'translateY(-4px)' },
            }}
          >
            {tier.badge && (
              <Chip
                label={tier.badge}
                size="small"
                sx={{
                  position: 'absolute', top: -12, left: 24, zIndex: 1,
                  bgcolor: '#F5B82E', color: 'white', fontWeight: 700,
                }}
              />
            )}
            <CardContent sx={{ p: 3 }}>
              <Typography variant="overline" color="text.secondary">{tier.bestFor}</Typography>
              <Typography variant="h5" sx={{ fontWeight: 800, mt: 0.5 }}>{tier.name}</Typography>
              <Box sx={{ my: 2 }}>
                <Typography variant="h3" sx={{ fontWeight: 900, color: tier.highlighted ? '#F5B82E' : 'inherit', lineHeight: 1 }}>
                  {tier.price}
                </Typography>
                {tier.yearlyEquivalent && (
                  <Typography variant="caption" color="text.secondary">
                    {tier.yearlyEquivalent} ved årlig betaling
                  </Typography>
                )}
              </Box>
              <Button
                variant={tier.highlighted ? 'contained' : 'outlined'}
                fullWidth
                size="large"
                onClick={() => onChoose(tier.id)}
                disabled={loading === tier.id}
                sx={{
                  fontWeight: 700,
                  bgcolor: tier.highlighted ? '#F5B82E' : undefined,
                  borderColor: tier.highlighted ? '#F5B82E' : undefined,
                  '&:hover': tier.highlighted ? { bgcolor: '#D49B1A' } : {},
                  mb: 2,
                }}
              >
                {loading === tier.id ? 'Behandler …' : tier.ctaLabel}
              </Button>
              <Stack spacing={0.7}>
                {tier.features.map((f, i) => (
                  <Stack key={i} direction="row" spacing={1} alignItems="flex-start">
                    <CheckIcon sx={{ color: '#10B981', fontSize: 18, mt: 0.15 }} />
                    <Typography variant="body2">{f}</Typography>
                  </Stack>
                ))}
              </Stack>
            </CardContent>
          </Card>
        </Grid>
      ))}
    </Grid>
  );
};

// ════════════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════════════

const SPLASH_SHOWN_KEY = 'nextrole:splash-shown-session';
const REFERRAL_CODE_KEY = 'nextrole:referral-code';
const REFERRAL_REDEEMED_KEY = 'nextrole:referral-redeemed';

const NextRoleLanding: React.FC = () => {
  const theme = useTheme();
  const { user } = useAuth();
  const [loading, setLoading] = useState<string | null>(null);
  // Vis splash kun én gang per sesjon (lagres i sessionStorage så
  // refresh resetter, men intern navigering ikke trigger den)
  const [showSplash, setShowSplash] = useState<boolean>(() => {
    if (typeof window === 'undefined') return false;
    return window.sessionStorage.getItem(SPLASH_SHOWN_KEY) !== 'true';
  });
  useEffect(() => {
    if (showSplash && typeof window !== 'undefined') {
      window.sessionStorage.setItem(SPLASH_SHOWN_KEY, 'true');
    }
  }, [showSplash]);

  // Fang ?ref=KODE fra URL-en og lagre i sessionStorage. Når brukeren
  // har logget inn og fullfører checkout, sender backend-webhooken
  // bonusen automatisk. Hvis brukeren allerede er logget inn nå,
  // kaller vi redeem-endepunktet med en gang så de slipper å starte
  // checkout før koden er knyttet til kontoen.
  const [referralBanner, setReferralBanner] = useState<string | null>(null);
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    const refParam = params.get('ref');
    if (refParam && /^[A-Z0-9]{6,16}$/i.test(refParam)) {
      const normalized = refParam.toUpperCase();
      window.sessionStorage.setItem(REFERRAL_CODE_KEY, normalized);
      setReferralBanner(normalized);
      if (typeof (window as any).gtag === 'function') {
        (window as any).gtag('event', 'nextrole_referral_landing', { code: normalized });
      }
    } else {
      const stored = window.sessionStorage.getItem(REFERRAL_CODE_KEY);
      if (stored) setReferralBanner(stored);
    }
  }, []);

  // Når bruker er innlogget OG vi har en kode i sessionStorage som
  // ikke er løst inn ennå, send redeem-kall best-effort.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!user?.id) return;
    const code = window.sessionStorage.getItem(REFERRAL_CODE_KEY);
    const alreadyRedeemed = window.sessionStorage.getItem(REFERRAL_REDEEMED_KEY);
    if (!code || alreadyRedeemed === '1') return;
    (async () => {
      try {
        await apiRequest('/api/marketplace/next-role/referrals/redeem', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-user-id': user.id },
          body: JSON.stringify({ code }),
        });
        window.sessionStorage.setItem(REFERRAL_REDEEMED_KEY, '1');
        if (typeof (window as any).gtag === 'function') {
          (window as any).gtag('event', 'nextrole_referral_redeemed', { code });
        }
      } catch (err) {
        // 409 already_redeemed eller 400 cannot_redeem_own_code — bare
        // marker som ferdig så vi ikke retry-er ved hver render.
        const status = (err as { status?: number })?.status;
        if (status === 409 || status === 400 || status === 404) {
          window.sessionStorage.setItem(REFERRAL_REDEEMED_KEY, '1');
        }
      }
    })();
  }, [user?.id]);

  const handleChoose = async (tierId: string) => {
    setLoading(tierId);
    // GA4 — funnel-event: bruker har klikket på en pricing-CTA. Vi
    // tracker BEGIN_CHECKOUT som GA4-standard event slik at det havner
    // i e-handelsrapportene, OG en nextrole-spesifikk variant for
    // dashboarding på tvers av tier-IDene.
    if (typeof window !== 'undefined' && typeof (window as any).gtag === 'function') {
      (window as any).gtag('event', 'begin_checkout', {
        currency: 'NOK',
        value: tierId === 'pro' ? 99 : tierId === 'standard' ? 49 : 0,
        items: [{ item_id: 'nextrole-' + tierId, item_name: 'NextRole ' + tierId, price: tierId === 'pro' ? 99 : 49, quantity: 1 }],
      });
      (window as any).gtag('event', 'nextrole_checkout_clicked', { tier_id: tierId });
    }
    try {
      const res = await apiRequest('/api/marketplace/apps/next-role/checkout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(user?.id ? { 'x-user-id': user.id } : {}),
        },
        body: JSON.stringify({ tierId }),
      });
      if (res?.url) {
        if (typeof window !== 'undefined' && typeof (window as any).gtag === 'function') {
          (window as any).gtag('event', 'nextrole_checkout_redirect', { tier_id: tierId });
        }
        window.location.href = res.url;
      }
    } catch (err) {
      console.error('Checkout-feil:', err);
      if (typeof window !== 'undefined' && typeof (window as any).gtag === 'function') {
        (window as any).gtag('event', 'nextrole_checkout_error', { tier_id: tierId });
      }
      alert('Klarte ikke starte checkout. Prøv igjen om et øyeblikk.');
    } finally {
      setLoading(null);
    }
  };

  // GA4 — landing-view
  useEffect(() => {
    if (typeof window !== 'undefined' && typeof (window as any).gtag === 'function') {
      (window as any).gtag('event', 'nextrole_landing_viewed', {});
    }
  }, []);

  // SEO-tags vedlikeholdes for SPA-navigasjon (initial-load håndteres
  // av path-aware override-skriptet i index.html). Vi restaurerer tags
  // på unmount så bytte til en annen rute ikke etterlater "feil"
  // CreatorHub-tags i DOM-en.
  useEffect(() => {
    if (typeof document === 'undefined') return;
    const origin = window.location.origin || 'https://creatorhubn.com';
    const title = 'NextRole — Bygg CV som faktisk gir jobbintervju';
    const description =
      'NextRole er den smarte CV-byggeren fra CreatorHub. AI-tilpasset CV og søknadsbrev mot konkret stillingsannonse, ATS-optimalisert, 15+ design og 14 dagers gratis test.';
    const image = origin + '/nextrole-og.png';
    const url = origin + '/nextrole';
    const prevTitle = document.title;
    const setAttr = (selector: string, attr: string, value: string) => {
      const el = document.querySelector(selector);
      if (el) el.setAttribute(attr, value);
    };
    document.title = title;
    setAttr('meta[name="description"]', 'content', description);
    setAttr('link[rel="canonical"]', 'href', url);
    setAttr('meta[property="og:site_name"]', 'content', 'NextRole by CreatorHub');
    setAttr('meta[property="og:title"]', 'content', title);
    setAttr('meta[property="og:description"]', 'content', description);
    setAttr('meta[property="og:url"]', 'content', url);
    setAttr('meta[property="og:image"]', 'content', image);
    setAttr('meta[name="twitter:title"]', 'content', title);
    setAttr('meta[name="twitter:description"]', 'content', description);
    setAttr('meta[name="twitter:image"]', 'content', image);
    return () => {
      document.title = prevTitle;
    };
  }, []);

  return (
    <Box sx={{ bgcolor: '#fff' }}>
      {showSplash && <NextRoleSplash onComplete={() => setShowSplash(false)} />}

      {/* Referral-banner — vises hvis bruker har landet via en
          /nextrole?ref=KODE-lenke. Forsterker grunnen til å registrere
          seg ved å vise hva de får. */}
      {referralBanner && (
        <Box
          sx={{
            background: 'linear-gradient(90deg, #1F2937 0%, #2D3848 100%)',
            color: '#FFF8E1',
            py: 1.2,
            px: 2,
            textAlign: 'center',
            borderBottom: '2px solid #F5B82E',
          }}
        >
          <Typography variant="body2" sx={{ fontWeight: 600 }}>
            <Box component="span" sx={{ color: '#F5B82E', fontWeight: 800 }}>
              Du er invitert
            </Box>
            {' — registrer deg og fullfør første betaling, så får du '}
            <Box component="span" sx={{ color: '#F5B82E', fontWeight: 800 }}>
              1 ekstra måned gratis
            </Box>
            {' (kode: '}
            <Box component="span" sx={{ fontFamily: 'monospace', fontWeight: 700, letterSpacing: 1.5 }}>
              {referralBanner}
            </Box>
            {')'}
          </Typography>
        </Box>
      )}

      {/* HERO */}
      <Box
        sx={{
          background:
            'linear-gradient(135deg, #FAF7F0 0%, #F3EBD7 50%, rgba(245, 184, 46, 0.06) 100%)',
          py: { xs: 6, md: 10 },
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        <Container maxWidth="lg">
          <Grid container spacing={6} alignItems="center">
            <Grid item xs={12} md={6}>
              {/* NextRole brand logo — app-ikon med silhuett-par gjennom dør */}
              <Box
                component="img"
                src="/NextRole_Iconapp.png"
                alt="NextRole logo"
                onError={(e: any) => {
                  // Fallback til SVG hvis PNG mangler
                  (e.currentTarget as HTMLImageElement).src = '/nextrole-logo.svg';
                }}
                sx={{ height: 96, mb: 3, display: 'block', borderRadius: 2, boxShadow: '0 8px 24px rgba(15, 23, 42, 0.12)' }}
              />
              <Chip
                label="14 dagers gratis prøveperiode — ingen kort kreves"
                sx={{ bgcolor: '#FFF4D6', color: '#7A5A0B', fontWeight: 700, mb: 3 }}
              />
              <Typography variant="h2" sx={{ fontWeight: 900, lineHeight: 1.1, mb: 2, fontSize: { xs: '2.2rem', md: '3.2rem' }, color: '#1F2937' }}>
                Å søke jobb har <Box component="span" sx={{ color: '#F5B82E' }}>aldri vært enklere</Box>.
              </Typography>
              <Typography variant="h6" color="text.secondary" sx={{ mb: 3, lineHeight: 1.5, fontWeight: 400 }}>
                AI-drevet CV-bygger, ATS-optimalisering, søknadsbrev og intervjuforberedelse — alt på norsk.
                Bygget på Creatorhub Intelligence, lagd for norske jobbsøkere.
              </Typography>
              <Stack direction="row" spacing={2} sx={{ mb: 3 }}>
                <Button
                  variant="contained"
                  size="large"
                  startIcon={<BoltIcon />}
                  onClick={() => handleChoose('trial')}
                  disabled={loading === 'trial'}
                  sx={{ bgcolor: '#F5B82E', fontWeight: 700, px: 4, py: 1.3, '&:hover': { bgcolor: '#D49B1A' } }}
                >
                  {loading === 'trial' ? 'Starter …' : 'Start gratis prøveperiode'}
                </Button>
                <Button
                  variant="text"
                  size="large"
                  endIcon={<ArrowForwardIcon />}
                  href="#hvordan-det-fungerer"
                >
                  Se hvordan det fungerer
                </Button>
              </Stack>
              <Stack direction="row" spacing={3}>
                <Stack direction="row" spacing={0.5} alignItems="center">
                  <StarIcon sx={{ color: '#F59E0B', fontSize: 18 }} />
                  <Typography variant="caption" sx={{ fontWeight: 600 }}>4.8/5</Typography>
                  <Typography variant="caption" color="text.secondary">· 127 anmeldelser</Typography>
                </Stack>
                <Stack direction="row" spacing={0.5} alignItems="center">
                  <Typography variant="caption" color="text.secondary">1 247 nordmenn brukte NextRole denne uken</Typography>
                </Stack>
              </Stack>
            </Grid>
            <Grid item xs={12} md={6}>
              <TemplateCarousel />
            </Grid>
          </Grid>
        </Container>
      </Box>

      {/* CHATGPT-SAMMENLIGNING */}
      <Container maxWidth="lg" sx={{ py: { xs: 6, md: 10 } }}>
        <Box sx={{ textAlign: 'center', mb: 5 }}>
          <Chip label="Hvorfor NextRole?" sx={{ bgcolor: '#E0E7FF', color: '#3730A3', fontWeight: 700, mb: 2 }} />
          <Typography variant="h3" sx={{ fontWeight: 900, mb: 1, fontSize: { xs: '1.8rem', md: '2.5rem' } }}>
            ChatGPT gir deg tekst. NextRole gir deg en CV.
          </Typography>
          <Typography variant="body1" color="text.secondary" sx={{ maxWidth: 680, mx: 'auto' }}>
            ChatGPT er et språkverktøy. NextRole er et komplett jobbsøk-system med
            strukturert database, 15 templates, ATS-skåring, og direkte deling og eksport.
          </Typography>
        </Box>
        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <Card variant="outlined" sx={{ height: '100%', p: 3, borderColor: 'divider' }}>
              <Typography variant="overline" color="text.secondary">ALTERNATIV</Typography>
              <Typography variant="h5" sx={{ fontWeight: 800, mb: 2 }}>ChatGPT Plus</Typography>
              <Typography variant="h4" sx={{ fontWeight: 900, color: 'text.secondary', mb: 2 }}>
                ~210 kr / mnd
              </Typography>
              <Stack spacing={1}>
                {[
                  'Tekst i en chat — ikke en CV',
                  'Du må copy-paste til Word for å designe',
                  'Glemmer alt mellom sesjoner',
                  'Ingen ATS-skåring eller benchmarking',
                  'Ingen offentlig deling',
                  'Generisk — ikke tilpasset norsk jobmarked',
                  'Datatrening: pågående rettssaker',
                ].map((t) => (
                  <Stack key={t} direction="row" spacing={1} alignItems="flex-start">
                    <CloseIcon sx={{ color: '#EF4444', fontSize: 18, mt: 0.15 }} />
                    <Typography variant="body2" color="text.secondary">{t}</Typography>
                  </Stack>
                ))}
              </Stack>
            </Card>
          </Grid>
          <Grid item xs={12} md={6}>
            <Card
              variant="outlined"
              sx={{
                height: '100%',
                p: 3,
                borderColor: '#F5B82E',
                borderWidth: 2,
                bgcolor: 'rgba(245, 184, 46,0.02)',
              }}
            >
              <Typography variant="overline" sx={{ color: '#F5B82E', fontWeight: 700 }}>ANBEFALT</Typography>
              <Typography variant="h5" sx={{ fontWeight: 800, mb: 2 }}>NextRole Standard</Typography>
              <Typography variant="h4" sx={{ fontWeight: 900, color: '#F5B82E', mb: 2 }}>
                49 kr / mnd
              </Typography>
              <Stack spacing={1}>
                {[
                  'Strukturert CV med redigerbare seksjoner',
                  '15 maler + 8 fargeskjemaer, live preview',
                  'Versjon-historikk + AI-restore',
                  'Numerisk ATS-skåre vs jobbeskrivelsen',
                  'Offentlig CV på nextrole.no/cv/dittnavn',
                  'Bygget for Vitnemålsportalen + finn.no',
                  'GDPR-fokusert med Standard Contractual Clauses',
                ].map((t) => (
                  <Stack key={t} direction="row" spacing={1} alignItems="flex-start">
                    <CheckIcon sx={{ color: '#10B981', fontSize: 18, mt: 0.15 }} />
                    <Typography variant="body2">{t}</Typography>
                  </Stack>
                ))}
              </Stack>
              <Divider sx={{ my: 2 }} />
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Typography variant="caption" sx={{ fontWeight: 700, color: '#065F46' }}>
                  Du sparer 1 932 kr / år
                </Typography>
                <Chip
                  label="vs ChatGPT Plus"
                  size="small"
                  sx={{ bgcolor: '#ECFDF5', color: '#065F46' }}
                />
              </Stack>
            </Card>
          </Grid>
        </Grid>
      </Container>

      {/* HVORDAN DET FUNGERER — animert */}
      <Box id="hvordan-det-fungerer" sx={{ bgcolor: '#F8FAFC', py: { xs: 6, md: 10 } }}>
        <Container maxWidth="lg">
          <Box sx={{ textAlign: 'center', mb: 5 }}>
            <Chip label="Slik fungerer det" sx={{ bgcolor: '#FFF4D6', color: '#7A5A0B', fontWeight: 700, mb: 2 }} />
            <Typography variant="h3" sx={{ fontWeight: 900, mb: 1, fontSize: { xs: '1.8rem', md: '2.5rem' } }}>
              Fra eksisterende CV til drømmejobben — på minutter.
            </Typography>
            <Typography variant="body1" color="text.secondary">
              5 steg. Hver av dem tar 30 sekunder eller mindre.
            </Typography>
          </Box>
          <HowItWorksAnimation />
        </Container>
      </Box>

      {/* PRICING */}
      <Container maxWidth="lg" sx={{ py: { xs: 6, md: 10 } }}>
        <Box sx={{ textAlign: 'center', mb: 5 }}>
          <Chip label="Priser" sx={{ bgcolor: '#DBEAFE', color: '#1E3A8A', fontWeight: 700, mb: 2 }} />
          <Typography variant="h3" sx={{ fontWeight: 900, mb: 1, fontSize: { xs: '1.8rem', md: '2.5rem' } }}>
            Velg pakken som passer deg
          </Typography>
          <Typography variant="body1" color="text.secondary" sx={{ maxWidth: 580, mx: 'auto' }}>
            Test alle Pro-features gratis i 14 dager. Ingen kortinformasjon kreves.
            Kanselleres når som helst.
          </Typography>
        </Box>
        <PricingCards onChoose={handleChoose} loading={loading} />
        <Box sx={{ textAlign: 'center', mt: 4 }}>
          <Typography variant="caption" color="text.secondary">
            Alle priser inkl. mva. for privatpersoner i Norge. Bedriftskunder: kontakt CreatorHub for faktura.
          </Typography>
        </Box>
      </Container>

      {/* SCARCITY-CTA */}
      <Box
        sx={{
          py: 8,
          background: 'linear-gradient(135deg, #F5B82E 0%, #D49B1A 100%)',
          color: 'white',
        }}
      >
        <Container maxWidth="md" sx={{ textAlign: 'center' }}>
          <SpeedIcon sx={{ fontSize: 48, mb: 2 }} />
          <Typography variant="h3" sx={{ fontWeight: 900, mb: 2 }}>
            Kampanjepris 49 kr/mnd — kun ut 2026
          </Typography>
          <Typography variant="body1" sx={{ mb: 3, opacity: 0.9, maxWidth: 580, mx: 'auto' }}>
            Standard-prisen er normalt 79 kr/mnd. Tidligbruker-rabatten på 30 kr/mnd er låst inn
            så lenge du holder abonnementet aktivt — du beholder 49 kr/mnd selv etter kampanjen
            er over.
          </Typography>
          <Button
            variant="contained"
            size="large"
            sx={{
              bgcolor: 'white', color: '#F5B82E', fontWeight: 700, px: 5, py: 1.5,
              '&:hover': { bgcolor: '#FAF7F0' },
            }}
            startIcon={<BoltIcon />}
            onClick={() => handleChoose('trial')}
            disabled={loading === 'trial'}
          >
            {loading === 'trial' ? 'Starter …' : 'Start 14 dagers prøveperiode nå'}
          </Button>
        </Container>
      </Box>

      {/* FOOTER */}
      <Box sx={{ py: 4, bgcolor: '#0F172A', color: 'white' }}>
        <Container maxWidth="lg">
          <Stack direction="row" justifyContent="space-between" alignItems="center" flexWrap="wrap" spacing={2}>
            <Box>
              <Typography variant="h6" sx={{ fontWeight: 800 }}>
                Next<Box component="span" sx={{ color: '#F5B82E' }}>Role</Box>
              </Typography>
              <Typography variant="caption" sx={{ opacity: 0.7 }}>by CreatorHub</Typography>
            </Box>
            <Stack direction="row" spacing={3}>
              <Typography variant="caption" component="a" href="/privacy-policy" sx={{ color: 'white', textDecoration: 'none' }}>
                Personvern
              </Typography>
              <Typography variant="caption" component="a" href="/terms-and-conditions" sx={{ color: 'white', textDecoration: 'none' }}>
                Vilkår
              </Typography>
              <Typography variant="caption" sx={{ opacity: 0.7 }}>
                © 2026 CreatorHub Norge AS
              </Typography>
            </Stack>
          </Stack>
        </Container>
      </Box>
    </Box>
  );
};

export default NextRoleLanding;
