import React from 'react';
import { Alert, Avatar, Box, Button, Card, Chip, CircularProgress, Container, Stack, TextField, ThemeProvider, Typography } from '@mui/material';
import CalendarMonth from '@mui/icons-material/CalendarMonth';
import CheckCircle from '@mui/icons-material/CheckCircle';
import { useRoute } from 'wouter';
import { apiRequest } from '@/lib/queryClient';
import { ws, workspaceDarkTheme } from '@/components/workspace/workspaceTheme';
import type { CreatorHubBookingProfile, CreatorHubBookingService } from '@shared/creatorhub-enterprise-operations';

const dateOnly = (date: Date) => date.toISOString().slice(0, 10);
export default function PublicBookingPage() {
  const [, params] = useRoute('/book/:slug'); const slug = params?.slug || '';
  const [profile, setProfile] = React.useState<CreatorHubBookingProfile | null>(null); const [services, setServices] = React.useState<CreatorHubBookingService[]>([]); const [serviceId, setServiceId] = React.useState(''); const [slots, setSlots] = React.useState<string[]>([]); const [selectedSlot, setSelectedSlot] = React.useState(''); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState(''); const [done, setDone] = React.useState<any>(null); const [form, setForm] = React.useState({ customerName: '', customerEmail: '', customerPhone: '', customerNote: '' });
  React.useEffect(() => { apiRequest(`/api/public/booking/${encodeURIComponent(slug)}`).then((data) => { setProfile(data.profile); setServices(data.services || []); setServiceId(data.services?.[0]?.id || ''); }).catch((cause) => setError(cause?.message || 'Bookingsiden finnes ikke.')).finally(() => setLoading(false)); }, [slug]);
  React.useEffect(() => { if (!serviceId) return; const to = new Date(); to.setDate(to.getDate() + 30); apiRequest(`/api/public/booking/${encodeURIComponent(slug)}/availability?serviceId=${encodeURIComponent(serviceId)}&from=${dateOnly(new Date())}&to=${dateOnly(to)}`).then((data) => setSlots(data.slots || [])).catch((cause) => setError(cause?.message || 'Kunne ikke laste ledige tider.')); }, [serviceId, slug]);
  const book = async () => { setError(''); try { const result = await apiRequest(`/api/public/booking/${encodeURIComponent(slug)}/bookings`, { method: 'POST', body: { serviceId, startsAt: selectedSlot, customerName: form.customerName, customerEmail: form.customerEmail, customerPhone: form.customerPhone || null, customerNote: form.customerNote || null, intakeAnswers: {}, privacyConsent: true, idempotencyKey: crypto.randomUUID() } }); setDone(result.booking); } catch (cause: any) { setError(cause?.message || 'Kunne ikke sende bookingen.'); } };
  if (loading) return <ThemeProvider theme={workspaceDarkTheme}><Box sx={{ minHeight: '100vh', bgcolor: ws.bg, display: 'grid', placeItems: 'center' }}><CircularProgress sx={{ color: ws.accent }} /></Box></ThemeProvider>;
  return <ThemeProvider theme={workspaceDarkTheme}><Box sx={{ minHeight: '100vh', bgcolor: ws.bg, color: ws.text, py: { xs: 3, md: 7 } }}><Container maxWidth="md">{error && !profile ? <Alert severity="error">{error}</Alert> : profile && <>
    <Stack alignItems="center" textAlign="center" spacing={1.5} sx={{ mb: 4 }}><Avatar src={profile.logoUrl || undefined} sx={{ width: 82, height: 82, bgcolor: ws.accentSoft }}>{profile.businessName.charAt(0)}</Avatar><Typography variant="h3" sx={{ fontWeight: 900 }}>{profile.businessName}</Typography>{profile.headline && <Typography sx={{ color: ws.textDim, maxWidth: 680 }}>{profile.headline}</Typography>}<Stack direction="row" spacing={1}>{profile.profession && <Chip label={profile.profession} />}{profile.locationLabel && <Chip label={profile.locationLabel} />}</Stack></Stack>
    {done ? <Card sx={{ p: 4, bgcolor: ws.panel, border: `1px solid ${ws.border}`, textAlign: 'center' }}><CheckCircle sx={{ fontSize: 58, color: ws.green }} /><Typography variant="h5" sx={{ fontWeight: 850, mt: 1 }}>Forespørselen er mottatt</Typography><Typography sx={{ color: ws.textDim, mt: 1 }}>Referanse {done.bookingReference}. Du får en bekreftelse når bookingen er godkjent.</Typography></Card> : <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '.85fr 1.15fr' }, gap: 2 }}>
      <Stack spacing={1.25}>{services.map((service) => <Card component="button" type="button" key={service.id} onClick={() => { setServiceId(service.id); setSelectedSlot(''); }} sx={{ p: 2, textAlign: 'left', color: ws.text, bgcolor: service.id === serviceId ? ws.accentSoft : ws.panel, border: `1px solid ${service.id === serviceId ? ws.accentBorder : ws.border}`, cursor: 'pointer' }}><Typography sx={{ fontWeight: 800 }}>{service.name}</Typography><Typography sx={{ color: ws.textDim, fontSize: 12.5 }}>{service.description}</Typography><Stack direction="row" justifyContent="space-between" sx={{ mt: 1 }}><Typography>{service.durationMinutes} min</Typography><Typography sx={{ color: ws.accent, fontWeight: 800 }}>{service.priceAmount.toLocaleString('nb-NO')} {profile.currency}</Typography></Stack></Card>)}</Stack>
      <Card sx={{ p: 2.5, bgcolor: ws.panel, border: `1px solid ${ws.border}` }}><Typography variant="h6" sx={{ fontWeight: 850, mb: 1.5 }}>Velg ledig tid</Typography><Stack direction="row" flexWrap="wrap" gap={1} sx={{ maxHeight: 210, overflowY: 'auto', mb: 2 }}>{slots.map((slot) => <Button key={slot} size="small" variant={selectedSlot === slot ? 'contained' : 'outlined'} onClick={() => setSelectedSlot(slot)} startIcon={<CalendarMonth />}>{new Date(slot).toLocaleString('nb-NO', { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: profile.timezone })}</Button>)}{!slots.length && <Typography sx={{ color: ws.textDim }}>Ingen ledige tider de neste 30 dagene.</Typography>}</Stack>
        <Stack spacing={1.5}><TextField label="Navn" value={form.customerName} onChange={(e) => setForm((f) => ({ ...f, customerName: e.target.value }))} /><TextField type="email" label="E-post" value={form.customerEmail} onChange={(e) => setForm((f) => ({ ...f, customerEmail: e.target.value }))} /><TextField label="Telefon (valgfritt)" value={form.customerPhone} onChange={(e) => setForm((f) => ({ ...f, customerPhone: e.target.value }))} /><TextField multiline minRows={2} label="Hva ønsker du hjelp med?" value={form.customerNote} onChange={(e) => setForm((f) => ({ ...f, customerNote: e.target.value }))} />{error && <Alert severity="error">{error}</Alert>}<Typography sx={{ color: ws.textFaint, fontSize: 11.5 }}>Ved å sende forespørselen samtykker du til at opplysningene behandles for å håndtere bookingen.</Typography><Button variant="contained" size="large" onClick={book} disabled={!selectedSlot || !form.customerName || !form.customerEmail} sx={{ bgcolor: ws.accent, color: ws.accentContrast }}>Send bookingforespørsel</Button></Stack>
      </Card>
    </Box>}
  </>}</Container></Box></ThemeProvider>;
}
