/**
 * Standard kontoplan basert på norsk kontoplanstandard (NS 4102-struktur).
 * Hver konto har brukervennlig metadata slik at brukergrensesnittet kan vise
 * handling og forklaring FØR teknisk kontonummer (produktprinsipp 4.1),
 * og slik at kodebiblioteket kan generere informasjonssider.
 *
 * Dette er et MVP-utvalg. Organisasjoner kan aktivere/utvide kontoplanen,
 * men numrene følger standard slik at SAF-T-eksport og regnskapsførere
 * kjenner seg igjen.
 */

export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';

export interface LedgerAccountDef {
  /** Firesifret standard kontonummer. */
  number: string;
  name: string;
  /** Brukervennlig navn som vises først i UI. */
  friendlyName: string;
  type: AccountType;
  plainExplanation: string;
  whenToUse: string;
  whenNotToUse?: string;
  examples: string[];
  commonMistakes?: string[];
  /** Vanligste SAF-T mva-koder for posteringer mot kontoen. */
  commonVatCodes: string[];
  /** Kan kostnaden normalt gi skattemessig fradrag? 'yes' | 'no' | 'depends' */
  taxDeductible?: 'yes' | 'no' | 'depends';
  /** true når kjøp på kontoen ofte egentlig er en eiendel som skal avskrives. */
  capitalizationCandidate?: boolean;
  /** true for reskontrokontoer (kunde/leverandør). */
  subledger?: 'customers' | 'vendors';
}

export const STANDARD_ACCOUNTS: LedgerAccountDef[] = [
  // ── Eiendeler ────────────────────────────────────────────────────────────
  {
    number: '1200',
    name: 'Maskiner og anlegg',
    friendlyName: 'Maskiner og produksjonsutstyr (eiendel)',
    type: 'asset',
    plainExplanation: 'Større maskiner og utstyr som skal avskrives over flere år.',
    whenToUse: 'Utstyr som koster 30 000 kr eller mer og varer i minst tre år.',
    examples: ['Produksjonsmaskin', 'Større verkstedsutstyr'],
    commonVatCodes: ['1'],
    taxDeductible: 'depends',
  },
  {
    number: '1250',
    name: 'Inventar',
    friendlyName: 'Inventar og innredning (eiendel)',
    type: 'asset',
    plainExplanation: 'Møbler og innredning som aktiveres og avskrives.',
    whenToUse: 'Inventar over grensen for direkte kostnadsføring.',
    examples: ['Kontormøblement ved nyinnredning'],
    commonVatCodes: ['1'],
    taxDeductible: 'depends',
  },
  {
    number: '1280',
    name: 'Kontormaskiner og datautstyr',
    friendlyName: 'Datautstyr og kontormaskiner (eiendel)',
    type: 'asset',
    plainExplanation:
      'Datautstyr og kontormaskiner som er dyre nok til å måtte avskrives (saldogruppe a, 30 %).',
    whenToUse: 'PC-er, servere, kamerautstyr o.l. som koster 30 000 kr eller mer og varer i minst tre år.',
    whenNotToUse: 'Rimeligere utstyr kostnadsføres direkte på 6551.',
    examples: ['Kameraparakke til 60 000 kr', 'Server'],
    commonVatCodes: ['1'],
    taxDeductible: 'depends',
  },
  {
    number: '1500',
    name: 'Kundefordringer',
    friendlyName: 'Penger kunder skylder deg',
    type: 'asset',
    plainExplanation: 'Fakturaer du har sendt som ikke er betalt ennå.',
    whenToUse: 'Automatisk ved fakturering. Reskontroføres per kunde.',
    examples: ['Utestående faktura'],
    commonVatCodes: ['0'],
    subledger: 'customers',
  },
  {
    number: '1900',
    name: 'Kontanter',
    friendlyName: 'Kontantkasse',
    type: 'asset',
    plainExplanation: 'Fysiske kontanter i virksomheten.',
    whenToUse: 'Kontantsalg og kontantutlegg.',
    examples: ['Vekslepenger'],
    commonVatCodes: ['0'],
  },
  {
    number: '1920',
    name: 'Bankinnskudd',
    friendlyName: 'Bankkonto',
    type: 'asset',
    plainExplanation: 'Virksomhetens driftskonto i banken.',
    whenToUse: 'Alle inn- og utbetalinger over bank.',
    examples: ['Betaling av leverandørfaktura', 'Kundeinnbetaling'],
    commonVatCodes: ['0'],
  },
  // ── Egenkapital og gjeld ────────────────────────────────────────────────
  {
    number: '2000',
    name: 'Aksjekapital',
    friendlyName: 'Aksjekapital (AS)',
    type: 'equity',
    plainExplanation: 'Innskutt aksjekapital i aksjeselskap.',
    whenToUse: 'Ved stiftelse og kapitalendringer i AS.',
    examples: ['Stiftelse med 30 000 kr aksjekapital'],
    commonVatCodes: ['0'],
  },
  {
    number: '2050',
    name: 'Annen egenkapital',
    friendlyName: 'Opptjent egenkapital',
    type: 'equity',
    plainExplanation: 'Akkumulert overskudd som er beholdt i virksomheten.',
    whenToUse: 'Ved årsavslutning og disponering av resultat.',
    examples: ['Overført årsresultat'],
    commonVatCodes: ['0'],
  },
  {
    number: '2060',
    name: 'Privatkonto uttak',
    friendlyName: 'Private uttak (ENK)',
    type: 'equity',
    plainExplanation:
      'Penger eller verdier eieren av et enkeltpersonforetak tar ut privat. Dette er ikke lønn og ikke en kostnad — det reduserer egenkapitalen.',
    whenToUse: 'Når eier av ENK tar ut penger, eller når private kjøp er betalt med firmakonto.',
    whenNotToUse: 'Bruk aldri denne i AS — der er uttak lønn, utbytte eller lån med egne regler.',
    examples: ['Overføring til privat konto', 'Privat middag betalt med firmakort'],
    commonMistakes: ['Å føre private kjøp som driftskostnad for å få fradrag — det er skatteunndragelse.'],
    commonVatCodes: ['0'],
    taxDeductible: 'no',
  },
  {
    number: '2400',
    name: 'Leverandørgjeld',
    friendlyName: 'Penger du skylder leverandører',
    type: 'liability',
    plainExplanation: 'Mottatte fakturaer som ikke er betalt ennå.',
    whenToUse: 'Automatisk ved bokføring av leverandørfaktura. Reskontroføres per leverandør.',
    examples: ['Ubetalt strømfaktura'],
    commonVatCodes: ['0'],
    subledger: 'vendors',
  },
  {
    number: '2500',
    name: 'Betalbar skatt',
    friendlyName: 'Skyldig skatt',
    type: 'liability',
    plainExplanation: 'Beregnet skatt som ikke er betalt ennå.',
    whenToUse: 'Ved avsetning for skatt (AS) eller forskuddsskatt-avsetning.',
    examples: ['Avsatt skatt av årets resultat'],
    commonVatCodes: ['0'],
  },
  {
    number: '2700',
    name: 'Utgående merverdiavgift',
    friendlyName: 'MVA du skylder staten (fra salg)',
    type: 'liability',
    plainExplanation: 'Mva du har krevd inn fra kundene og skal betale videre til staten.',
    whenToUse: 'Automatisk ved avgiftspliktig salg.',
    examples: ['25 % mva på en salgsfaktura'],
    commonVatCodes: ['0'],
  },
  {
    number: '2710',
    name: 'Inngående merverdiavgift',
    friendlyName: 'MVA du får igjen (fra kjøp)',
    type: 'asset',
    plainExplanation: 'Mva du har betalt på kjøp og kan trekke fra i mva-oppgjøret.',
    whenToUse: 'Automatisk ved fradragsberettigede kjøp.',
    examples: ['25 % mva på en leverandørfaktura'],
    commonVatCodes: ['0'],
  },
  {
    number: '2740',
    name: 'Oppgjørskonto merverdiavgift',
    friendlyName: 'MVA-oppgjør',
    type: 'liability',
    plainExplanation: 'Nettobeløpet som skal betales eller mottas ved mva-oppgjør for en termin.',
    whenToUse: 'Ved terminavslutning av mva.',
    examples: ['Overføring av utgående/inngående mva ved terminslutt'],
    commonVatCodes: ['0'],
  },
  // ── Inntekter ───────────────────────────────────────────────────────────
  {
    number: '3000',
    name: 'Salgsinntekt, avgiftspliktig, høy sats',
    friendlyName: 'Salg med 25 % mva',
    type: 'revenue',
    plainExplanation: 'Vanlig avgiftspliktig salg av varer og tjenester.',
    whenToUse: 'Salg i Norge når virksomheten er mva-registrert.',
    examples: ['Konsulenttime', 'Varesalg'],
    commonVatCodes: ['3'],
  },
  {
    number: '3100',
    name: 'Salgsinntekt, avgiftsfri',
    friendlyName: 'Salg uten mva (fritatt)',
    type: 'revenue',
    plainExplanation: 'Salg med nullsats, f.eks. eksport.',
    whenToUse: 'Eksport og annet fritatt salg.',
    examples: ['Tjenester levert til utenlandsk kunde'],
    commonVatCodes: ['52', '5'],
  },
  {
    number: '3200',
    name: 'Salgsinntekt, unntatt mva',
    friendlyName: 'Salg utenfor mva-loven',
    type: 'revenue',
    plainExplanation: 'Omsetning som er unntatt mva-loven, f.eks. helsetjenester og undervisning.',
    whenToUse: 'Unntatt omsetning. Merk: gir ikke fradragsrett for tilhørende kjøp.',
    examples: ['Undervisningstjenester'],
    commonVatCodes: ['6'],
  },
  {
    number: '3210',
    name: 'Bruksbasert inntekt (AI/kreditt)',
    friendlyName: 'AI-/bruksbasert inntekt',
    type: 'revenue',
    plainExplanation: 'Inntekt fra bruksbasert fakturering, som AI-kreditt/overforbruk fakturert til kundene.',
    whenToUse: 'Når kunden betaler for faktisk AI-/API-forbruk (f.eks. Stripe-metering / overage).',
    examples: ['AI-overforbruk', 'Kredittpakke'],
    commonVatCodes: ['6'],
  },
  {
    number: '3900',
    name: 'Annen driftsrelatert inntekt',
    friendlyName: 'Andre inntekter',
    type: 'revenue',
    plainExplanation: 'Inntekter som ikke er ordinært salg.',
    whenToUse: 'Tilskudd, refusjoner m.m.',
    examples: ['Offentlig tilskudd'],
    commonVatCodes: ['7'],
  },
  // ── Varekostnad ─────────────────────────────────────────────────────────
  {
    number: '4000',
    name: 'Innkjøp av varer for videresalg, høy sats',
    friendlyName: 'Varekjøp',
    type: 'expense',
    plainExplanation: 'Varer du kjøper inn for å selge videre.',
    whenToUse: 'Innkjøp av handelsvarer.',
    examples: ['Innkjøp av produkter til nettbutikk'],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
  },
  // ── Lønn ────────────────────────────────────────────────────────────────
  {
    number: '5000',
    name: 'Lønn til ansatte',
    friendlyName: 'Lønn',
    type: 'expense',
    plainExplanation: 'Bruttolønn til ansatte. Krever a-melding og skattetrekk (lønnsmodul kommer senere).',
    whenToUse: 'Lønnsutbetalinger i AS eller ENK med ansatte.',
    whenNotToUse: 'Eier av ENK kan ikke ta lønn fra eget foretak — bruk private uttak (2060).',
    examples: ['Månedslønn'],
    commonVatCodes: ['0'],
    taxDeductible: 'yes',
  },
  // ── Driftskostnader ─────────────────────────────────────────────────────
  {
    number: '6300',
    name: 'Leie lokale',
    friendlyName: 'Husleie for lokaler',
    type: 'expense',
    plainExplanation: 'Leie av kontor, verksted eller butikklokale.',
    whenToUse: 'Næringslokaler. Hjemmekontor har egne regler — spør assistenten.',
    examples: ['Kontorleie'],
    commonVatCodes: ['0', '1'],
    taxDeductible: 'yes',
  },
  {
    number: '6340',
    name: 'Lys og varme',
    friendlyName: 'Strøm og oppvarming',
    type: 'expense',
    plainExplanation: 'Strøm og oppvarming av næringslokaler.',
    whenToUse: 'Strømfaktura for lokalene.',
    examples: ['Strømregning for kontoret'],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
  },
  {
    number: '6500',
    name: 'Maskiner og utstyr (ikke aktiveringspliktig)',
    friendlyName: 'Verktøy og utstyr (direkte kostnad)',
    type: 'expense',
    plainExplanation: 'Utstyr under grensen for aktivering som kostnadsføres direkte.',
    whenToUse: 'Utstyr under 30 000 kr eller med kort levetid.',
    examples: ['Drill', 'Mindre verktøy'],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
    capitalizationCandidate: true,
  },
  {
    number: '6540',
    name: 'Inventar',
    friendlyName: 'Utstyr og mindre inventar',
    type: 'expense',
    plainExplanation:
      'Brukes vanligvis når virksomheten kjøper inventar og utstyr som skal brukes i driften og som kostnadsføres direkte.',
    whenToUse: 'Møbler og inventar under aktiveringsgrensen.',
    whenNotToUse: 'Kjøp på 30 000 kr eller mer med levetid over tre år skal vurderes aktivert (konto 1250/1280).',
    examples: ['Kontorstol', 'Skrivebord', 'Hyller'],
    commonMistakes: ['Å kostnadsføre dyre kjøp som skulle vært avskrevet over flere år.'],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
    capitalizationCandidate: true,
  },
  {
    number: '6551',
    name: 'Datautstyr',
    friendlyName: 'Datautstyr og elektronikk',
    type: 'expense',
    plainExplanation: 'PC, skjerm, kamera og annet elektronisk utstyr som kostnadsføres direkte.',
    whenToUse: 'Datautstyr under 30 000 kr eller med kort levetid.',
    whenNotToUse: 'Dyrere utstyr med lang levetid aktiveres på 1280 og avskrives.',
    examples: ['Laptop til 15 000 kr', 'Skjerm', 'Kamera til 20 000 kr'],
    commonMistakes: [
      'Privat elektronikk ført som næringskjøp.',
      'Utstyrspakker over grensen splittet kunstig for å unngå aktivering.',
    ],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
    capitalizationCandidate: true,
  },
  {
    number: '6552',
    name: 'Programvare',
    friendlyName: 'Programvare (kjøp)',
    type: 'expense',
    plainExplanation: 'Kjøpt programvare og lisenser.',
    whenToUse: 'Engangskjøp av programvare.',
    examples: ['Lisens til bilderedigering'],
    commonVatCodes: ['1', '86'],
    taxDeductible: 'yes',
  },
  {
    number: '6555',
    name: 'AI-tjenester og API-forbruk',
    friendlyName: 'AI- og API-kostnad',
    type: 'expense',
    plainExplanation: 'Kostnad til AI-/API-leverandører (f.eks. Anthropic, OpenAI, fal, ElevenLabs, Perplexity).',
    whenToUse: 'Forbruk hos AI-/API-leverandører. Tagg gjerne produktet (dimensjon) for AI-margin per produkt.',
    examples: ['Anthropic API', 'OpenAI', 'fal.ai', 'ElevenLabs'],
    commonVatCodes: ['86'],
    taxDeductible: 'yes',
  },
  {
    number: '6700',
    name: 'Revisjons- og regnskapshonorar',
    friendlyName: 'Regnskapsfører og revisor',
    type: 'expense',
    plainExplanation: 'Honorar til regnskapsfører og revisor.',
    whenToUse: 'Faktura fra regnskapsbyrå eller revisor.',
    examples: ['Månedlig regnskapshonorar'],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
  },
  {
    number: '6720',
    name: 'Honorar juridisk bistand',
    friendlyName: 'Advokat og juridisk hjelp',
    type: 'expense',
    plainExplanation: 'Advokathonorar og annen juridisk bistand i næring.',
    whenToUse: 'Juridiske tjenester knyttet til driften.',
    examples: ['Kontraktsgjennomgang'],
    commonVatCodes: ['1'],
    taxDeductible: 'depends',
  },
  {
    number: '6800',
    name: 'Kontorrekvisita',
    friendlyName: 'Kontorrekvisita',
    type: 'expense',
    plainExplanation: 'Penner, papir og annet forbruksmateriell.',
    whenToUse: 'Småinnkjøp til kontoret.',
    examples: ['Skriverpapir'],
    commonVatCodes: ['1'],
    taxDeductible: 'yes',
  },
  {
    number: '6810',
    name: 'Data/EDB-kostnad',
    friendlyName: 'Programvareabonnement og skytjenester',
    type: 'expense',
    plainExplanation:
      'Løpende abonnement på programvare og skytjenester. Utenlandske leverandører (f.eks. amerikanske SaaS-tjenester) skal ofte ha omvendt avgiftsplikt (kode 86).',
    whenToUse: 'Månedlige/årlige programvareabonnement.',
    examples: ['Regnskapsprogram', 'Skylagring', 'Designverktøy'],
    commonMistakes: ['Utenlandske abonnement ført med kode 1 i stedet for 86 (omvendt avgiftsplikt).'],
    commonVatCodes: ['86', '1'],
    taxDeductible: 'yes',
  },
  {
    number: '6900',
    name: 'Telefon',
    friendlyName: 'Telefon',
    type: 'expense',
    plainExplanation:
      'Telefonkostnader i næring. Ved blandet privat/næringsbruk gjelder sjablongregler — assistenten hjelper med fordelingen.',
    whenToUse: 'Mobilabonnement brukt i næring.',
    examples: ['Mobilregning'],
    commonMistakes: ['Full kostnadsføring av privat telefonbruk uten sjablongtillegg.'],
    commonVatCodes: ['1'],
    taxDeductible: 'depends',
  },
  {
    number: '6907',
    name: 'Datakommunikasjon',
    friendlyName: 'Internett',
    type: 'expense',
    plainExplanation: 'Internett-abonnement i næring. Blandet bruk må vurderes.',
    whenToUse: 'Bredbånd til kontor/hjemmekontor brukt i næring.',
    examples: ['Fiberabonnement'],
    commonVatCodes: ['1'],
    taxDeductible: 'depends',
  },
  {
    number: '7100',
    name: 'Bilkostnader',
    friendlyName: 'Bil og drivstoff',
    type: 'expense',
    plainExplanation:
      'Kostnader til yrkesbil eller næringsandel av privatbil. Egne regler for el-bil, yrkesbil og kilometergodtgjørelse.',
    whenToUse: 'Drivstoff, bompenger, service på bil i næring.',
    examples: ['Drivstoff', 'Bomavgift'],
    commonMistakes: ['Privatbilkostnader ført fullt ut uten fordeling.'],
    commonVatCodes: ['1', '0'],
    taxDeductible: 'depends',
  },
  {
    number: '7140',
    name: 'Reisekostnader',
    friendlyName: 'Reiser i jobb',
    type: 'expense',
    plainExplanation: 'Fly, tog, hotell og andre reisekostnader i næring.',
    whenToUse: 'Tjenestereiser med dokumentert formål.',
    examples: ['Flybillett til kundemøte', 'Hotellovernatting'],
    commonVatCodes: ['13', '1', '0'],
    taxDeductible: 'yes',
  },
  {
    number: '7320',
    name: 'Reklamekostnad',
    friendlyName: 'Markedsføring og annonser',
    type: 'expense',
    plainExplanation:
      'Annonsering og markedsføring. Utenlandske annonseplattformer har ofte omvendt avgiftsplikt (kode 86).',
    whenToUse: 'Annonser, nettsider, markedsføringsmateriell.',
    examples: ['Annonser på sosiale medier', 'Google Ads'],
    commonVatCodes: ['86', '1'],
    taxDeductible: 'yes',
  },
  {
    number: '7350',
    name: 'Representasjon, fradragsberettiget',
    friendlyName: 'Kundepleie (begrenset fradrag)',
    type: 'expense',
    plainExplanation:
      'Enkel bevertning av kunder har begrenset fradragsrett med beløpsgrenser og vilkår. Mva er normalt IKKE fradragsberettiget for representasjon.',
    whenToUse: 'Kun når vilkårene for fradragsberettiget representasjon er oppfylt.',
    examples: ['Enkel lunsj med kunde innenfor beløpsgrensen'],
    commonMistakes: ['Full mva-fradragsføring av representasjon.'],
    commonVatCodes: ['0'],
    taxDeductible: 'depends',
  },
  {
    number: '7500',
    name: 'Forsikringspremie',
    friendlyName: 'Forsikringer',
    type: 'expense',
    plainExplanation: 'Næringsforsikringer. Forsikring er unntatt mva.',
    whenToUse: 'Ansvarsforsikring, utstyrforsikring m.m.',
    examples: ['Ansvarsforsikring'],
    commonVatCodes: ['0'],
    taxDeductible: 'yes',
  },
  {
    number: '7770',
    name: 'Bank- og kortgebyr',
    friendlyName: 'Bankgebyrer',
    type: 'expense',
    plainExplanation: 'Gebyrer fra bank og betalingstjenester. Finansielle tjenester er unntatt mva.',
    whenToUse: 'Kontohold, kortgebyr, betalingsformidling.',
    examples: ['Månedsgebyr bedriftskonto', 'Stripe-gebyr'],
    commonVatCodes: ['0'],
    taxDeductible: 'yes',
  },
  {
    number: '7790',
    name: 'Annen kostnad',
    friendlyName: 'Andre kostnader',
    type: 'expense',
    plainExplanation: 'Kostnader som ikke passer i andre kategorier. Bruk sparsomt.',
    whenToUse: 'Kun når ingen annen konto passer.',
    commonMistakes: ['Å bruke denne som samlekonto i stedet for å kategorisere riktig.'],
    examples: [],
    commonVatCodes: ['1', '0'],
    taxDeductible: 'depends',
  },
  // ── Finans ──────────────────────────────────────────────────────────────
  {
    number: '8050',
    name: 'Renteinntekt',
    friendlyName: 'Renteinntekter',
    type: 'revenue',
    plainExplanation: 'Renter på bankinnskudd.',
    whenToUse: 'Automatisk ved renteinnbetaling fra bank.',
    examples: ['Innskuddsrente'],
    commonVatCodes: ['0'],
  },
  {
    number: '8150',
    name: 'Rentekostnad',
    friendlyName: 'Rentekostnader',
    type: 'expense',
    plainExplanation: 'Renter på lån og kreditt i næring.',
    whenToUse: 'Renter på næringslån.',
    examples: ['Rente på driftskreditt'],
    commonVatCodes: ['0'],
    taxDeductible: 'yes',
  },
  {
    number: '8060',
    name: 'Valutagevinst (agio)',
    friendlyName: 'Valutagevinst',
    type: 'revenue',
    plainExplanation: 'Gevinst når valutakursen endrer seg i din favør mellom faktura og betaling.',
    whenToUse: 'Automatisk ved valutadifferanser.',
    examples: ['EUR-faktura som ble billigere i NOK ved betaling'],
    commonVatCodes: ['0'],
  },
  {
    number: '8160',
    name: 'Valutatap (disagio)',
    friendlyName: 'Valutatap',
    type: 'expense',
    plainExplanation: 'Tap når valutakursen endrer seg i din disfavør mellom faktura og betaling.',
    whenToUse: 'Automatisk ved valutadifferanser.',
    examples: ['USD-faktura som ble dyrere i NOK ved betaling'],
    commonVatCodes: ['0'],
    taxDeductible: 'yes',
  },
  {
    number: '8300',
    name: 'Betalbar skatt (skattekostnad)',
    friendlyName: 'Skattekostnad',
    type: 'expense',
    plainExplanation:
      'Årets beregnede selskapsskatt. Bokføres kun for aksjeselskap ved årsavslutning — motsatsen er «Betalbar skatt» (2500) som du betaler til Skatteetaten.',
    whenToUse: 'Automatisk ved årsavslutning for AS. Enkeltpersonforetak skatter privat og bruker ikke denne.',
    examples: ['22 % selskapsskatt av skattepliktig overskudd'],
    commonVatCodes: ['0'],
    taxDeductible: 'no',
  },
];

const byNumber = new Map(STANDARD_ACCOUNTS.map((a) => [a.number, a]));

export function getAccountDef(accountNumber: string): LedgerAccountDef | undefined {
  return byNumber.get(accountNumber);
}
