/**
 * CreatorHub Norge - Resume & Project Timeline Integration
 * Automatically updates CV when projects are completed
 */

import { apiRequest } from '@/lib/queryClient';

export interface ProjectCompletionEvent {
  projectId: string;
  projectTitle: string;
  clientName: string;
  projectType: string;
  description?: string;
  location?: string;
  startDate?: string;
  endDate: string;
  completedAt: string;
  userId: string;
}

/**
 * Automatically add completed project to all active resumes
 */
export async function addCompletedProjectToResumes(
  projectData: ProjectCompletionEvent
): Promise<void> {
  try {
    // Get all active resumes for the user
    const resumes = await apiRequest('/api/resumes', {
      headers: { 'x-user-id': projectData.userId },
    });

    if (!resumes || resumes.length === 0) {
      console.log('No active resumes found, skipping auto-add to CV');
      return;
    }

    // Add to each active resume
    for (const resume of resumes) {
      if (resume.status === 'active' || resume.status === 'draft') {
        await addProjectExperience(resume.id, projectData);
        await addPortfolioProject(resume.id, projectData);
      }
    }

    console.log(`✅ Project ${projectData.projectTitle} added to ${resumes.length} resume(s)`);
  } catch (error) {
    console.error('Failed to add project to resumes: ', error);
    throw error;
  }
}

/**
 * Add project as work experience
 */
async function addProjectExperience(
  resumeId: string,
  projectData: ProjectCompletionEvent
): Promise<void> {
  try {
    await apiRequest(`/api/resumes/${resumeId}/experiences`, {
      method: 'POST',
      headers: {
        'x-user-id': projectData.userId,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        jobTitle: getJobTitleFromProjectType(projectData.projectType),
        company: projectData.clientName,
        location: projectData.location || ', ',
        employmentType: 'freelance',
        startDate: projectData.startDate || projectData.completedAt,
        endDate: projectData.endDate,
        isCurrent: false,
        description: projectData.description || `Successful ${projectData.projectType} project for ${projectData.clientName}`,
        achievements: [],
        skills: extractSkillsFromProjectType(projectData.projectType),
        projectId: projectData.projectId,
        autoGenerated: true,
        isVisible: true,
      }),
    });
  } catch (error) {
    console.error('Failed to add project experience:', error);
  }
}

/**
 * Add project to portfolio
 */
async function addPortfolioProject(
  resumeId: string,
  projectData: ProjectCompletionEvent
): Promise<void> {
  try {
    await apiRequest(`/api/resumes/${resumeId}/projects`, {
      method: 'POST',
      headers: {
        'x-user-id': projectData.userId,
        'Content-Type' : 'application/json',
      },
      body: JSON.stringify({
        title: projectData.projectTitle,
        description: projectData.description || `${projectData.projectType} project for ${projectData.clientName}`,
        role: 'Lead',
        startDate: projectData.startDate || projectData.completedAt,
        endDate: projectData.endDate,
        technologies: extractTechnologiesFromProjectType(projectData.projectType),
        achievements: [],
        projectUrl: ', ',
        images: [],
        projectId: projectData.projectId,
        autoGenerated: true,
        isVisible: true,
      }),
    });
  } catch (error) {
    console.error('Failed to add portfolio project:', error);
  }
}

/**
 * Get appropriate job title based on project type
 */
function getJobTitleFromProjectType(projectType: string): string {
  const titleMap: Record<string, string> = {
    'wedding':'Bryllupsfotograf','portrait':'Portrettfotograf','event':'Event-fotograf','commercial':'Kommersiell fotograf','video':'Videograf','music':'Musikkprodusent','family':'Familie-fotograf','product' : 'Produktfotograf',
  };

  return titleMap[projectType] || 'Kreativ profesjonell';
}

/**
 * Extract relevant skills from project type
 */
function extractSkillsFromProjectType(projectType: string): string[] {
  const skillsMap: Record<string, string[]> = {
    'wedding': ['Bryllupsfotografering','Portrettfotografering','Eventhåndtering','Klientrelasjoner'],'portrait': ['Portrettfotografering','Studiofotografering','Belysning','Bilderedigering'],'event': ['Event-fotografering','Dokumentarfotografering','Miljøfotografering'],'commercial': ['Kommersiell fotografering','Produktfotografering','Markedsføring'],'video': ['Videografi','Videoredigering','Cinematografi','Fortelling'],'music': ['Musikkproduksjon','Lydteknikk','Mixing','Mastering'],'family': ['Familie-fotografering','Barnefotografering','Naturlig lysbruk'],'product': ['Produktfotografering','Studiofotografering','E-handel fotografering'],
  };

  return skillsMap[projectType] || ['Fotografering','Bilderedigering'];
}

/**
 * Extract technologies/tools from project type
 */
function extractTechnologiesFromProjectType(projectType: string): string[] {
  const techMap: Record<string, string[]> = {
    'wedding': ['Adobe Lightroom','Adobe Photoshop','Camera Raw'],'portrait': ['Adobe Lightroom','Adobe Photoshop','Capture One'],'event': ['Adobe Lightroom','Adobe Photoshop'],'commercial': ['Adobe Photoshop','Adobe Lightroom','Capture One'],'video': ['Adobe Premiere Pro','DaVinci Resolve','Final Cut Pro'],'music': ['Logic Pro','Ableton Live','Pro Tools'],'family': ['Adobe Lightroom','Adobe Photoshop'],'product': ['Adobe Photoshop', 'Adobe Lightroom', 'Capture One'],
  };

  return techMap[projectType] || ['Adobe Creative Suite'];
}

/**
 * Hook to automatically trigger CV update on project completion
 * Call this in ProjectTimeline component when a project is marked as completed
 */
export function useProjectCompletionTrigger() {
  const handleProjectCompleted = async (projectData: ProjectCompletionEvent) => {
    try {
      await addCompletedProjectToResumes(projectData);
      
      // Show notification
      if (typeof window !== 'undefined' && 'Notification' in window) {
        if (Notification.permission === 'granted') {
          new Notification('CV oppdatert! 🎉', {
            body: `Prosjektet "${projectData.projectTitle}" er lagt til i CV-en din`,
            icon: '/logo.png',
          });
        }
      }
    } catch (error) {
      console.error('Failed to auto-update CV:', error);
    }
  };

  return { handleProjectCompleted };
}

/**
 * Check if a project already exists in a resume
 */
export async function isProjectInResume(
  resumeId: string,
  projectId: string,
  userId: string
): Promise<boolean> {
  try {
    const resume = await apiRequest(`/api/resumes/${resumeId}`, {
      headers: {'x-user-id': userId },
    });

    const existsInExperience = resume.experiences?.some(
      (exp: any) => exp.projectId === projectId
    );
    
    const existsInProjects = resume.projects?.some(
      (proj: any) => proj.projectId === projectId
    );

    return existsInExperience || existsInProjects;
  } catch (error) {
    console.error('Failed to check project in resume:', error);
    return false;
  }
}

