// @ts-nocheck
/**
 * BringPhotographerDashboard - Photographer Dashboard with Bring Integration
 * Auto-generated by Code Generator
 */

import { useTheming } from '../../utils/theming-helper';
import { useProfessionConfigs } from '@/hooks/useProfessionConfigs';
import { useProfessionAdapter } from '@/hooks/useProfessionAdapter';
import getProfessionIcon from '@/utils/profession-icons';
import { useDynamicProfessions } from '../universal/hooks/useDynamicProfessions';
import React, { useState } from 'react';
import {
  Box,
  Container,
  Typography,
  Tabs,
  Tab,
  Paper,
  Grid,
  Card,
  CardContent,
  Alert,
  Chip,
  Button,
} from '@mui/material';
import { PhotographyIconAlt } from '../shared/CreatorHubIcons';
import {
  LocalShipping as LocalDirectionsBoatping,
  Calculate,
  Search,
  LocationOn,
  CheckCircle,
  Info,
  PhotoLibrary,
  Send,
} from '@mui/icons-material';

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`bring-photographer-tabpanel-${index}`}
      aria-labelledby={`bring-photographer-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}

function a11yProps(index: number) {
  return {
    id: `bring-photographer-tab-${index}`, 'aria-controls': `bring-photographer-tabpanel-${index}`,
};
}

interface BringPhotographerDashboardProps {
  profession?: string;
  apiName?: string;
}

export const BringPhotographerDashboard: React.FC<BringPhotographerDashboardProps> = ({ 
  profession = "photographer", 
  apiName = "bring" 
}) => {
  const [activeTab, setActiveTab] = useState(0);
  const [systemStatus, setSystemStatus] = useState({
    apiConnected: true,
    wireMockActive: true,
    lastUpdated: new Date().toISOString(),
});

  const handleTabChange = (event: React.SyntheticEvent, newValue: number) => {
    setActiveTab(newValue);
};

  const tabs = [
    {
      label: 'Fraktkalkulator',
      icon: <Calculate />,
      component: (
        <Box>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Beregn fraktkostnader for fotopakker
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Kalkuler leveringskostnader for dine fotopakker til kunder.
          </Typography>
          <Button variant="contained" startIcon={<Calculate />} sx={theming.getThemedButtonSx()}>
            Start Kalkulator
          </Button>
        </Box>
      ),
      description: 'Beregn fraktkostnader og leveringstider for fotopakker',
  },
    {
      label: 'Pakkesporing',
      icon: theming.getThemedIcon('search,'),
      component: (
        <Box>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Spor fotopakker
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Følg leveringen av dine fotopakker til kunder i sanntid.
          </Typography>
          <Button variant="contained" startIcon={theming.getThemedIcon('search')} sx={theming.getThemedButtonSx()}>
            Spor Pakke
          </Button>
        </Box>
      ),
      description: 'Spor dine fotopakker i sanntid',
  },
    {
      label: 'Postnummer Validering',
      icon: theming.getThemedIcon('locationOn'),
      component: (
        <Box>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Verifiser leveringsadresser
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Sjekk at kundens adresse er gyldig før levering.
          </Typography>
          <Button variant="contained" startIcon={theming.getThemedIcon('locationOn')} sx={theming.getThemedButtonSx()}>
            Valider Adresse
          </Button>
        </Box>
      ),
      description: 'Verifiser norske postnummer for levering',
  },
    {
      label: 'Fotopakke Sending',
      icon: <Send />,
      component: (
        <Box>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Send fotopakke
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Opprett og send fotopakke til kunde med Bring.
          </Typography>
          <Button variant="contained" startIcon={<Send />} sx={theming.getThemedButtonSx()}>
            Send Pakke
          </Button>
        </Box>
      ),
      description: 'Opprett og send fotopakke til kunde',
  },
  ];

  return (
    <Container maxWidth="xl" sx={{ py: 4 }}>
      {/* Header */}
      <Box sx={{ mb: 4 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
          <CameraAlt sx={{ fontSize: 40, color: 'primary.main', mr: 2 }} />
          <Box>
            <Typography variant="h3" component="h1" gutterBottom sx={{ color: theming.colors.primary }}>
              Fotograf Dashboard - Bring Integrasjon
            </Typography>
            <Typography variant="subtitle1" color="text.secondary">
              Komplett løsning for frakt og logistikk av fotopakker med Bring API
            </Typography>
          </Box>
        </Box>

        {/* System Status */}
        <Box sx={{ mb: 3 }}>
          <Grid container spacing={2} alignItems="center">
            <Grid item>
              <Chip
                icon={theming.getThemedIcon('checkCircle')}
                label="API Tilkoblet"
                color="success"
                variant="outlined"
              />
            </Grid>
            <Grid item>
              <Chip
                icon={theming.getThemedIcon('info')}
                label="WireMock Aktiv"
                color="info"
                variant="outlined"
              />
            </Grid>
            <Grid item>
              <Chip
                icon={<PhotographyIcon />}
                label={`Profesjon: ${profession}`}
                color="primary"
                variant="outlined"
              />
            </Grid>
            <Grid item>
              <Typography variant="body2" color="text.secondary">
                Sist oppdatert: {new Date(systemStatus.lastUpdated).toLocaleString(', ')}
              </Typography>
            </Grid>
          </Grid>
        </Box>

        {/* Info Alert */}
        <Alert severity="info" sx={{ mb: 3 }}>
          <Typography variant="body2">
            <strong>Fotograf Dashboard: </strong> Spesialisert dashboard for fotografer med Bring-integrasjon.
            Alle komponenter er koblet til WireMock API for testing av Bring-integrasjonen.
          </Typography>
        </Alert>
      </Box>

      {/* Main Content */}
      <Paper elevation={1}>
        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tabs
            value={activeTab}
            onChange={handleTabChange}
            aria-label="Bring photographer tabs"
            variant="fullWidth"
          >
            {tabs.map((tab, index) => (
              <Tab
                key={index}
                icon={tab.icon}
                label={tab.label}
                {...a11yProps(index)}
                sx={{ py: 2 }}
              />
            ))}
          </Tabs>
        </Box>

        {/* Tab Content */}
        {tabs.map((tab, index) => (
          <TabPanel key={index} value={activeTab} index={index}>
            <Box sx={{ mb: 3 }}>
              <Typography variant="h5" gutterBottom sx={{ ...{}, color: theming.colors.primary }}>
                {tab.label}
              </Typography>
              <Typography variant="body1" color="text.secondary" gutterBottom>
                {tab.description}
              </Typography>
            </Box>
            {tab.component}
          </TabPanel>
        ))}
      </Paper>

      {/* Footer Info */}
      <Box sx={{ mt: 4, p: 3, bgcolor: 'grey.50', borderRadius: 1 }}>
        <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
          Om denne løsningen
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Denne dashboarden er spesialisert for fotografer og integrerer Bring API for 
          enkel håndtering av fotopakke-leveringer til kunder.
        </Typography>
        <Grid container spacing={2}>
          <Grid item xs={12}>
            <Card variant="outlined" sx={theming.getThemedCardSx()}>
              <CardContent sx={theming.getThemedCardSx()}>
                <Typography variant="subtitle2" gutterBottom>
                  📸 Fotograf-spesifikk
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Tilpasset for fotografer med fokus på fotopakke-leveringer
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card variant="outlined" sx={theming.getThemedCardSx()}>
              <CardContent sx={theming.getThemedCardSx()}>
                <Typography variant="subtitle2" gutterBottom>
                  🔌 Bring API Integrert
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Direkte kobling til Bring API for frakt og levering
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card variant="outlined" sx={theming.getThemedCardSx()}>
              <CardContent sx={theming.getThemedCardSx()}>
                <Typography variant="subtitle2" gutterBottom>
                  🚀 Produksjonsklar
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Komplett løsning med error handling og brukervennlig UI
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </Box>
    </Container>
  );
};

export default BringPhotographerDashboard;
