/**
 * BringShippingDashboard - Main Dashboard for Bring Integration
 * Auto-generated by Code Generator
 */

import { useTheming } from '../../utils/theming-helper';
import React, { useState } from 'react';
import {
  Box,
  Container,
  Typography,
  Tabs,
  Tab,
  Paper,
  Grid,
  Card,
  CardContent,
  Alert,
  Chip,
} from '@mui/material';
import {
  LocalShipping,
  Calculate,
  Search,
  LocationOn,
  CheckCircle,
  Info,
} from '@mui/icons-material';

import ShippingCalculator from './ShippingCalculator';
import PackageTracker from './PackageTracker';
import PostalCodeValidator from './PostalCodeValidator';

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`bring-tabpanel-${index}`}
      aria-labelledby={`bring-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p:  3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}

function a11yProps(index: number) {
  return {
    id: `bring-tab-${index}`, 'aria-controls': `bring-tabpanel-${index}`
  };
}

export const BringShippingDashboard: React.FC = () => {
  const [activeT, absetActiveTab] = useState(false);
  
  // Theming system
  const theming = useTheming('photographer');
  const [systemStatus, setSystemStatus] = useState({
    apiConnected: true,
    wireMockActive: true,
    lastUpdated: new Date().toISOString(),
});

  const handleTabChange = (event: React.SyntheticEvent, newValue: number) => {
    setActiveTab(newValue);
};

  const tabs = [
    {
      label: 'Fraktkalkulator',
      icon: <Calculate />,
      component: <ShippingCalculator />,
      description: 'Beregn fraktkostnader og leveringstider',
  },
    {
      label: 'Pakkesporing',
      icon: theming.getThemedIcon(', '),
      component: <PackageTracker />,
      description: 'Spor din pakke i sanntid',
  },
    {
      label: 'Postnummer Validering',
      icon: theming.getThemedIcon(''),
      component: <PostalCodeValidator />,
      description: 'Verifiser norske postnummer',
  },
  ];

  return (
    <Container maxWidth="xl" sx={{ py:  4 }}>
      {/* Header */}
      <Box sx={{ mb:  4 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', mb:  2 }}>
          <LocalShipping sx={{ fontSize:  40, color: 'primary.main', mr:  2 }} />
          <Box>
            <Typography variant="h3" component="h1" gutterBottom sx={{ color: theming.colors.primary }}>
              Bring Shipping Dashboard
            </Typography>
            <Typography variant="subtitle1" color="text.secondary">
              Komplett løsning for frakt og logistikk med Bring API
            </Typography>
          </Box>
        </Box>

        {/* System Status */}
        <Box sx={{ mb:  3 }}>
          <Grid container spacing={2} alignItems="center">
            <Grid item>
              <Chip
                icon={theming.getThemedIcon('checkCircle')}
                label="API Tilkoblet"
                color="success"
                variant="outlined"
              />
            </Grid>
            <Grid item>
              <Chip
                icon={theming.getThemedIcon('info')}
                label="WireMock Aktiv"
                color="info"
                variant="outlined"
              />
            </Grid>
            <Grid item>
              <Typography variant="body2" color="text.secondary">
                Sist oppdatert: {new Date(systemStatus.lastUpdated).toLocaleString(', ')}
              </Typography>
            </Grid>
          </Grid>
        </Box>

        {/* Info Alert */}
        <Alert severity="info" sx={{ mb:  3 }}>
          <Typography variant="body2">
            <strong>Code Generator Test: </strong> Denne dashboarden er generert automatisk av Code Generator systemet.
            Alle komponenter er koblet til WireMock API for testing av Bring-integrasjonen.
          </Typography>
        </Alert>
      </Box>

      {/* Main Content */}
      <Paper elevation={1} sx={theming.getThemedCardSx()}>
        <Box sx={{ borderBottom: 1, borderColor: 'divider'}}>
          <Tabs
            value={activeTab}
            onChange={handleTabChange}
            aria-label="Bring shipping tabs"
            variant="fullWidth"
          >
            {tabs.map((tab, index) => (
              <Tab
                key={index}
                icon={tab.icon}
                label={tab.label}
                {...a11yProps(index)}
                sx={{ py:  2 }}
              />
            ))}
          </Tabs>
        </Box>

        {/* Tab Content */}
        {tabs.map((tab, index) => (
          <TabPanel key={index} value={activeTab} index={index}>
            <Box sx={{ mb:  3 }}>
              <Typography variant="h5" gutterBottom sx={{ color: theming.colors.primary }}>
                {tab.label}
              </Typography>
              <Typography variant="body1" color="text.secondary" gutterBottom>
                {tab.description}
              </Typography>
            </Box>
            {tab.component}
          </TabPanel>
        ))}
      </Paper>

      {/* Footer Info */}
      <Box sx={{ mt:  4, p:  3, bgcolor: 'grey.5', borderRadius:  1 }}>
        <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
          Om denne løsningen
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Denne dashboarden demonstrerer Code Generator systemets evne til å automatisk generere
          komplett frontend-løsninger for API-integrasjoner. Alle komponenter er: </Typography>
        <Grid container spacing={2}>
          <Grid item xs={12}>
            <Card variant="outlined" sx={theming.getThemedCardSx()}>
              <CardContent sx={theming.getThemedCardSx()}>
                <Typography variant="subtitle2" gutterBottom>
                  🎯 Automatisk Generert
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Komponenter opprettet av Code Generator basert på Bring API spesifikasjoner
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card variant="outlined" sx={theming.getThemedCardSx()}>
              <CardContent sx={theming.getThemedCardSx()}>
                <Typography variant="subtitle2" gutterBottom>
                  🔌 API Integrert
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Direkte kobling til WireMock systemet for sanntidstesting av API-endepunkter
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card variant="outlined" sx={theming.getThemedCardSx()}>
              <CardContent sx={theming.getThemedCardSx()}>
                <Typography variant="subtitle2" gutterBottom>
                  🚀 Produksjonsklar
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Komplett løsning med error handling, loading states og brukervennlig UI
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </Box>
    </Container>
  );
};

export default BringShippingDashboard;

