/**
 * PackageTracker - Bring API Integration Component
 * Auto-generated by Code Generator
 */

import { useTheming } from '../../utils/theming-helper';
import React, { useState } from 'react';
import { apiRequest } from '@/lib/queryClient';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/useAuth';
import {
  Card,
  CardContent,
  CardHeader,
  TextField,
  Button,
  Grid,
  Typography,
  Box,
  Alert,
  CircularProgress,
  Stepper,
  Step,
  StepLabel,
  StepContent,
  Chip,
  Divider,
} from '@mui/material';
import {
  LocalShipping,
  Search,
  CheckCircle,
  Schedule,
  LocationOn,
  Warning,
  Info,
} from '@mui/icons-material';

interface TrackingEvent {
  timestamp: string;
  status: string;
  location: string;
  description: string
}

interface TrackingResult {
  success: boolean;
  trackingNumber: string;
  service: string;
  status: 'delivered' | 'in_transit' | 'pending' | 'exception';
  events: TrackingEvent[];
  estimatedDelivery?: string;
  currentLocation?: string;
  message: string;
}

interface PackageTrackerProps {
  initialTrackingNumber?: string;
}

export const PackageTracker: React.FC<PackageTrackerProps> = ({
  initialTrackingNumber = '',
}) => {
  const [trackingNumber, setTrackingNumber] = useState(initialTrackingNumber);

  // Theming system
  const theming = useTheming('photographer');
  const [trackingResult, setTrackingResult] = useState<TrackingResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const trackPackage = async () => {
    if (!trackingNumber.trim()) {
      setError('Vennligst skriv inn et sporingsnummer');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await fetch('/api/wiremock/test-bring', {
        headers: {
          'Content-Type' : 'application/json',
        },
        body: JSON.stringify({
          action: 'track',
          trackingNumber: trackingNumber.trim(),
      }),
    });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }

      const result = await response.json();

      if (result.success) {
        // Use real tracking data from API response
        const trackingData: TrackingResult = {
          success: true,
          trackingNumber: result.trackingNumber || trackingNumber.trim(),
          service: result.service || 'Bring Pakke',
          status: result.status || 'in_transit',
          events: result.events || [],
          estimatedDelivery: result.estimatedDelivery,
          currentLocation: result.currentLocation || result.toPostalCode,
          message: result.message,
        };

        setTrackingResult(trackingData);
      } else {
        throw new Error(result.message || 'Kunne ikke spore pakken');
      }
    } catch (err) {
      console.error('Package tracking error: ', err);
      setError(err instanceof Error ? err.message : 'En feil oppstod ved sporing');
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'delivered':
        return 'success';
      case 'in_transit':
        return 'info';
      case 'pending':
        return 'warning';
      case 'exception':
        return 'error';
      default:
        return 'default';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'delivered':
        return <CheckCircle />;
      case 'in_transit':
        return <LocalShipping />;
      case 'pending':
        return <Schedule />;
      case 'exception':
        return <Warning />;
      default:
        return <Info />;
    }
  };

  const formatTimestamp = (timestamp: string) => {
    return new Date(timestamp).toLocaleString('no-NO', {
      weekday: 'short',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <Card sx={{ maxWidth: 800, mx: 'auto', mt: 2, ...theming.getThemedCardSx() }}>
      <CardHeader
        avatar={<LocalShipping color="primary" />}
        title="Bring Pakkesporing"
        subheader="Spor din pakke i sanntid"
      />
      <CardContent sx={theming.getThemedCardSx()}>
        {/* Search Input */}
        <Box sx={{ mb: 3 }}>
          <TextField
            fullWidth
            label="Sporingsnummer"
            value={trackingNumber}
            onChange={(e) => setTrackingNumber(e.target.value)}
            placeholder="BRING123456789"
            sx={{ mb: 2 }}
            InputProps={{
              endAdornment: (
                <Button
                  variant="contained"
                  onClick={trackPackage}
                  disabled={loading}
                  startIcon={loading ? <CircularProgress size={20} /> : <Search />}
                  sx={{ ml: 1, ...theming.getThemedButtonSx() }}
                >
                  {loading ? 'Sporer...' : 'Spor'}
                </Button>
              )}}
          />
        </Box>

        {/* Error Display */}
        {error && (
          <Alert severity="error" sx={{ mb:  3 }}>
            {error}
          </Alert>
        )}

        {/* Tracking Results */}
        {trackingResult && (
          <Box>
            {/* Package Status Header */}
            <Box sx={{ mb: 3 }}>
              <Grid container spacing={2} alignItems="center">
                <Grid item>
                  <Chip
                    icon={getStatusIcon(trackingResult.status)}
                    label={trackingResult.service}
                    color={getStatusColor(trackingResult.status)}
                    size="medium"
                  />
                </Grid>
                <Grid item>
                  <Typography variant="h6" sx={{ color: theming.colors.primary }}>
                    {trackingResult.trackingNumber}
                  </Typography>
                </Grid>
              </Grid>
            </Box>

            {/* Current Status */}
            <Box sx={{ mb:  3 }}>
              <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
                Status
              </Typography>
              <Typography variant="body1" gutterBottom>
                <strong>Tjeneste: </strong> {trackingResult.service}
              </Typography>
              <Typography variant="body1" gutterBottom>
                <strong>Nåværende status: </strong> På vei til destinasjon
              </Typography>
              {trackingResult.estimatedDelivery && (
                <Typography variant="body1" gutterBottom>
                  <strong>Estimert levering:</strong>{', '}
                  {new Date(trackingResult.estimatedDelivery).toLocaleDateString('no-NO')}
                </Typography>
              )}
              {trackingResult.currentLocation && (
                <Typography variant="body1" gutterBottom>
                  <strong>Nåværende lokasjon: </strong> {trackingResult.currentLocation}
                </Typography>
              )}
            </Box>

            <Divider sx={{ my:  3 }} />

            {/* Tracking Events Timeline */}
            <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
              Sporingshistorikk
            </Typography>
            
            <Stepper orientation="vertical" sx={{ mt:  2 }}>
              {trackingResult.events.map((event, index) => (
                <Step key={index} active={true} completed={index < trackingResult.events.length - 1}>
                  <StepLabel
                    icon={getStatusIcon(event.status)}
                    optional={
                      <Typography variant="caption">
                        {formatTimestamp(event.timestamp)}
                      </Typography>
                  }
                  >
                    <Typography variant="subtitle1">
                      {event.description}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      <LocationOn fontSize="small" sx={{ mr: 0.5, verticalAlign: 'middle' }} />
                      {event.location}
                    </Typography>
                  </StepLabel>
                  <StepContent>
                    <Typography variant="body2" color="text.secondary">
                      {formatTimestamp(event.timestamp)}
                    </Typography>
                  </StepContent>
                </Step>
              ))}
            </Stepper>


          </Box>
        )}

        {/* Help Text */}
        {!trackingResult && !loading && !error && (
          <Box sx={{ textAlign: 'center', py:  4 }}>
            <LocalShipping sx={{ fontSize:  48, color:'text.secondary', mb:  2 }} />
            <Typography variant="body1" color="text.secondary">
              Skriv inn sporingsnummeret ditt for å se status og sporingshistorikk
            </Typography>
          </Box>
        )}
      </CardContent>
    </Card>
  );
};

export default PackageTracker;

