/**
 * PostalCodeValidator - Bring API Integration Component
 * Auto-generated by Code Generator
 */

import { useTheming } from '../../utils/theming-helper';
import React, { useState, useEffect } from 'react';
import { apiRequest } from '@/lib/queryClient';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/useAuth';
import { useExternalData } from '../../services/ExternalDataService';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  TextField,
  Button,
  Grid,
  Typography,
  Box,
  Alert,
  CircularProgress,
  Chip,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Divider,
  Autocomplete,
} from '@mui/material';
import { 
  LocationOn, 
  Search, 
  CheckCircle, 
  Warning,
  Info,
  Place
} from '@mui/icons-material';

interface PostalCodeInfo {
  postalCode: string;
  city: string;
  municipality: string;
  county: string;
  region: string;
  valid: boolean;
  source?: 'bring_api' | 'fallback';
  coordinates?: {
    latitude: number;
    longitude: number;
  };
}

interface PostalCodeValidatorProps {
  onValidPostalCode?: (info: PostalCodeInfo) => void;
  onInvalidPostalCode?: (postalCode: string) => void
}

// Common Norwegian postal codes for autocomplete
const commonPostalCodes = [
  { code: '0001', city: 'Oslo' },
  { code: '0150', city: 'Oslo' },
  { code: '0159', city: 'Oslo' },
  { code: '0580', city: 'Oslo' },
  { code: '5003', city: 'Bergen' },
  { code: '5020', city: 'Bergen' },
  { code: '7010', city: 'Trondheim' },
  { code: '7030', city: 'Trondheim' },
  { code: '4008', city: 'Stavanger' },
  { code: '8006', city: 'Bodø' },
  { code: '9008', city: 'Tromsø' },
  { code: '9170', city: 'Longyearbyen' },
];

export const PostalCodeValidator: React.FC<PostalCodeValidatorProps> = ({
  onValidPostalCode,
  onInvalidPostalCode,
}) => {
  // Theming system
  const theming = useTheming('photographer');
  const { validatePostalCode: validatePostalCodeService } = useExternalData();
  
  const [postalCode, setPostalCode] = useState('');
  const [validationResult, setValidationResult] = useState<PostalCodeInfo | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [recentValidations, setRecentValidations] = useState<PostalCodeInfo[]>([]);

  // Auto-validate as user types (with debounce)
  useEffect(() => {
    if (postalCode.length === 4 && /^\d{4}$/.test(postalCode)) {
      const timer = setTimeout(() => {
        validatePostalCode();
    }, 500);
      return () => clearTimeout(timer);
  }
}, [postalCode]);

  const validatePostalCode = async () => {
    if (!postalCode.trim() || !/^\d{4}$/.test(postalCode)) {
      setError('Vennligst skriv inn et gyldig 4-siffer postnummer, ');
      return;
  }

    setLoading(true);
    setError(null);

    try {
      // Call the real Bring API via ExternalDataService
      const result = await validatePostalCodeService(postalCode.trim());

      if (result.valid) {
        const postalInfo: PostalCodeInfo = {
          postalCode: postalCode.trim(),
          city: result.city || 'Ukjent by',
          municipality: result.municipality || 'Ukjent kommune',
          county: result.municipality || 'Ukjent fylke', // Use municipality as county fallback
          region: getRegionFromPostalCode(postalCode.trim()),
          valid: true,
          source: result.source,
        };

        setValidationResult(postalInfo);
        setRecentValidations(prev => [postalInfo, ...prev.slice(0, 4)]);
        onValidPostalCode?.(postalInfo);
      } else {
        setValidationResult({
          postalCode: postalCode.trim(),
          city: 'Ugyldig',
          municipality: 'Ugyldig',
          county: 'Ugyldig',
          region: 'Ugyldig',
          valid: false,
          source: result.source,
        });
        setError(result.error || 'Ugyldig postnummer');
        onInvalidPostalCode?.(postalCode);
      }
    } catch (err) {
      console.error('Postal code validation error: ', err);
      setError(err instanceof Error ? err.message : 'En feil oppstod ved validering');
    } finally {
      setLoading(false);
    }
  };

  // Helper to determine region from postal code prefix
  const getRegionFromPostalCode = (code: string): string => {
    const prefix = parseInt(code.substring(0, 1));
    switch (prefix) {
      case 0:
      case 1:
      case 2:
      case 3:
        return 'Østlandet';
      case 4:
        return 'Sørlandet';
      case 5:
        return 'Vestlandet';
      case 6:
        return 'Vestlandet/Møre og Romsdal';
      case 7:
        return 'Trøndelag';
      case 8:
      case 9:
        return 'Nord-Norge';
      default:
        return 'Ukjent';
    }
  };

  const isValidPostalCode = (code: string): boolean => {
    return /^\d{4}$/.test(code);
  };

  return (
    <Card
      sx={{ maxWidth: 600, mx: 'auto', mt: 2, ...theming.getThemedCardSx() }}
      role="region"
      aria-labelledby="postal-validator-title"
    >
      <CardHeader
        avatar={<LocationOn color="primary" aria-hidden="true" />}
        title={<span id="postal-validator-title">Postnummer Validering</span>}
        subheader="Verifiser norske postnummer og få detaljert informasjon"
      />
      <CardContent sx={theming.getThemedCardSx()}>
        {/* WCAG 2.2 Compliant Input Section */}
        <Box sx={{ mb: 3 }} role="search" aria-label="Søk etter postnummer">
          <Autocomplete
            freeSolo
            options={commonPostalCodes}
            getOptionLabel={(option) =>
              typeof option === 'string' ? option : `${option.code} - ${option.city}`
            }
            aria-describedby="postal-code-help"
            renderInput={(params) => (
              <TextField
                {...params}
                fullWidth
                label="Postnummer"
                value={postalCode}
                onChange={(e) => setPostalCode(e.target.value.replace(/\D/g, ', ').slice(0, 4))}
                placeholder="0159"
                sx={{ mb: 2 }}
                inputProps={{
                  ...params.inputProps,
                  'aria-label':'Skriv inn 4-siffer postnummer', 'aria-invalid': error ? 'true' : 'false', 'aria-describedby': error ? 'postal-error' : 'postal-code-help',
                  maxLength: 4,
                  pattern: '[0-9]{4}',
                  inputMode: 'numeric'}}
                InputProps={{
                  ...params.InputProps,
                  endAdornment: (
                    <Button
                      variant="contained"
                      onClick={validatePostalCode}
                      disabled={loading || !isValidPostalCode(postalCode)}
                      startIcon={loading ? <CircularProgress size={20} aria-hidden="true" /> : theming.getThemedIcon('search')}
                      sx={{ ml: 1 }}
                      aria-busy={loading}
                      aria-label={loading ? 'Validerer postnummer' : 'Valider postnummer'}
                    >
                      {loading ? 'Validerer...' : 'Valider'}
                    </Button>
                  )}}
              />
            )}
          />

          <Typography
            id="postal-code-help"
            variant="body2"
            color="text.secondary"
            role="status"
          >
            Skriv inn et 4-siffer postnummer for å få informasjon om området
          </Typography>
        </Box>

        {/* WCAG 2.2 Compliant Error Display */}
        {error && (
          <Alert
            severity="error"
            sx={{ mb: 3 }}
            id="postal-error"
            role="alert"
            aria-live="assertive"
          >
            {error}
          </Alert>
        )}

        {/* WCAG 2.2 Compliant Validation Results */}
        {validationResult && (
          <Box
            sx={{ mb: 3 }}
            role="region"
            aria-label="Valideringsresultat"
            aria-live="polite"
          >
            <Grid container spacing={2} alignItems="center" sx={{ mb: 2 }}>
              <Grid>
                <Chip
                  icon={validationResult.valid ? theming.getThemedIcon('checkCircle') : theming.getThemedIcon('warning')}
                  label={validationResult.valid ? 'Gyldig postnummer' : 'Ugyldig postnummer'}
                  color={validationResult.valid ? 'success' : 'error'}
                  size="medium"
                  aria-label={validationResult.valid ? 'Status: Gyldig postnummer' : 'Status: Ugyldig postnummer'}
                />
              </Grid>
              <Grid>
                <Typography variant="h6" sx={{ color: theming.colors.primary }} aria-label={`Postnummer: ${validationResult.postalCode}`}>
                  {validationResult.postalCode}
                </Typography>
              </Grid>
            </Grid>

            {validationResult.valid && (
              <List
                dense
                aria-label="Postnummer informasjon"
                role="list"
              >
                <ListItem role="listitem" aria-label={`By: ${validationResult.city}`}>
                  <ListItemIcon aria-hidden="true">
                    <Place color="primary" />
                  </ListItemIcon>
                  <ListItemText
                    primary="By"
                    secondary={validationResult.city}
                  />
                </ListItem>

                <ListItem role="listitem" aria-label={`Kommune: ${validationResult.municipality}`}>
                  <ListItemIcon aria-hidden="true">
                    <LocationOn color="primary" />
                  </ListItemIcon>
                  <ListItemText
                    primary="Kommune"
                    secondary={validationResult.municipality}
                  />
                </ListItem>

                <ListItem role="listitem" aria-label={`Fylke: ${validationResult.county}`}>
                  <ListItemIcon aria-hidden="true">
                    <Info color="primary" />
                  </ListItemIcon>
                  <ListItemText
                    primary="Fylke"
                    secondary={validationResult.county}
                  />
                </ListItem>

                <ListItem role="listitem" aria-label={`Region: ${validationResult.region}`}>
                  <ListItemIcon aria-hidden="true">
                    <LocationOn color="primary" />
                  </ListItemIcon>
                  <ListItemText
                    primary="Region"
                    secondary={validationResult.region}
                  />
                </ListItem>

                {validationResult.coordinates && (
                  <>
                    <Divider sx={{ my: 1 }} aria-hidden="true" />
                    <ListItem role="listitem" aria-label={`Koordinater: ${validationResult.coordinates.latitude.toFixed(4)}, ${validationResult.coordinates.longitude.toFixed(4)}`}>
                      <ListItemIcon aria-hidden="true">
                        <LocationOn color="primary" />
                      </ListItemIcon>
                      <ListItemText
                        primary="Koordinater"
                        secondary={`${validationResult.coordinates.latitude.toFixed(4)}, ${validationResult.coordinates.longitude.toFixed(4)}`}
                      />
                    </ListItem>
                  </>
                )}

                {/* Data source indicator with WCAG 2.2 compliance */}
                <Divider sx={{ my: 1 }} aria-hidden="true" />
                <ListItem
                  role="listitem"
                  aria-label={`Datakilde: ${validationResult.source === 'bring_api' ? 'Bring API Live data' : 'Fallback data'}`}
                >
                  <ListItemIcon aria-hidden="true">
                    <Info color={validationResult.source === 'bring_api' ? 'success' : 'warning'} />
                  </ListItemIcon>
                  <ListItemText
                    primary="Datakilde"
                    secondary={validationResult.source === 'bring_api' ? 'Bring API (Live)' : 'Fallback data'}
                  />
                </ListItem>
              </List>
            )}
          </Box>
        )}

        {/* WCAG 2.2 Compliant Recent Validations */}
        {recentValidations.length > 0 && (
          <Box role="region" aria-labelledby="recent-validations-title">
            <Typography
              id="recent-validations-title"
              variant="h6"
              gutterBottom
              sx={{ color: theming.colors.primary }}
            >
              Nylige valideringer
            </Typography>
            <List dense aria-label="Liste over nylige valideringer">
              {recentValidations.slice(0, 3).map((validation, index) => (
                <ListItem
                  key={index}
                  sx={{ py: 0.5 }}
                  role="listitem"
                  aria-label={`${validation.postalCode} ${validation.city}, ${validation.municipality}`}
                >
                  <ListItemIcon aria-hidden="true">
                    <CheckCircle color="success" />
                  </ListItemIcon>
                  <ListItemText
                    primary={`${validation.postalCode} - ${validation.city}`}
                    secondary={`${validation.municipality}, ${validation.county}`}
                  />
                  <Button
                    size="small"
                    onClick={() => setPostalCode(validation.postalCode)}
                    aria-label={`Bruk postnummer ${validation.postalCode} for ${validation.city}`}
                  >
                    Bruk
                  </Button>
                </ListItem>
              ))}
            </List>
          </Box>
        )}

        {/* WCAG 2.2 Compliant Help Text */}
        {!validationResult && !loading && !error && (
          <Box
            sx={{ textAlign: 'center', py: 4 }}
            role="status"
            aria-label="Venter på input"
          >
            <LocationOn sx={{ fontSize: 48, color:'text.secondary', mb: 2 }} aria-hidden="true" />
            <Typography variant="body1" color="text.secondary">
              Skriv inn et norsk postnummer for å få detaljert informasjon
            </Typography>
          </Box>
        )}
      </CardContent>
    </Card>
  );
};

export default PostalCodeValidator;

