/**
 * ShippingCalculator - Bring API Integration Component
 * Auto-generated by Code Generator
 */

import { useTheming } from '../../utils/theming-helper';
import React, { useState } from 'react';
import { apiRequest } from '@/lib/queryClient';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/useAuth';
import { useExternalData } from '../../services/ExternalDataService';
import {
  Card,
  CardContent,
  CardHeader,
  TextField,
  Button,
  Grid,
  Typography,
  Box,
  Alert,
  CircularProgress,
  Chip,
  Divider,
} from '@mui/material';
import { LocalShipping, Calculate, Euro } from '@mui/icons-material';

interface ShippingQuote {
  service: string;
  rate: number;
  currency: string;
  deliveryDays: number;
  trackingNumber: string;
  estimatedDelivery: string;
  fromPostalCode: string;
  toPostalCode: string;
  weight: number;
  message: string;
  mock?: boolean
}

interface ShippingCalculatorProps {
  onQuoteGenerated?: (quote: ShippingQuote) => void
}

export const ShippingCalculator: React.FC<ShippingCalculatorProps> = ({
  onQuoteGenerated,
}) => {
  // Theming system
  const theming = useTheming('photographer');
  const { calculateShippingCosts } = useExternalData();
  
  const [formData, setFormData] = useState({
    fromPostalCode: '0159',
    toPostalCode: '5020',
    weight: 1.5,
});

  const [quote, setQuote] = useState<ShippingQuote | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleInputChange = (field: string, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [field]: value,
  }));
};

  const calculateShipping = async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await calculateShippingCosts({
        fromPostalCode: formData.fromPostalCode,
        toPostalCode: formData.toPostalCode,
        weight: formData.weight,
        packageType: 'BPAKKE'
    });

      const shippingQuote: ShippingQuote = {
        service: result.service,
        rate: result.cost,
        deliveryTime: result.deliveryTime,
        weight: formData.weight,
        message: `Fraktkostnad: ${result.cost} NOK`,
        mock: result.source === 'fallback'
    };

      setQuote(shippingQuote);
      onQuoteGenerated?.(shippingQuote);
  } catch (err) {
      console.error('Shipping calculation error: ', err);
      setError(err instanceof Error ? err.message : 'En feil oppstod');
  } finally {
      setLoading(false);
  }
};

  const formatCurrency = (amount: number, currency: string) => {
    return new Intl.NumberFormat('no-NO', {
      style: 'currency',
      currency: currency === 'NOK' ? 'NOK' : 'EUR',
  }).format(amount);
};

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('no-NO', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
  });
};

  return (
    <Card sx={{ maxWidth: 800, mx: 'auto', mt: 2, ...theming.getThemedCardSx() }}>
      <CardHeader
        avatar={<LocalShipping color="primary" />}
        title="Bring Fraktkalkulator"
        subheader="Beregn fraktkostnader og leveringstider"
      />
      <CardContent sx={theming.getThemedCardSx()}>
        <Grid container spacing={3}>
          {/* Input Form */}
          <Grid size={{ xs: 12 }}>
            <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
              Fraktdetaljer
            </Typography>

            <TextField
              fullWidth
              label="Fra postnummer"
              value={formData.fromPostalCode}
              onChange={(e) => handleInputChange('fromPostalCode', e.target.value)}
              placeholder="0159"
              sx={{ mb: 2 }}
            />

            <TextField
              fullWidth
              label="Til postnummer"
              value={formData.toPostalCode}
              onChange={(e) => handleInputChange('toPostalCode', e.target.value)}
              placeholder="5020"
              sx={{ mb: 2 }}
            />

            <TextField
              fullWidth
              label="Vekt (kg)"
              type="number"
              value={formData.weight}
              onChange={(e) => handleInputChange('weight', parseFloat(e.target.value) || 0)}
              inputProps={{ min: 0, max: 30, step: 0.1 }}
              sx={{ mb: 3 }}
            />

            <Button
              variant="contained"
              size="large"
              fullWidth
              onClick={calculateShipping}
              disabled={loading}
              startIcon={loading ? <CircularProgress size={20} /> : <Calculate />}
              sx={theming.getThemedButtonSx()}
            >
              {loading ? 'Beregner...' : 'Beregn Frakt'}
            </Button>
          </Grid>

          {/* Results */}
          <Grid size={{ xs: 12 }}>
            <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
              Fraktresultat
            </Typography>
            
            {error && (
              <Alert severity="error" sx={{ mb:  2 }}>
                {error}
              </Alert>
            )}
            
            {quote && (
              <Box>
                <Box sx={{ mb:  2 }}>
                  <Chip
                    icon={<Euro />}
                    label={formatCurrency(quote.rate, quote.currency)}
                    color="primary"
                    size="large"
                    sx={{ fontSize: '1.2rem', fontWeight: 'bold'}}
                  />
                </Box>
                
                <Typography variant="body1" gutterBottom>
                  <strong>Tjeneste: </strong> {quote.service}
                </Typography>
                
                <Typography variant="body1" gutterBottom>
                  <strong>Leveringstid: </strong> {quote.deliveryDays} arbeidsdager
                </Typography>
                
                <Typography variant="body1" gutterBottom>
                  <strong>Estimert levering: </strong> {formatDate(quote.estimatedDelivery)}
                </Typography>
                
                <Divider sx={{ my:  2 }} />
                
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  <strong>Fra: </strong> {quote.fromPostalCode}
                </Typography>
                
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  <strong>Til: </strong> {quote.toPostalCode}
                </Typography>
                
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  <strong>Vekt: </strong> {quote.weight} kg
                </Typography>
                
                {quote.trackingNumber && (
                  <Box sx={{ mt:  2 }}>
                    <Typography variant="body2" color="text.secondary">
                      <strong>Sporingsnummer: </strong>
                    </Typography>
                    <Typography variant="body2" fontFamily="monospace" sx={{ bgcolor:'grey.10', p: 1, borderRadius:  1 }}>
                      {quote.trackingNumber}
                    </Typography>
                  </Box>
                )}
                
                {quote.mock && (
                  <Alert severity="info" sx={{ mt:  2 }}>
                    Dette er en test-respons fra WireMock systemet
                  </Alert>
                )}
              </Box>
            )}
            
            {!quote && !loading && !error && (
              <Typography variant="body2" color="text.secondary">
                Fyll inn fraktdetaljene og klikk"Beregn Frakt" for å se resultater
              </Typography>
            )}
          </Grid>
        </Grid>
      </CardContent>
    </Card>
  );
};

export default ShippingCalculator;
