/**
 * Demo dancer profiles — brukes i Storybook og dev for å vise grid uten
 * backend. ALDRI seedet inn i prod-DB. Profilene matcher DEMO_DANCERS
 * (Ingrid, Martin, Sofie, Jonas) fra formationTypes.ts.
 */

import type { DancerProfile } from './dancerProfileService';

const NOW = '2026-04-25T10:00:00Z';

export const DEMO_DANCER_PROFILES: readonly DancerProfile[] = [
  {
    ownerUserId: 'demo-owner',
    dancerId: 'd-ingrid',
    displayName: 'Ingrid Nordahl',
    heightCm: 168,
    primaryStyle: 'contemporary',
    strengths: ['turns', 'musicality', 'improv'],
    availabilityWindows: [
      { from: '2026-04-25T09:00:00Z', to: '2026-04-25T17:00:00Z', note: 'Hele dagen' },
    ],
    injuryStatus: 'healthy',
    injuryNote: null,
    reelUrls: ['https://vimeo.com/example/ingrid-2026'],
    bodyMeasurements: { inseamCm: 78, weightKg: 56, shoeSize: 38.5 },
    skillLevels: {
      turns: 'pro',
      leaps: 'advanced',
      lifts: 'advanced',
      partnering: 'advanced',
      improv: 'pro',
      musicality: 'pro',
      floorwork: 'advanced',
    },
    notes: 'Solo-protagonist for høst-sesongen. Foretrekker å varme opp 30 min før prøver.',
    projectId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    ownerUserId: 'demo-owner',
    dancerId: 'd-martin',
    displayName: 'Martin Aas',
    heightCm: 182,
    primaryStyle: 'contemporary',
    strengths: ['lifts', 'partnering'],
    availabilityWindows: [
      { from: '2026-04-25T13:00:00Z', to: '2026-04-25T20:00:00Z', note: 'Etter kl. 13' },
    ],
    injuryStatus: 'cleared-with-restriction',
    injuryNote: 'Venstre kne — unngå dyp landing fra hopp over 1 m.',
    reelUrls: [],
    bodyMeasurements: { inseamCm: 92, reachCm: 188, weightKg: 78, shoeSize: 44 },
    skillLevels: {
      turns: 'advanced',
      leaps: 'intermediate',
      lifts: 'pro',
      partnering: 'pro',
      improv: 'advanced',
      musicality: 'advanced',
      floorwork: 'intermediate',
    },
    notes: 'Pas de deux med Ingrid. Sterkest på lift-arbeid.',
    projectId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    ownerUserId: 'demo-owner',
    dancerId: 'd-sofie',
    displayName: 'Sofie Olsen',
    heightCm: 162,
    primaryStyle: 'jazz',
    strengths: ['leaps', 'floorwork'],
    availabilityWindows: [],
    injuryStatus: 'healthy',
    injuryNote: null,
    reelUrls: ['https://youtube.com/watch?v=example-sofie'],
    bodyMeasurements: { inseamCm: 75, weightKg: 52, shoeSize: 37 },
    skillLevels: {
      turns: 'advanced',
      leaps: 'pro',
      lifts: 'intermediate',
      partnering: 'intermediate',
      improv: 'advanced',
      musicality: 'advanced',
      floorwork: 'pro',
    },
    notes: null,
    projectId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    ownerUserId: 'demo-owner',
    dancerId: 'd-jonas',
    displayName: 'Jonas K.',
    heightCm: 178,
    primaryStyle: 'hip-hop',
    strengths: ['floorwork', 'improv'],
    availabilityWindows: [],
    injuryStatus: 'rehab',
    injuryNote: 'Akilles — venter på fysio-grønt-lys (2 uker).',
    reelUrls: [],
    bodyMeasurements: { inseamCm: 86, weightKg: 72, shoeSize: 43 },
    skillLevels: {
      turns: 'intermediate',
      leaps: 'intermediate',
      lifts: 'beginner',
      partnering: 'intermediate',
      improv: 'advanced',
      musicality: 'advanced',
      floorwork: 'pro',
    },
    notes: 'Rehab-modus — kun gulvarbeid og improv inntil videre.',
    projectId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
] as const;
