import {
  pgTable,
  text,
  varchar,
  timestamp,
  boolean,
  integer,
  jsonb,
  uuid,
} from 'drizzle-orm/pg-core';
import { createInsertSchema } from 'drizzle-zod';
import type { z } from 'zod';

// Client Portal Access for Music Producer's Clients
export const clientPortals = pgTable('client_portals', {
  id: uuid('id').primaryKey().defaultRandom(),
  sessionId: uuid('session_id').notNull(),
  producerId: varchar('producer_id').notNull(),
  clientName: varchar('client_name').notNull(),
  clientEmail: varchar('client_email').notNull(),
  accessToken: varchar('access_token').notNull().unique(),
  permissions: jsonb('permissions')
    .$type<{
      canDownload: boolean;
      canComment: boolean;
      canViewAll: boolean;
      expiresAt?: string;
    }>()
    .notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  isActive: boolean('is_active').default(true),
});

// Downloadable Stems/Parts for Clients
export const downloadableStems = pgTable('downloadable_stems', {
  id: uuid('id').primaryKey().defaultRandom(),
  sessionId: uuid('session_id').notNull(),
  portalId: uuid('portal_id').notNull(),
  stemName: varchar('stem_name').notNull(),
  stemType: varchar('stem_type').notNull(), // 'track', 'mix', 'master', 'rough'
  filePath: varchar('file_path').notNull(),
  fileName: varchar('file_name').notNull(),
  fileSize: integer('file_size').notNull(),
  duration: integer('duration'), // in seconds
  sampleRate: integer('sample_rate').default(48000),
  bitDepth: integer('bit_depth').default(24),
  format: varchar('format').default('wav'), // 'wav', 'mp3', 'aiff'
  isPublic: boolean('is_public').default(false),
  downloadCount: integer('download_count').default(0),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Client Comments with Timeline Integration
export const clientComments = pgTable('client_comments', {
  id: uuid('id').primaryKey().defaultRandom(),
  sessionId: uuid('session_id').notNull(),
  portalId: uuid('portal_id').notNull(),
  stemId: uuid('stem_id'), // Optional - comment on specific stem
  clientName: varchar('client_name').notNull(),
  clientEmail: varchar('client_email').notNull(),
  comment: text('comment').notNull(),
  timePosition: integer('time_position'), // Time in milliseconds where comment applies
  priority: varchar('priority').default('normal'), // 'low', 'normal', 'high', 'urgent'
  status: varchar('status').default('open'), // 'open', 'in_progress', 'resolved', 'closed'
  proToolsMarker: jsonb('pro_tools_marker').$type<{
    markerName: string;
    timePosition: number;
    trackName?: string;
    barsBeat?: string;
  }>(),
  attachments: jsonb('attachments').$type<string[]>().default([]),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  resolvedAt: timestamp('resolved_at'),
  resolvedBy: varchar('resolved_by'),
});

// Producer Responses to Client Comments
export const commentResponses = pgTable('comment_responses', {
  id: uuid('id').primaryKey().defaultRandom(),
  commentId: uuid('comment_id').notNull(),
  sessionId: uuid('session_id').notNull(),
  producerId: varchar('producer_id').notNull(),
  response: text('response').notNull(),
  actionTaken: text('action_taken'), // Description of what was changed
  proToolsUpdate: jsonb('pro_tools_update').$type<{
    editsMade: string[];
    tracksAffected: string[];
    newMixVersion?: string;
  }>(),
  createdAt: timestamp('created_at').defaultNow(),
});

// Download History for Analytics
export const downloadHistory = pgTable('download_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  portalId: uuid('portal_id').notNull(),
  stemId: uuid('stem_id').notNull(),
  clientEmail: varchar('client_email').notNull(),
  downloadedAt: timestamp('downloaded_at').defaultNow(),
  ipAddress: varchar('ip_address'),
  userAgent: varchar('user_agent'),
});

// Zod Schemas for Validation
export const insertClientPortalSchema = createInsertSchema(clientPortals).omit({
  id: true,
  accessToken: true, // Generated by service
  createdAt: true,
  updatedAt: true,
});

export const insertDownloadableStemSchema = createInsertSchema(downloadableStems).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  downloadCount: true,
});

export const insertClientCommentSchema = createInsertSchema(clientComments).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  resolvedAt: true,
  resolvedBy: true,
});

export const insertCommentResponseSchema = createInsertSchema(commentResponses).omit({
  id: true,
  createdAt: true,
});

export const insertDownloadHistorySchema = createInsertSchema(downloadHistory).omit({
  id: true,
  downloadedAt: true,
});

// TypeScript Types
export type ClientPortal = typeof clientPortals.$inferSelect;
export type InsertClientPortal = z.infer<typeof insertClientPortalSchema>;

export type DownloadableStem = typeof downloadableStems.$inferSelect;
export type InsertDownloadableStem = z.infer<typeof insertDownloadableStemSchema>;

export type ClientComment = typeof clientComments.$inferSelect;
export type InsertClientComment = z.infer<typeof insertClientCommentSchema>;

export type CommentResponse = typeof commentResponses.$inferSelect;
export type InsertCommentResponse = z.infer<typeof insertCommentResponseSchema>;

export type DownloadHistory = typeof downloadHistory.$inferSelect;
export type InsertDownloadHistory = z.infer<typeof insertDownloadHistorySchema>;
