/**
 * CreatorHub Norge - Auto-Generated Folder Structure System
 * Creates comprehensive folder structure for all dashboard features and Daniel administrator access
 */

export interface PlatformFolder {
  id: string;
  name: string;
  path: string;
  category: 'dashboard' | 'admin' | 'system' | 'user' | 'smart_notes';
  description: string;
  permissions: string[];
  autoGenerated: boolean;
  parentFolder?: string;
  subFolders?: PlatformFolder[];
}

// Auto-generated folder structure for all CreatorHub Norge features
export const AUTO_GENERATED_FOLDERS: PlatformFolder[] = [
  // Main Dashboard Folders
  {
    id: 'photographer-dashboard',
    name: 'Fotografer Dashboard',
    path: '/folders/photographer-dashboard',
    category: 'dashboard',
    description: 'Komplett fotografer dashboard med prosjekter, klienter, og utstyr',
    permissions: ['photographer', 'admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'photo-projects',
        name: 'Fotoprosjekter',
        path: '/folders/photographer-dashboard/photo-projects',
        category: 'dashboard',
        description: 'Alle fotograferingsprosjekter og oppdrag',
        permissions: ['photographer', 'admin'],
        autoGenerated: true,
      },
      {
        id: 'client-management',
        name: 'Klienthåndtering',
        path: '/folders/photographer-dashboard/client-management',
        category: 'dashboard',
        description: 'Klientinformasjon og kommunikasjon',
        permissions: ['photographer', 'admin'],
        autoGenerated: true,
      },
      {
        id: 'equipment-rental',
        name: 'Utstyrsutleie',
        path: '/folders/photographer-dashboard/equipment-rental',
        category: 'dashboard',
        description: 'Utstyrshåndtering og utleiesystem',
        permissions: ['photographer', 'admin'],
        autoGenerated: true,
      },
    ],
  },

  // Videographer Dashboard
  {
    id: 'videographer-dashboard',
    name: 'Videograf Dashboard',
    path: '/folders/videographer-dashboard',
    category: 'dashboard',
    description: 'Komplett videograf dashboard med produksjoner og redigering',
    permissions: ['videographer', 'admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'video-productions',
        name: 'Videoproduksjoner',
        path: '/folders/videographer-dashboard/video-productions',
        category: 'dashboard',
        description: 'Alle videoproduksjoner og filmprosjekter',
        permissions: ['videographer', 'admin'],
        autoGenerated: true,
      },
      {
        id: 'video-editing',
        name: 'Videoredigering',
        path: '/folders/videographer-dashboard/video-editing',
        category: 'dashboard',
        description: 'Videoredigeringsprosjekter og DaVinci Resolve',
        permissions: ['videographer', 'admin'],
        autoGenerated: true,
      },
    ],
  },

  // Music Producer Dashboard
  {
    id: 'music-producer-dashboard',
    name: 'Musikkprodusent Dashboard',
    path: '/folders/music-producer-dashboard',
    category: 'dashboard',
    description: 'Komplett musikkprodusent dashboard med studio og miksing',
    permissions: ['music_producer', 'admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'music-productions',
        name: 'Musikkproduksjoner',
        path: '/folders/music-producer-dashboard/music-productions',
        category: 'dashboard',
        description: 'Alle musikkproduksjoner og studioarbeid',
        permissions: ['music_producer', 'admin'],
        autoGenerated: true,
      },
      {
        id: 'mixing-mastering',
        name: 'Miksing og Mastering',
        path: '/folders/music-producer-dashboard/mixing-mastering',
        category: 'dashboard',
        description: 'Miksing og mastering prosjekter',
        permissions: ['music_producer', 'admin'],
        autoGenerated: true,
      },
    ],
  },

  // Vendor Dashboard
  {
    id: 'vendor-dashboard',
    name: 'Leverandør Dashboard',
    path: '/folders/vendor-dashboard',
    category: 'dashboard',
    description: 'Leverandør dashboard med produkter og salg',
    permissions: ['vendor', 'admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'vendor-products',
        name: 'Leverandørprodukter',
        path: '/folders/vendor-dashboard/vendor-products',
        category: 'dashboard',
        description: 'Alle leverandørprodukter og tjenester',
        permissions: ['vendor', 'admin'],
        autoGenerated: true,
      },
    ],
  },

  // Smart Notes System - Special folder for Daniel
  {
    id: 'smart-notes-system',
    name: 'Smart Notes System',
    path: '/folders/smart-notes-system',
    category: 'smart_notes',
    description: 'AI-drevet notatsystem integrert med Google Docs for Daniel administrasjon',
    permissions: ['admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'developer-notes',
        name: 'Utviklernotater',
        path: '/folders/smart-notes-system/developer-notes',
        category: 'smart_notes',
        description: 'Tekniske notater og utviklingsideer',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'bug-fixes',
        name: 'Feilrettinger',
        path: '/folders/smart-notes-system/bug-fixes',
        category: 'smart_notes',
        description: 'Oversikt over feilrettinger og tekniske problemer',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'feature-requests',
        name: 'Funksjonsforespørsler',
        path: '/folders/smart-notes-system/feature-requests',
        category: 'smart_notes',
        description: 'Nye funksjoner og forbedringer',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'google-docs-sync',
        name: 'Google Docs Synkronisering',
        path: '/folders/smart-notes-system/google-docs-sync',
        category: 'smart_notes',
        description: 'Synkroniserte Google Docs dokumenter',
        permissions: ['admin'],
        autoGenerated: true,
      },
    ],
  },

  // Admin System Folders
  {
    id: 'admin-system',
    name: 'Administrasjonssystem',
    path: '/folders/admin-system',
    category: 'admin',
    description: 'Komplett administrasjonssystem for Daniel med full plattformkontroll',
    permissions: ['admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'feature-control',
        name: 'Funksjonskontroll',
        path: '/folders/admin-system/feature-control',
        category: 'admin',
        description: 'Administrasjon av alle plattformfunksjoner',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'user-management',
        name: 'Brukerhåndtering',
        path: '/folders/admin-system/user-management',
        category: 'admin',
        description: 'Brukeradministrasjon og tilgangskontroll',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'platform-monitoring',
        name: 'Plattformovervåkning',
        path: '/folders/admin-system/platform-monitoring',
        category: 'admin',
        description: 'Systemovervåkning og ytelsesanalyse',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'magic-creator-control',
        name: 'Magic Creator Kontroll',
        path: '/folders/admin-system/magic-creator-control',
        category: 'admin',
        description: 'Administrasjon av Magic Creator systemet',
        permissions: ['admin'],
        autoGenerated: true,
      },
    ],
  },

  // Academy System
  {
    id: 'academy-system',
    name: 'CreatorHub Academy',
    path: '/folders/academy-system',
    category: 'system',
    description: 'Utdanningssystem med HD videokurs og norske instruktører',
    permissions: ['all'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'photography-courses',
        name: 'Fotograferingskurs',
        path: '/folders/academy-system/photography-courses',
        category: 'system',
        description: 'Profesjonelle fotograferingskurs',
        permissions: ['all'],
        autoGenerated: true,
      },
      {
        id: 'videography-courses',
        name: 'Videografikurs',
        path: '/folders/academy-system/videography-courses',
        category: 'system',
        description: 'Avanserte videografikurs',
        permissions: ['all'],
        autoGenerated: true,
      },
      {
        id: 'music-production-courses',
        name: 'Musikkproduksjonskurs',
        path: '/folders/academy-system/music-production-courses',
        category: 'system',
        description: 'Musikkproduksjon og studio kurs',
        permissions: ['all'],
        autoGenerated: true,
      },
    ],
  },

  // AI and Automation Systems
  {
    id: 'ai-automation-system',
    name: 'AI og Automatisering',
    path: '/folders/ai-automation-system',
    category: 'system',
    description: 'AI-drevet automatisering og intelligente systemer',
    permissions: ['admin'],
    autoGenerated: true,
    subFolders: [
      {
        id: 'workflow-automation',
        name: 'Arbeidsflytautomatisering',
        path: '/folders/ai-automation-system/workflow-automation',
        category: 'system',
        description: 'Automatiserte arbeidsflyter og prosesser',
        permissions: ['admin'],
        autoGenerated: true,
      },
      {
        id: 'magic-creator-features',
        name: 'Magic Creator Funksjoner',
        path: '/folders/ai-automation-system/magic-creator-features',
        category: 'system',
        description: 'Genererte funksjoner fra Magic Creator',
        permissions: ['admin'],
        autoGenerated: true,
      },
    ],
  },
];

// Function to get folders for specific user permissions
export function getFoldersForUser(userPermissions: string[]): PlatformFolder[] {
  return AUTO_GENERATED_FOLDERS.filter((folder) =>
    folder.permissions.some(
      (permission) => userPermissions.includes(permission) || permission === 'all',
    ),
  );
}

// Function to get all admin folders for Daniel
export function getDanielAdminFolders(): PlatformFolder[] {
  return AUTO_GENERATED_FOLDERS.filter((folder) => folder.permissions.includes('admin'));
}

// Function to create folder structure for new user
export function generateUserFolderStructure(userType: string): PlatformFolder[] {
  const userPermissions = [userType, 'all'];
  return getFoldersForUser(userPermissions);
}
