/**
 * CreatorHub Norge - Resume/CV Builder Schema
 * Comprehensive resume management system with AI assistance and ATS optimization
 */

import {
  pgTable,
  text,
  varchar,
  timestamp,
  jsonb,
  integer,
  boolean,
  uuid,
  serial,
  index,
  unique,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';

// ============================================================================
// RESUME/CV CORE TABLES
// ============================================================================

/**
 * Main resume/CV document
 * Each user can have multiple resumes for different purposes
 */
export const resumes = pgTable(
  'resumes',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: varchar('user_id').notNull(),

    // Basic Information
    title: varchar('title', { length: 255 }).notNull(), // e.g., "Senior Photographer Resume"
    slug: varchar('slug', { length: 255 }).notNull(),

    // Personal Information
    personalInfo: jsonb('personal_info')
      .$type<{
        fullName: string;
        email: string;
        phone?: string;
        location?: string;
        website?: string;
        linkedin?: string;
        github?: string;
        portfolio?: string;
        profilePhoto?: string;
        professionalTitle?: string;
        summary?: string;
      }>()
      .notNull(),

    // Template & Styling
    templateId: varchar('template_id').notNull().default('modern-ats'),
    colorScheme: varchar('color_scheme', { length: 50 }).default('professional-blue'),
    customColors: jsonb('custom_colors').$type<{
      primary?: string;
      secondary?: string;
      accent?: string;
      text?: string;
      background?: string;
    }>(),

    // ATS Optimization
    atsScore: integer('ats_score').default(0), // 0-100
    atsOptimized: boolean('ats_optimized').default(false),
    keywords: text('keywords').array(),
    targetJobTitle: varchar('target_job_title', { length: 255 }),
    targetIndustry: varchar('target_industry', { length: 255 }),

    // AI Assistance
    aiGenerated: boolean('ai_generated').default(false),
    aiSuggestions: jsonb('ai_suggestions').$type<{
      summary?: string[];
      skills?: string[];
      improvements?: string[];
    }>(),
    lastAIAnalysis: timestamp('last_ai_analysis'),

    // Status & Visibility
    status: varchar('status', { length: 50 })
      .$type<'draft' | 'active' | 'archived'>()
      .default('draft'),
    isPublic: boolean('is_public').default(false),
    publicUrl: varchar('public_url', { length: 255 }),

    // Metadata
    language: varchar('language', { length: 10 }).default('no'),
    version: integer('version').default(1),
    lastExported: timestamp('last_exported'),
    exportCount: integer('export_count').default(0),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    userIdIdx: index('resumes_user_id_idx').on(table.userId),
    slugIdx: index('resumes_slug_idx').on(table.slug),
    statusIdx: index('resumes_status_idx').on(table.status),
    uniqueUserSlug: unique('resumes_user_slug_unique').on(table.userId, table.slug),
  }),
);

/**
 * Work Experience entries from completed projects
 * Automatically populated from ProjectTimeline
 */
export const resumeExperiences = pgTable(
  'resume_experiences',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id, { onDelete: 'cascade' }),
    userId: varchar('user_id').notNull(),

    // Experience Details
    jobTitle: varchar('job_title', { length: 255 }).notNull(),
    company: varchar('company', { length: 255 }).notNull(),
    location: varchar('location', { length: 255 }),
    employmentType: varchar('employment_type', { length: 50 }).$type<
      'full-time' | 'part-time' | 'contract' | 'freelance' | 'self-employed'
    >(),

    startDate: timestamp('start_date').notNull(),
    endDate: timestamp('end_date'),
    isCurrent: boolean('is_current').default(false),

    description: text('description'),
    achievements: text('achievements').array(),
    skills: text('skills').array(),

    // Project Integration
    projectId: varchar('project_id'), // Link to completed project
    autoGenerated: boolean('auto_generated').default(false),

    // Display Order
    displayOrder: integer('display_order').default(0),
    isVisible: boolean('is_visible').default(true),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_experiences_resume_id_idx').on(table.resumeId),
    projectIdIdx: index('resume_experiences_project_id_idx').on(table.projectId),
  }),
);

/**
 * Education entries
 */
export const resumeEducation = pgTable(
  'resume_education',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id, { onDelete: 'cascade' }),
    userId: varchar('user_id').notNull(),

    degree: varchar('degree', { length: 255 }).notNull(),
    fieldOfStudy: varchar('field_of_study', { length: 255 }),
    institution: varchar('institution', { length: 255 }).notNull(),
    location: varchar('location', { length: 255 }),

    startDate: timestamp('start_date').notNull(),
    endDate: timestamp('end_date'),
    isCurrent: boolean('is_current').default(false),

    grade: varchar('grade', { length: 50 }),
    description: text('description'),
    achievements: text('achievements').array(),

    displayOrder: integer('display_order').default(0),
    isVisible: boolean('is_visible').default(true),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_education_resume_id_idx').on(table.resumeId),
  }),
);

/**
 * Skills & Competencies
 */
export const resumeSkills = pgTable(
  'resume_skills',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id, { onDelete: 'cascade' }),
    userId: varchar('user_id').notNull(),

    name: varchar('name', { length: 255 }).notNull(),
    category: varchar('category', { length: 100 }), // e.g., 'Technical', 'Software', 'Languages'
    proficiencyLevel: integer('proficiency_level').default(50), // 0-100
    yearsOfExperience: integer('years_of_experience'),

    isEndorsed: boolean('is_endorsed').default(false),
    endorsementCount: integer('endorsement_count').default(0),

    displayOrder: integer('display_order').default(0),
    isVisible: boolean('is_visible').default(true),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_skills_resume_id_idx').on(table.resumeId),
    categoryIdx: index('resume_skills_category_idx').on(table.category),
  }),
);

/**
 * Certifications & Awards
 */
export const resumeCertifications = pgTable(
  'resume_certifications',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id, { onDelete: 'cascade' }),
    userId: varchar('user_id').notNull(),

    name: varchar('name', { length: 255 }).notNull(),
    issuer: varchar('issuer', { length: 255 }).notNull(),
    issueDate: timestamp('issue_date').notNull(),
    expiryDate: timestamp('expiry_date'),
    credentialId: varchar('credential_id', { length: 255 }),
    credentialUrl: varchar('credential_url', { length: 500 }),

    description: text('description'),

    displayOrder: integer('display_order').default(0),
    isVisible: boolean('is_visible').default(true),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_certifications_resume_id_idx').on(table.resumeId),
  }),
);

/**
 * Projects & Portfolio Items
 * Automatically populated from completed projects
 */
export const resumeProjects = pgTable(
  'resume_projects',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id, { onDelete: 'cascade' }),
    userId: varchar('user_id').notNull(),

    title: varchar('title', { length: 255 }).notNull(),
    description: text('description'),
    role: varchar('role', { length: 255 }),

    startDate: timestamp('start_date'),
    endDate: timestamp('end_date'),

    technologies: text('technologies').array(),
    achievements: text('achievements').array(),

    projectUrl: varchar('project_url', { length: 500 }),
    images: text('images').array(),

    // Project Integration
    projectId: varchar('project_id'), // Link to actual project
    autoGenerated: boolean('auto_generated').default(false),

    displayOrder: integer('display_order').default(0),
    isVisible: boolean('is_visible').default(true),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_projects_resume_id_idx').on(table.resumeId),
    projectIdIdx: index('resume_projects_project_id_idx').on(table.projectId),
  }),
);

/**
 * Resume Templates
 * Pre-designed ATS-friendly templates
 */
export const resumeTemplates = pgTable(
  'resume_templates',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),

    name: varchar('name', { length: 255 }).notNull(),
    description: text('description'),
    category: varchar('category', { length: 100 }), // 'professional', 'creative', 'modern', etc.

    // ATS Compatibility
    atsScore: integer('ats_score').default(100), // Template's inherent ATS score
    isAtsOptimized: boolean('is_ats_optimized').default(true),

    // Template Structure
    layout: varchar('layout', { length: 50 }).$type<
      'single-column' | 'two-column' | 'modern-split'
    >(),
    sections: jsonb('sections').$type<string[]>(), // Enabled sections

    // Styling
    previewImage: varchar('preview_image', { length: 500 }),
    colorSchemes: jsonb('color_schemes').$type<string[]>(),
    fonts: jsonb('fonts').$type<{
      heading?: string;
      body?: string;
    }>(),

    // Metadata
    isPremium: boolean('is_premium').default(false),
    usageCount: integer('usage_count').default(0),
    rating: integer('rating').default(0), // 0-5 stars

    isActive: boolean('is_active').default(true),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    categoryIdx: index('resume_templates_category_idx').on(table.category),
    isActiveIdx: index('resume_templates_is_active_idx').on(table.isActive),
  }),
);

/**
 * Job Application Tracking
 * Track job applications with Norwegian job sites
 */
export const jobApplications = pgTable(
  'job_applications',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: varchar('user_id').notNull(),
    resumeId: varchar('resume_id').references(() => resumes.id),

    // Job Details
    jobTitle: varchar('job_title', { length: 255 }).notNull(),
    company: varchar('company', { length: 255 }).notNull(),
    location: varchar('location', { length: 255 }),
    jobUrl: varchar('job_url', { length: 500 }),

    // Source
    source: varchar('source', { length: 100 }), // 'finn.no', 'nav.no', 'linkedin', etc.
    jobId: varchar('job_id', { length: 255 }), // External job ID

    // Application Status
    status: varchar('status', { length: 50 })
      .$type<
        'saved' | 'applied' | 'interviewing' | 'offer' | 'rejected' | 'accepted' | 'withdrawn'
      >()
      .default('saved'),

    appliedDate: timestamp('applied_date'),
    responseDate: timestamp('response_date'),
    interviewDate: timestamp('interview_date'),
    offerDate: timestamp('offer_date'),

    // Application Details
    coverLetter: text('cover_letter'),
    notes: text('notes'),
    salary: varchar('salary', { length: 100 }),

    // Reminders & Follow-ups
    followUpDate: timestamp('follow_up_date'),
    reminderSent: boolean('reminder_sent').default(false),

    // Metadata
    priority: varchar('priority', { length: 20 })
      .$type<'low' | 'medium' | 'high'>()
      .default('medium'),
    tags: text('tags').array(),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    userIdIdx: index('job_applications_user_id_idx').on(table.userId),
    statusIdx: index('job_applications_status_idx').on(table.status),
    sourceIdx: index('job_applications_source_idx').on(table.source),
  }),
);

/**
 * Norwegian Job Sites Configuration
 * Track and scrape job postings from Norwegian sources
 */
export const jobSources = pgTable('job_sources', {
  id: varchar('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),

  name: varchar('name', { length: 255 }).notNull(),
  url: varchar('url', { length: 500 }).notNull(),
  country: varchar('country', { length: 50 }).default('Norway'),

  // Scraping Configuration
  isActive: boolean('is_active').default(true),
  scrapingEnabled: boolean('scraping_enabled').default(false),
  apiEnabled: boolean('api_enabled').default(false),
  apiKey: varchar('api_key', { length: 500 }),

  // Metadata
  jobCount: integer('job_count').default(0),
  lastScraped: timestamp('last_scraped'),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/**
 * Resume Export History
 * Track all exports for analytics
 */
export const resumeExports = pgTable(
  'resume_exports',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id),
    userId: varchar('user_id').notNull(),

    format: varchar('format', { length: 50 })
      .$type<'pdf' | 'docx' | 'txt' | 'json' | 'html'>()
      .notNull(),
    fileUrl: varchar('file_url', { length: 500 }),
    fileSize: integer('file_size'), // in bytes

    exportedAt: timestamp('exported_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_exports_resume_id_idx').on(table.resumeId),
    formatIdx: index('resume_exports_format_idx').on(table.format),
  }),
);

/**
 * AI Analysis Results
 * Store AI-generated suggestions and improvements
 */
export const resumeAiAnalyses = pgTable(
  'resume_ai_analyses',
  {
    id: varchar('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resumeId: varchar('resume_id')
      .notNull()
      .references(() => resumes.id),
    userId: varchar('user_id').notNull(),

    // Analysis Type
    analysisType: varchar('analysis_type', { length: 50 })
      .$type<'ats_optimization' | 'keyword_match' | 'content_improvement' | 'grammar_check'>()
      .notNull(),

    // Results
    score: integer('score'), // 0-100
    suggestions: jsonb('suggestions').$type<
      Array<{
        type: string;
        severity: 'low' | 'medium' | 'high';
        message: string;
        suggestion: string;
      }>
    >(),

    // Keywords Analysis
    matchedKeywords: text('matched_keywords').array(),
    missingKeywords: text('missing_keywords').array(),

    // Job Description Match
    jobDescription: text('job_description'),
    matchScore: integer('match_score'), // 0-100

    analyzedAt: timestamp('analyzed_at').defaultNow().notNull(),
  },
  (table) => ({
    resumeIdIdx: index('resume_ai_analyses_resume_id_idx').on(table.resumeId),
    analysisTypeIdx: index('resume_ai_analyses_type_idx').on(table.analysisType),
  }),
);

// ============================================================================
// RELATIONS
// ============================================================================

export const resumesRelations = relations(resumes, ({ many }) => ({
  experiences: many(resumeExperiences),
  education: many(resumeEducation),
  skills: many(resumeSkills),
  certifications: many(resumeCertifications),
  projects: many(resumeProjects),
  exports: many(resumeExports),
  aiAnalyses: many(resumeAiAnalyses),
}));

export const resumeExperiencesRelations = relations(resumeExperiences, ({ one }) => ({
  resume: one(resumes, {
    fields: [resumeExperiences.resumeId],
    references: [resumes.id],
  }),
}));

export const resumeEducationRelations = relations(resumeEducation, ({ one }) => ({
  resume: one(resumes, {
    fields: [resumeEducation.resumeId],
    references: [resumes.id],
  }),
}));

export const resumeSkillsRelations = relations(resumeSkills, ({ one }) => ({
  resume: one(resumes, {
    fields: [resumeSkills.resumeId],
    references: [resumes.id],
  }),
}));

export const resumeCertificationsRelations = relations(resumeCertifications, ({ one }) => ({
  resume: one(resumes, {
    fields: [resumeCertifications.resumeId],
    references: [resumes.id],
  }),
}));

export const resumeProjectsRelations = relations(resumeProjects, ({ one }) => ({
  resume: one(resumes, {
    fields: [resumeProjects.resumeId],
    references: [resumes.id],
  }),
}));

export const jobApplicationsRelations = relations(jobApplications, ({ one }) => ({
  resume: one(resumes, {
    fields: [jobApplications.resumeId],
    references: [resumes.id],
  }),
}));

// ============================================================================
// ZOD SCHEMAS
// ============================================================================

export const insertResumeSchema = createInsertSchema(resumes);
export const selectResumeSchema = createSelectSchema(resumes);

export const insertExperienceSchema = createInsertSchema(resumeExperiences);
export const selectExperienceSchema = createSelectSchema(resumeExperiences);

export const insertEducationSchema = createInsertSchema(resumeEducation);
export const selectEducationSchema = createSelectSchema(resumeEducation);

export const insertSkillSchema = createInsertSchema(resumeSkills);
export const selectSkillSchema = createSelectSchema(resumeSkills);

export const insertCertificationSchema = createInsertSchema(resumeCertifications);
export const selectCertificationSchema = createSelectSchema(resumeCertifications);

export const insertProjectSchema = createInsertSchema(resumeProjects);
export const selectProjectSchema = createSelectSchema(resumeProjects);

export const insertJobApplicationSchema = createInsertSchema(jobApplications);
export const selectJobApplicationSchema = createSelectSchema(jobApplications);

// ============================================================================
// TYPESCRIPT TYPES
// ============================================================================

export type Resume = typeof resumes.$inferSelect;
export type InsertResume = typeof resumes.$inferInsert;

export type ResumeExperience = typeof resumeExperiences.$inferSelect;
export type InsertResumeExperience = typeof resumeExperiences.$inferInsert;

export type ResumeEducation = typeof resumeEducation.$inferSelect;
export type InsertResumeEducation = typeof resumeEducation.$inferInsert;

export type ResumeSkill = typeof resumeSkills.$inferSelect;
export type InsertResumeSkill = typeof resumeSkills.$inferInsert;

export type ResumeCertification = typeof resumeCertifications.$inferSelect;
export type InsertResumeCertification = typeof resumeCertifications.$inferInsert;

export type ResumeProject = typeof resumeProjects.$inferSelect;
export type InsertResumeProject = typeof resumeProjects.$inferInsert;

export type ResumeTemplate = typeof resumeTemplates.$inferSelect;
export type InsertResumeTemplate = typeof resumeTemplates.$inferInsert;

export type JobApplication = typeof jobApplications.$inferSelect;
export type InsertJobApplication = typeof jobApplications.$inferInsert;

export type JobSource = typeof jobSources.$inferSelect;
export type InsertJobSource = typeof jobSources.$inferInsert;

export type ResumeExport = typeof resumeExports.$inferSelect;
export type InsertResumeExport = typeof resumeExports.$inferInsert;

export type ResumeAiAnalysis = typeof resumeAiAnalyses.$inferSelect;
export type InsertResumeAiAnalysis = typeof resumeAiAnalyses.$inferInsert;
