/**
 * Story Arc Studio - Complete Database Schema
 * Supports intelligent content analysis, auto monitoring, and story arc generation
 */

import {
  pgTable,
  text,
  varchar,
  timestamp,
  jsonb,
  integer,
  boolean,
  decimal,
  uuid,
  real,
  index,
} from 'drizzle-orm/pg-core';
import { relations, sql } from 'drizzle-orm';
import { createInsertSchema } from 'drizzle-zod';
import { z } from 'zod';

// Story Arc Projects - Main projects table
export const storyArcProjects = pgTable(
  'story_arc_projects',
  {
    id: varchar('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    userId: varchar('user_id').notNull(),
    storyArcName: varchar('story_arc_name', { length: 255 }).notNull(),
    status: varchar('status').notNull().default('initialized'), // 'initialized', 'processing', 'completed', 'error'

    // Project settings
    templateType: varchar('template_type').notNull(), // 'wedding', 'corporate', 'music_video', 'documentary', 'event', 'portrait'
    emotionalCurve: varchar('emotional_curve').notNull(), // 'rising', 'falling', 'wave', 'mountain'
    targetDuration: integer('target_duration').notNull(), // in seconds

    // Source information
    sourceVideoId: varchar('source_video_id'), // Google Drive file ID
    sourceVideoName: varchar('source_video_name'),
    triggerFolder: varchar('trigger_folder'), // Which folder triggered the creation

    // Project metadata
    autoGenerated: boolean('auto_generated').default(false),
    driveFolder: jsonb('drive_folder').$type<{
      id: string;
      path: string;
      url?: string;
    }>(),

    // Content analysis results
    contentAnalysis: jsonb('content_analysis').$type<{
      contentType: string;
      confidence: number;
      detectedElements: string[];
      analysisDetails: {
        fileName: string;
        fileSize: number;
        duration?: number;
        metadata?: any;
      };
    }>(),

    // Generated story arc data
    storyArcData: jsonb('story_arc_data').$type<{
      structure: string;
      emotionalFlow: number[];
      keyMoments: any[];
      scenes: any[];
      transitions: any[];
      musicSuggestions: any[];
    }>(),

    // Export information
    exportedFiles: jsonb('exported_files').$type<{
      davinciResolve?: {
        xmlPath: string;
        exportedAt: string;
      };
      finalCutPro?: {
        fcpxmlPath: string;
        exportedAt: string;
      };
      premiereProj?: {
        prprojPath: string;
        exportedAt: string;
      };
    }>(),

    // Timestamps
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
    completedAt: timestamp('completed_at'),
  },
  (table) => ({
    userIdIdx: index('story_arc_projects_user_id_idx').on(table.userId),
    statusIdx: index('story_arc_projects_status_idx').on(table.status),
    templateTypeIdx: index('story_arc_projects_template_type_idx').on(table.templateType),
    createdAtIdx: index('story_arc_projects_created_at_idx').on(table.createdAt),
  }),
);

// Auto Monitor Configurations - Settings for automatic monitoring
export const autoMonitorConfigs = pgTable(
  'auto_monitor_configs',
  {
    id: varchar('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    userId: varchar('user_id').notNull(),
    monitorFolderName: varchar('monitor_folder_name').notNull(), // 'studio_arc_create'
    isActive: boolean('is_active').default(true),

    // Monitoring settings
    checkIntervalMinutes: integer('check_interval_minutes').default(5),
    lastCheckedAt: timestamp('last_checked_at'),

    // Auto generation settings
    autoGenerateEnabled: boolean('auto_generate_enabled').default(true),
    defaultTemplateType: varchar('default_template_type').default('wedding'),
    defaultEmotionalCurve: varchar('default_emotional_curve').default('rising'),
    defaultTargetDuration: integer('default_target_duration').default(480), // 8 minutes

    // Advanced settings
    confidenceThreshold: real('confidence_threshold').default(0.3), // Minimum confidence for using intelligent settings
    moveProcessedFiles: boolean('move_processed_files').default(true),
    notificationSettings: jsonb('notification_settings').$type<{
      emailOnSuccess: boolean;
      emailOnError: boolean;
      webhookUrl?: string;
    }>(),

    // Statistics
    totalFilesProcessed: integer('total_files_processed').default(0),
    successfulGenerations: integer('successful_generations').default(0),
    failedGenerations: integer('failed_generations').default(0),

    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
  },
  (table) => ({
    userIdIdx: index('auto_monitor_configs_user_id_idx').on(table.userId),
    isActiveIdx: index('auto_monitor_configs_is_active_idx').on(table.isActive),
    monitorFolderIdx: index('auto_monitor_configs_monitor_folder_idx').on(table.monitorFolderName),
  }),
);

// Processed Files - Track files that have been processed
export const processedFiles = pgTable(
  'processed_files',
  {
    id: varchar('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    userId: varchar('user_id').notNull(),
    configId: varchar('config_id')
      .notNull()
      .references(() => autoMonitorConfigs.id),

    // File information
    fileId: varchar('file_id').notNull(), // Google Drive file ID
    fileName: varchar('file_name').notNull(),
    mimeType: varchar('mime_type'),
    fileSize: integer('file_size'), // in bytes
    originalPath: varchar('original_path'), // Original location in Drive
    processedPath: varchar('processed_path'), // Location after processing

    // Processing status
    processed: boolean('processed').default(false),
    processingError: text('processing_error'),
    processingStartedAt: timestamp('processing_started_at'),
    processingCompletedAt: timestamp('processing_completed_at'),

    // Generated story arc reference
    storyArcProjectId: varchar('story_arc_project_id').references(() => storyArcProjects.id),

    // Content analysis results
    contentAnalysis: jsonb('content_analysis').$type<{
      contentType: string;
      confidence: number;
      detectedElements: string[];
      suggestedSettings: {
        templateType: string;
        emotionalCurve: string;
        targetDuration: number;
      };
      analysisDetails: {
        fileName: string;
        fileSize: number;
        duration?: number;
        metadata?: any;
      };
    }>(),

    // Intelligent settings used
    intelligentSettings: jsonb('intelligent_settings').$type<{
      detectedType: string;
      confidence: number;
      usedSettings: {
        templateType: string;
        emotionalCurve: string;
        targetDuration: number;
      };
      fallbackToDefault: boolean;
    }>(),

    uploadedAt: timestamp('uploaded_at').notNull(),
    createdAt: timestamp('created_at').defaultNow(),
  },
  (table) => ({
    userIdIdx: index('processed_files_user_id_idx').on(table.userId),
    configIdIdx: index('processed_files_config_id_idx').on(table.configId),
    fileIdIdx: index('processed_files_file_id_idx').on(table.fileId),
    processedIdx: index('processed_files_processed_idx').on(table.processed),
    storyArcProjectIdIdx: index('processed_files_story_arc_project_id_idx').on(
      table.storyArcProjectId,
    ),
    uploadedAtIdx: index('processed_files_uploaded_at_idx').on(table.uploadedAt),
  }),
);

// Content Analysis Cache - Cache analysis results to avoid re-processing
export const contentAnalysisCache = pgTable(
  'content_analysis_cache',
  {
    id: varchar('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),

    // File identification
    fileId: varchar('file_id').notNull().unique(), // Google Drive file ID
    fileName: varchar('file_name').notNull(),
    fileHash: varchar('file_hash'), // MD5 hash for integrity checking

    // Analysis results
    contentType: varchar('content_type').notNull(),
    confidence: real('confidence').notNull(),
    detectedElements: jsonb('detected_elements').$type<string[]>(),

    // Suggested settings
    suggestedSettings: jsonb('suggested_settings').$type<{
      templateType: string;
      emotionalCurve: string;
      targetDuration: number;
    }>(),

    // Analysis details
    analysisDetails: jsonb('analysis_details').$type<{
      fileName: string;
      fileSize: number;
      duration?: number;
      metadata?: any;
      keywordsFound: string[];
      metadataFactors: any;
    }>(),

    // Cache metadata
    analysisVersion: varchar('analysis_version').default('1.0'), // For algorithm versioning
    createdAt: timestamp('created_at').defaultNow(),
    lastUsedAt: timestamp('last_used_at').defaultNow(),
    expiresAt: timestamp('expires_at'), // For cache expiration
  },
  (table) => ({
    fileIdIdx: index('content_analysis_cache_file_id_idx').on(table.fileId),
    contentTypeIdx: index('content_analysis_cache_content_type_idx').on(table.contentType),
    createdAtIdx: index('content_analysis_cache_created_at_idx').on(table.createdAt),
    expiresAtIdx: index('content_analysis_cache_expires_at_idx').on(table.expiresAt),
  }),
);

// Story Arc Templates - Predefined templates for different content types
export const storyArcTemplates = pgTable(
  'story_arc_templates',
  {
    id: varchar('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    name: varchar('name', { length: 255 }).notNull(),
    contentType: varchar('content_type').notNull(), // 'wedding', 'corporate', etc.
    emotionalCurve: varchar('emotional_curve').notNull(),

    // Template configuration
    defaultDuration: integer('default_duration').notNull(),
    isDefault: boolean('is_default').default(false),
    isActive: boolean('is_active').default(true),

    // Template structure
    storyStructure: jsonb('story_structure').$type<{
      acts: Array<{
        name: string;
        duration: number;
        emotionalLevel: number;
        keyElements: string[];
      }>;
      transitions: Array<{
        type: string;
        duration: number;
        style: string;
      }>;
      musicSuggestions: Array<{
        mood: string;
        genre: string;
        energy: number;
      }>;
    }>(),

    // Usage statistics
    timesUsed: integer('times_used').default(0),
    lastUsedAt: timestamp('last_used_at'),

    // Metadata
    description: text('description'),
    tags: jsonb('tags').$type<string[]>(),
    culturalContext: varchar('cultural_context'), // 'norwegian', 'international', etc.

    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
  },
  (table) => ({
    contentTypeIdx: index('story_arc_templates_content_type_idx').on(table.contentType),
    isDefaultIdx: index('story_arc_templates_is_default_idx').on(table.isDefault),
    isActiveIdx: index('story_arc_templates_is_active_idx').on(table.isActive),
  }),
);

// Relations
export const storyArcProjectsRelations = relations(storyArcProjects, ({ many }) => ({
  processedFiles: many(processedFiles),
}));

export const autoMonitorConfigsRelations = relations(autoMonitorConfigs, ({ many }) => ({
  processedFiles: many(processedFiles),
}));

export const processedFilesRelations = relations(processedFiles, ({ one }) => ({
  config: one(autoMonitorConfigs, {
    fields: [processedFiles.configId],
    references: [autoMonitorConfigs.id],
  }),
  storyArcProject: one(storyArcProjects, {
    fields: [processedFiles.storyArcProjectId],
    references: [storyArcProjects.id],
  }),
}));

// Insert schemas
export const insertStoryArcProjectSchema = createInsertSchema(storyArcProjects);
export const insertAutoMonitorConfigSchema = createInsertSchema(autoMonitorConfigs);
export const insertProcessedFileSchema = createInsertSchema(processedFiles);
export const insertContentAnalysisCacheSchema = createInsertSchema(contentAnalysisCache);
export const insertStoryArcTemplateSchema = createInsertSchema(storyArcTemplates);

// Select types
export type StoryArcProject = typeof storyArcProjects.$inferSelect;
export type AutoMonitorConfig = typeof autoMonitorConfigs.$inferSelect;
export type ProcessedFile = typeof processedFiles.$inferSelect;
export type ContentAnalysisCache = typeof contentAnalysisCache.$inferSelect;
export type StoryArcTemplate = typeof storyArcTemplates.$inferSelect;

// Insert types
export type InsertStoryArcProject = z.infer<typeof insertStoryArcProjectSchema>;
export type InsertAutoMonitorConfig = z.infer<typeof insertAutoMonitorConfigSchema>;
export type InsertProcessedFile = z.infer<typeof insertProcessedFileSchema>;
export type InsertContentAnalysisCache = z.infer<typeof insertContentAnalysisCacheSchema>;
export type InsertStoryArcTemplate = z.infer<typeof insertStoryArcTemplateSchema>;

// API schemas for validation
export const createStoryArcProjectSchema = z.object({
  userId: z.string(),
  storyArcName: z.string().min(1).max(255),
  templateType: z.enum(['wedding', 'corporate', 'music_video', 'documentary', 'event', 'portrait']),
  emotionalCurve: z.enum(['rising', 'falling', 'wave', 'mountain']),
  targetDuration: z.number().min(60).max(3600),
  sourceVideoId: z.string().optional(),
  sourceVideoName: z.string().optional(),
  autoGenerated: z.boolean().default(false),
});

export const enableAutoMonitoringSchema = z.object({
  userId: z.string(),
  monitorFolderName: z.string(),
  checkIntervalMinutes: z.number().min(1).max(60).default(5),
  autoGenerateSettings: z.object({
    enabled: z.boolean().default(true),
    templateType: z.enum([
      'wedding',
      'corporate',
      'music_video',
      'documentary',
      'event',
      'portrait',
    ]),
    emotionalCurve: z.enum(['rising', 'falling', 'wave', 'mountain']),
    targetDuration: z.number().min(60).max(3600),
  }),
});

export const contentAnalysisSchema = z.object({
  contentType: z.enum([
    'wedding',
    'corporate',
    'music_video',
    'documentary',
    'event',
    'portrait',
    'unknown',
  ]),
  confidence: z.number().min(0).max(1),
  detectedElements: z.array(z.string()),
  suggestedSettings: z.object({
    templateType: z.string(),
    emotionalCurve: z.string(),
    targetDuration: z.number(),
  }),
  analysisDetails: z.object({
    fileName: z.string(),
    fileSize: z.number(),
    duration: z.number().optional(),
    metadata: z.any().optional(),
  }),
});

// Response schemas
export const storyArcProjectResponseSchema = z.object({
  success: z.boolean(),
  storyArcId: z.string().optional(),
  folderId: z.string().optional(),
  error: z.string().optional(),
});

export const autoMonitorStatusResponseSchema = z.object({
  activeMonitors: z.array(
    z.object({
      userId: z.string(),
      monitorFolderName: z.string(),
      checkIntervalMinutes: z.number(),
      autoGenerateSettings: z.object({
        enabled: z.boolean(),
        templateType: z.string(),
        emotionalCurve: z.string(),
        targetDuration: z.number(),
      }),
    }),
  ),
  processedFiles: z.record(
    z.string(),
    z.array(
      z.object({
        fileId: z.string(),
        fileName: z.string(),
        mimeType: z.string(),
        uploadedAt: z.string(),
        processed: z.boolean(),
        storyArcId: z.string().optional(),
        processingError: z.string().optional(),
        contentAnalysis: contentAnalysisSchema.optional(),
        intelligentSettings: z
          .object({
            detectedType: z.string(),
            confidence: z.number(),
            usedSettings: z.object({
              templateType: z.string(),
              emotionalCurve: z.string(),
              targetDuration: z.number(),
            }),
          })
          .optional(),
      }),
    ),
  ),
});
